### ISSUE TITLE
Add support for Traits (PHP 5.4)

### ISSUE THREAD

**Issue by ruimarinho** [schmittjoh/JMSSerializerBundle#102]
PHP 5.4.0 includes support for Traits and with them, new patterns for "drop in" functionality will likely gain attraction in the following months.

For example, a `User` could use Traits for mapping social networks profiles, such as Facebook or Twitter. Another interesting use case is to easily include Doctrine behaviors without having to rely on much more complex code. KnpLabs recently blogged about this new way of dealing with behaviors on a [blog post](http://knplabs.com/blog/knp-doctrine-orm-behaviors).

This issue is a request to include support for mapping metadata when using Traits.

**Comment by nass600** [comment]
Same here

**Comment by kmonmousseau** [comment]
+1

**Comment by drewsonian** [comment]
+1

**Comment by PLEEROCK** [comment]
+1

**Comment by floriansemm** [comment]
+1

**Comment by giovkanata** [comment]
+1

**Comment by cfoehrdes** [comment]
+1

**Comment by jamesisaac** [comment]
+1, exposing Doctrine behaviour traits (https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/timestampable.md#traits) involves a load of redundant copy/pasting without trait support in the serializer.

**Comment by epoplive** [comment]
Yeah for real, this is basically making JMS Serializer to be useless for me, since I attach stuff like the entity manager via a trait and I can't seem to exclude.

**Comment by barduck007** [comment]
+1

**Comment by hhsissi** [comment]
+1

**Comment by ajanssen** [comment]
What is the current status?

**Comment by EmmanuelVella** [comment]
+1

**Comment by JulianStier** [comment]
+1

**Comment by mikelohmann** [comment]
+1

**Comment by sdecandelario** [comment]
+1

Anyone find a solution for this?

**Comment by drewclauson** [comment]
+1

**Comment by drewclauson** [comment]
Actually, I'm not having any problems with fields on traits being serialized, just using the Doctrine\ORM\Mapping and JMS\Serializer\Annotation annotations.

**Comment by liverbool** [comment]
+1

**Comment by choco-julie** [comment]
Traits methods aren't available after deserialization

**Comment by IndyIndyIndy** [comment]
+1

**Comment by kokmok** [comment]
+1 
Traits properties are serialized by default but the Groups doesn't work. 

`trait VendableTrait
{

    /**
     * @var Pricing
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Pricing",cascade={"all"})
     * @Groups({"base"})
     */
    protected $basePrice;
//...
`
` /**
     * @param $id
     * @return object
     * @ApiDoc(
     *     section= "MeetingRooms",
     * )
     * @View(serializerGroups={"base"})
     */
    public function getAction($id)
    {
`
The property basePrice is exposed only if I remove the View annotation

**Comment by vinaocruz** [comment]
+1

**Comment by stepansib** [comment]
+1
Still cant serialize properties defined in traits...

**Comment by atournayre** [comment]
I found a solution (for me)

**Before, my code was this :**

```
<?php

namespace App\Doctrine\Traits;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Groups;

trait IdTrait
{
    /**
     * Id.
     *
     * @Groups({"elastica"})
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
}
```

**Working code :**

```
<?php

namespace App\Doctrine\Traits;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class IdTrait.
 */
trait IdTrait
{
    /**
     * Id.
     *
     * @JMS\Serializer\Annotation\Groups({"elastica"})
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
}
```

**Comment by spackmat** [comment]
I have the exact opposite problem. I am using the `Knp\DoctrineBehaviors\Model\Blameable\Blameable` Trait and this serializes the whole user objects with all roles, passwords and really everything and in general, I cannot control the MaxDepth() of properties implemented in traits with Annotations.

When I set `@ExclusionPolicy("all")` on my User entity extending the BaseUser of FOSUserBundle, the problem from #100 kicks in. So for now, I cannot get rid of the User internals like passworthashes in all Entities that use the Bameable Trait. That means nearly all my Entities.

How do others handle this? Combining [knplabs/doctrine-behaviors](https://github.com/KnpLabs/DoctrineBehaviors) and [friendsofsymfony/user-bundle](https://github.com/FriendsOfSymfony/FOSUserBundle) should not be the rarest case.

**Comment by goetas** [comment]
Not planning to "add" some special "trait"  support since the traits are already working as they are.

When using traits there are some scenarios: 

- using annotations and traits are "yours": you can do everything you need/want since annotations from traits are already parsed.
- using annotations and traits are third-party: use YAML or XML for your metadata to expose/exclude/customize the serialization of the **class that uses the trait**
- using YAML or XML: congratulations, everything should work as expected.

When using YAML or XML mapping info for a trait should be placed on the class-metadata file that "uses" the trait.

Example:


```php
trait PhysicalAddress
{
    public $city;
}

class Address
{
    use PhysicalAddress;
    public $firstName;
    public $lastName;
}
```

Metadata for `Address` class have to be inside `Address.yml`
```yml
Address:
  properties:
    firstName:
      expose: true
    lastName:
      exclude: true
    city: ## this i the property coming from the trait
      exclude: true
