### ISSUE TITLE
Add a new AccessType to allow for __call()

### ISSUE THREAD

**Issue by michaelhagedon** [schmittjoh/JMSSerializerBundle#104]
I've created an entity that uses __get() and __set() for access while still keeping properties protected for Doctrine. I've also implemented __call() to allow for more traditional-looking getters and setters, but JMSSerializerBundle can only use reflection (which bypasses my __get() implementation) or _existing_ public methods. If there were another AccessType like "magic_call" it would be compatible with PHP's magic methods. For the moment I've overwritten the setAccessor() method on PropertyMetadata to avoid the checks for method existence, but that's obviously not right. 

If anyone's wondering why I still want my __get() call to fire when serialization occurs, I've created the ability to have an "optional" getter in case I need to modify the data on the way out, and I'd like JMSSerializerBundle to respect that. Something like this:

``` php
public function __get($property) {
  $getter = '_get' . ucfirst($property);
  if (method_exists($this, $getter)) {
    return $this->$getter();
  }
  if (property_exists($this, $property) && in_array($property, $this->accessible) ) {
    return $this->$property;
  }
}
```

**Comment by TKr** [comment]
I need it.

**Comment by exi** [comment]
Me too

**Comment by razvanmitre** [comment]
+1

**Comment by evgemar** [comment]
I need it. A have the same problem on several projects.
For example propel delegate behaviour http://propelorm.org/documentation/behaviors/delegate.html#delegating-using-a-many-to-one-relationship is really good thing but it's impossible to use it with jms serializer.

**Comment by vincentdieltiens** [comment]
It's also interresting with Doctrine Behaviors translatable where some methods are available using `__call` (https://github.com/KnpLabs/DoctrineBehaviors#proxy-translations)

```php
public function __call($method, $arguments)
{
    return $this->proxyCurrentLocaleTranslation($method, $arguments);
}
```

**Comment by evgemar** [comment]
This fix do serializer more simple and usable :) without reflection. You can use any name for fields but set getters and setters in config.
