### ISSUE TITLE
Serialization Groups Improvements

### ISSUE THREAD

**Issue by Seldaek** [schmittjoh/JMSSerializerBundle#107]
I think the current serialization groups are a bit weird because they don't work like the validator component, so first of all it's confusing because it's not familiar, and second I think the behavior of the validator makes more sense (that may be bias from the former though).

Example: I define group User and group Item and attach them like this:

``` php
Item {
    name // no group
    owner // group "Item"
}

User {
   name // no group
   items // group "User"
}
```
- When I serialize an item, I want to show its owner so I set the group to Item, but at the moment this returns _only_ the owner, kinda fail. So I add the group Default (like for the Validator), to get Default and Item, but that doesn't change anything. IMO all properties should have the group Default by default, or rather the exclusion policy should consider that they do are not excluded if the group default is enabled (we have a patch for that).
- If I serialize an item without specifying any group, it basically skips the group exclusion policy entirely. I think this is misleading, by default it should apply it with group Default and exclude what has another group but not the group Default.

If you agree I can work on a PR.

**Comment by mamartins** [comment]
was this removed? I think that @Seldaek is right about the implementation. Having to set the group to default in all the app so we can actually have groups working is not very good and can potentially lead to exposing unwanted properties -> security flaw
