### ISSUE TITLE
DateTime deserialization + Accessor(setter) bug?

### ISSUE THREAD

**Issue by iVariable** [schmittjoh/JMSSerializerBundle#115]
Setter accessor is used for DateTime values after $this->navigator->accept. If value not accepted, then setter isn't used at all because of an exception, thrown by DateTimeHandler(). Is this correct?

I think that's not a correct behaviour, because if I'm using custom setter, then I don't want any special validation to be performed by serializer. All needed validation i'll make by myself in setter.

For example, I want to set current date to property if an empty string passed from serialized object. But I'll fail, because my setter won't be called because of thrown exception. 

Example markdown for property.

 *
- @Serializer\Type("DateTime")
- @Serializer\Accessor(setter="setDateActiveFrom")
  *

PS: Sorry for my poor english :)

**Comment by martijn80** [comment]
@iVariable how did you manage do deactivate the date handler? I have no clue howto disable it via config, I tried this :
```yml
jms_serializer:
    handlers: 
        datetime: []
```            
But still an RuntimeException Invalid datetime "", expected format is thrown.
