### ISSUE TITLE
Default to @ExclusionPolicy("ALL") instead of "NONE"

### ISSUE THREAD

**Issue by beberlei** [schmittjoh/JMSSerializerBundle#159]
I use a base class from a library. It contains private properties i dont care about. JMS Serializer Annotation Driver should not read properties of these classes, and assume `@ExclusionPolicy("ALL")` instead of the current behavior of aggresively scanning.

I get an error "you must define a type for BaseClass::$property" at the moment.

**Comment by ruudk** [comment]
@schmittjoh I'm just trying out to create my own ExclusionStrategy but I'm stuck. The `@Exclude` `@Expose` `@ExclusionPolicy` annotations are not passed to the `ClassMetadata` and `PropertyMetadata`. Is there a special reason for not passing them? 

So what would be the best way to skip them then? Parse the annotations again? Or submit a PR to add the given annotations to `ClassMetadata` and `PropertyMetadata`?

https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Metadata/Driver/AnnotationDriver.php#L159:L162
