### ISSUE TITLE
VirtualProperties called after postSerialize triggers

### ISSUE THREAD

**Issue by scoolen** [schmittjoh/JMSSerializerBundle#216]
Hi,

It looks like a `@VirtualProperty` is handled after calls to `@PostSerialize`. Maybe this is intended behavior, but in my case it leads to unexpected results:

I rewrite a class' property to an array in PostSerialize and in a VirtualProperty method I depend on the property still being an instance of said class.

**Comment by goetas** [comment]
closing,
sorry for the incredibly long feedback loop. the issue seems to be solved long time ago. do not hesitate to re open a new issue if the problem persists
