### ISSUE TITLE
custom visitor

### ISSUE THREAD

**Issue by dbu** [schmittjoh/JMSSerializerBundle#218]
i created a custom visitor to get the raw array instead of a serialized json/xml. i manually inject datetime handler and arraycollection handler (after my comment on https://github.com/schmittjoh/JMSSerializerBundle/commit/b1fe04f7c9881e34c3a88576da58c3bd81148cc5 i realized what was going on)

but it still does not work, as in 1.0 SubscribingHandlerInterface::getSubscribingMethods also returns the list of supported formats. and i can't add to that list. what should i do? extend all handlers to change the returned array? feels a lot of work for not much benefit to me...

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/pull/435
