### ISSUE TITLE
XML serialization of URLs fail

### ISSUE THREAD

**Issue by phidah** [schmittjoh/JMSSerializerBundle#230]
I am trying to serialize the following array:

``` php
array('Test','http://google.com')
```

The result is:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <entry><![CDATA[Test]]></entry>
  <entry>
```

With other words, the result is abruptly ended once the URL is reached.

Can anyone explain this behavior and what I can do about it?

**Comment by goetas** [comment]
Sorry for the long feedback loop.
This issue is probably already solved.

(if not feel free to re open the issue or to comment here)

Thanks
