### ISSUE TITLE
Prevent Doctrine Entities from Serializing

### ISSUE THREAD

**Issue by colinmorelli** [schmittjoh/JMSSerializerBundle#263]
With the change of Doctrine proxy class initialization moved to an event, there's now no longer a way to prevent Doctrine proxy classes from being initialized (as far as I can tell).

My particular use case is this:

Entity A holds two many-to-one relationships with entity B. For the first instance of B on entity A, I need to load the related entity C. However, I don't want C to be loaded on the second instance of B attached to entity A.

Could we possibly add a priority to the EventDispatcher and a way to stop propagation? That would be a potential solution for this.

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/pull/684
