### ISSUE TITLE
Add support for wildcard serialization group

### ISSUE THREAD

**Issue by alex88** [schmittjoh/JMSSerializerBundle#269]
It would be nice to be able to set a serialization group to an entity field that matches all serialization groups.

I know you can also set Default in serialization groups but it matches all fields without any serialization groups set.

**Comment by zajca** [comment]
Bit old issue, but would be usefull.

Example: All documents inherits from base document which have some general fields like timestapms and id. Every time you want expose id. But if you using serialization group id is not exposed unless have all groups.

**Comment by alex88** [comment]
@zajca I'm not sure this library is still maintained, maybe you should check the symfony serialization library

**Comment by lukepass** [comment]
Hello, any news on this issue?
It could be useful to have wildcards in serialization groups.

Thanks.

**Comment by goetas** [comment]
what should be an "wildcard" serialization group? a serialization group that matches any group?

IMO serialization groups are powerful enough for now... if you need special exclusion/inclusion why not use the expression language feature? https://jmsyst.com/libs/serializer/master/reference/annotations#exclude
