### ISSUE TITLE
SerializeNull documentation

### ISSUE THREAD

**Issue by jeroenjoosen** [schmittjoh/JMSSerializerBundle#276]
Hey

Could someone tell me where you find the documentation about serializing null values with JMS? I'm searching but I did not yet found it.

Thanks

**Comment by theofidry** [comment]
I also met this problem, really annoying!

**Comment by jeroenjoosen** [comment]
You can enable it by using serialize_null: true in the config of FOSRest

**Comment by theofidry** [comment]
Hm Yeah sorry but I'm not using the FOSRestBundle, how do I do that?

**Comment by theofidry** [comment]
Answer [here](https://github.com/schmittjoh/JMSSerializerBundle/issues/440).
