### ISSUE TITLE
Fatal Error: Cannot redeclare class doctrine\orm\mapping\annotation in /vagrant/vendor/composer/ClassLoader.php line 183

### ISSUE THREAD

**Issue by mikehaas763** [schmittjoh/JMSSerializerBundle#286]
Hello.
This is the full exception I'm getting:
FatalErrorException: Error: include(): Cannot redeclare class doctrine\orm\mapping\annotation in /vagrant/vendor/composer/ClassLoader.php line 183

It works until I use the Paginator. I did see https://github.com/schmittjoh/JMSSerializerBundle/issues/123

Although it's not clear what the fix is in that issue I tried some of the things mentioned and still cannot fix this error.

Here is my stack trace: http://pastie.org/7365756

**Comment by sromano88** [comment]
I have made $iterator->getIterator()->getArrayCopy() and was serialized without problem.

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved. 
(if not feel free to re open the issue or to comment here)

Thanks
