### ISSUE TITLE
serialize_null configuration

### ISSUE THREAD

**Issue by AAtticus** [schmittjoh/JMSSerializerBundle#287]
To be able to work with Knockout.js I require the keys of empty values to be preserved.
I thought this was added to a previous version of JMSSerializerBundle / Serializer but in the current version I can't find anything to make sure it also serializes null values.

Any suggestions?

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved. 
(if not feel free to re open the issue or to comment here)

Thanks
