### ISSUE TITLE
Doctrine entity Symfony2

### ISSUE THREAD

**Issue by dtunes** [schmittjoh/JMSSerializerBundle#288]
Hi all,

I'm just unsure of how to use it with JsonResponse();

I'm trying the following,

``` php
$data = array(
'entities' => $entities,
);

$serializer = $this->get('jms_serializer');
$response = $serializer->serialize($data, 'json');

return new JsonResponse($data);
```

what I get is this

``` json
"{\u0022entities\u0022:[{\u0022id\u0022:1,\u0022first_name\u0022:\u0022Diego\u0022,\u0022middle_name\u0022:\u0022Fernando\u0022,\u0022last_name\u0022:\u0022Antunes\u0022,\u0022email\u0022:\u0022diegotdai@gmail.com\u0022,\u0022facebook\u0022:\u0022\u0022,\u0022twitter\u0022:\u0022\u0022,\u0022linkedin\u0022:\u0022\u0022,\u0022created\u0022:\u0022-0001-11-30T00:00:00+1130\u0022,\u0022last_loggedin\u0022:\u0022-0001-11-30T00:00:00+1130\u0022,\u0022last_modified\u0022:\u0022-0001-11-30T00:00:00+1130\u0022,\u0022revision\u0022:1}]}"
```

looks like the JsonResponse is not changing the content-type to application/json and returning text/html instead. Anyone got any tips?

If I just return $data it returns a json string with the right characters, but still the content type is text/html.

**Comment by theofidry** [comment]
I had a similar problem. It's really inconvenient that you have no way to tell to the `JsonResponse` that you're data is already in JSON. So the only way is to use the `Response` object dans set the headers to JSON:
```php
$response->headers->set('Content-Type', 'application/json');
```

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved and @theofidry solution works well. 
(if not feel free to re open the issue or to comment here)

Thanks
