### ISSUE TITLE
Output JSON and Specialchars 

### ISSUE THREAD

**Issue by priestor** [schmittjoh/JMSSerializerBundle#289]
Hello there! 

I recently posted a problem for the restbundle (https://github.com/FriendsOfSymfony/FOSRestBundle/issues/438).

Long story short I dont want my special chars to be "escaped" or anything else.

Like for example the string:
 {"wikipedia":"en.wikipedia.org/wiki/Mexico_City"}

would be in my situation:
 {"wikipedia":"en.wikipedia.org\/wiki\/Mexico_City"}

I know that this is perfectly valid, but the output should stay like the first string.
Can anyone help?

**Comment by trousers** [comment]
How do you do  this in the standalone version

**Comment by joe936** [comment]
I'd like to repeat the question above, how do I do this with the standalone version? The config thing is not doing anything...

**Comment by diegocavalletti** [comment]
@stof https://github.com/schmittjoh/JMSSerializerBundle/issues/289#issuecomment-16569632 What if this doesn't work? I setted it up in my config.yml but that doesn't seem to change the output which is still quote-escaped

**Comment by sstrgar** [comment]
> I setted it up in my config.yml but that doesn't seem to change the output which is still quote-escaped

I can confirm that. Same Here. Some more information about my setup:
- symfony/symfony v. 3.3.2
- jms/serializer-bundle v. 2.0.0

**Comment by goetas** [comment]
Can you share your configurations ?

**Comment by sstrgar** [comment]
Sure. It's the same as described before. Location: config.yml
```yml
jms_serializer:
    visitors:
        json:
            options: [JSON_UNESCAPED_SLASHES, JSON_UNESCAPED_UNICODE]
```

**Comment by goetas** [comment]
hmm, i tried and it works... are you sure is not an encoding issue? can you create a failing test case?

**Comment by buffcode** [comment]
Is there any possibility to set this on a per-use basis? I could not find a way to set this on the `SerializationContext`, as the setting gets mapped to a global parameter (`jms_serializer.json_serialization_visitor.options`) which is then injected into the 
`JsonSerializationVisitor`.

**Comment by webarchitect609** [comment]
@buffcode , @alexandr-lakeev , there is, but it's dirty one. Look: 

```php
/** @var Symfony\Component\DependencyInjection\Container $container */

$serializer = $container->get('jms_serializer');

/** @var Product $product An object for serialization */
$product = (new Product(123, "Nature's Table"))->setBrand('5" pack');

$jsonSerializationVisitor = $container->get('jms_serializer.json_serialization_visitor');

//Save options.
$oldOptions = $jsonSerializationVisitor->getOptions();

//Set options you want now.
$jsonSerializationVisitor->setOptions(JSON_HEX_APOS);

echo $serializer->serialize($product, 'json') . PHP_EOL;

//Restore old options.
$jsonSerializationVisitor->setOptions($oldOptions);

echo $serializer->serialize($product, 'json');
```

Output:
```
{"id":"123","name":"Nature\u0027s Table","brand":"5\" pack"}
{"id":"123","name":"Nature's Table","brand":"5\" pack"}
```
