### ISSUE TITLE
@Accessor not works in sf2.3

### ISSUE THREAD

**Issue by mrcmorales** [schmittjoh/JMSSerializerBundle#304]
Hi,

@Accessor annotation not works with sf2.3, I have this code:

use JMS\Serializer\Annotation\Accessor;

```
/**
 * @ORM\Column(type="integer")
 * @Groups({"list"})
 * @Accessor(getter="getIconName")
 */
protected $icon;

public function getIconName()
{
    $reflector = new \ReflectionClass('P4f\CoreBundle\Enum\MainMenuIconEnum');
    $namesArray=array_flip($reflector->getConstants());

    return $namesArray[$this->icon];

}
```

Thanks

Regards

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved. 
(if not feel free to re open the issue or to comment here)

Thanks
