### ISSUE TITLE
DoctrineObjectConstructor doesn't work with id as attribute

### ISSUE THREAD

**Issue by georgevanvliet** [schmittjoh/JMSSerializerBundle#305]
I'm using the DoctrineObjectConstructor to have my entities deserialized. 

When I receive the following xml:

```
<license id="12345">
<name>Foo</name>
</license>
```

The DoctrineObjectConstructor incorrectly uses the fallback constructor. In DoctrineObjectConstructor it states:

```
if (!is_array($data)) {            
            // Single identifier, load proxy
            return $objectManager->getReference($metadata->name, $data);
        }
```

When using xml, the if statement will always resolve to true (simplexml elements will always yield false to is_array).
So this codeblock boggles me. I would fix it for xml, but I'm unsure to the motivation behind it.
However, if I just comment it, my fuss is with the block further down:

```
foreach ($classMetadata->getIdentifierFieldNames() as $name) {

            if ( ! array_key_exists($name, $data)) {
                return $this->fallbackConstructor->construct($visitor, $metadata, $data, $type);
            }

            $identifierList[$name] = $data[$name];
        }
```

This does not take into account id fields that are set to be serialized as attribute.

My guess is that the DoctrineObjectConstructor was written with JSON in mind, but it would be nice if we can make it compliant with xml as well.

**Comment by goetas** [comment]
> Edit, got the fix, posted it on stackoverflow
