### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by minixxie** [schmittjoh/JMSSerializerBundle#306]
Hi Johannes,

I'm trying to integrate this bundle into my symfony2.2.*, to facilitate the JSON serialization.
All my objects are stored under MySQL and fetched with Doctrine2.

I got this error when I'm just doing a select on my "User" table with only one JOIN:

<pre>
Maximum execution time of 30 seconds exceeded
</pre>

If I fetched the user object and saved into the symfony2's session first, and serialize the object retrieved from the session, it has no problem. So I'm quite sure that this was caused by the LAZY LOADING that this bundle is using. From the dev log, I can see that there are not only ONE SQL statement, but there are MANY SQL statements fetching a bunch of tables. So I believe the LAZY LOADING is helping me fetch all related table that "User" table references.

I've been searching for this on stackoverflow and got this:
http://stackoverflow.com/questions/11851197/avoiding-recursion-with-doctrine-entities-and-jmsserializer

Seems that only the last answer is the most updated because I couldn't even find the class Serializer\Handler\DoctrineProxyHandler. But by following the last answer (which got 0 marks), the problem is not solved. I think the rewrite of the DoctrineProxySubscriber class is the correct direction but the line in "parameters.yml" is not being effective.

Can you give me some hints? It is perfect if you told me somewhere to switch off the LAZY LOADING. Thanks.

Simon

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved. 
(if not feel free to re open the issue or to comment here)

Thanks
