### ISSUE TITLE
get a error of JMSSerializerBundle in Symfony2.3.4 and ODM

### ISSUE THREAD

**Issue by lichnow** [schmittjoh/JMSSerializerBundle#320]
error is ServiceNotFoundException: The service "jms_serializer.metadata_driver" has a dependency on a non-existent service "doctrine".

my configure in composer.json:

"jms/serializer-bundle": "dev-master",
"jms/di-extra-bundle": "dev-master"

what's wrong?

**Comment by goetas** [comment]
cleaning up, probably not an issue anymore. sorry for late feedback loop
