### ISSUE TITLE
Unexpected extra requests when working with doctrine tree extension.

### ISSUE THREAD

**Issue by InformaticRevolution** [schmittjoh/JMSSerializerBundle#326]
Hi,

I have a category entity configured with the doctrine tree extension. I load the whole tree using the nested repository that is shipped with the bundle. 

When I try to serialize my categories, I get 102 extra requests. (actually one extra request per category in my tree).

Is this normal behavior ? And if so, how can I avoid this.

Thanks in advance

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved (and looks more a doctrine issue).

(if not feel free to re open the issue or to comment here)

Thanks

**Comment by karousn** [comment]
I'm in the same case
doing Expose decorator to the children of the class(entity) call again all what childrenQueryBuilder (of [NestedTreeRepository](https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/Tree/Entity/Repository/NestedTreeRepository.php)) got it before one by one.
I think that it need a custom handler for the return of childrenQueryBuilder format.

**Comment by karousn** [comment]
A view from symfony profiler
![image](https://user-images.githubusercontent.com/1721960/133760109-a490f57c-1303-4a22-b4b5-f2edad9f8267.png)
