### ISSUE TITLE
Composer error minimum-stability

### ISSUE THREAD

**Issue by mkakadiya47** [schmittjoh/JMSSerializerBundle#330]
i was tried to install or update composer but i got error..

Problem 1
- The requested package jms/serializer-bundle dev-master could not be found.

Potential causes:

```
A typo in the package name
The package is not available in a stable-enough version according to your minimum-stability setting see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
```

here my composer.json file

{
"name": "symfony/framework-standard-edition",
"description": "The \"Symfony Standard Edition\" distribution",
"autoload": {
"psr-0": { "": "src/" }
},
"require": {
"php": ">=5.3.3",
"symfony/symfony": "2.1._",
"doctrine/orm": ">=2.2.3,<2.4-dev",
"doctrine/doctrine-bundle": "1.0._",
"twig/extensions": "1.0._@dev",
"symfony/assetic-bundle": "2.1._",
"symfony/swiftmailer-bundle": "2.1._",
"symfony/monolog-bundle": "2.1._",
"sensio/distribution-bundle": "2.1._",
"sensio/framework-extra-bundle": "2.1._",
"sensio/generator-bundle": "2.1._",
"jms/security-extra-bundle": "1.2._",
"jms/di-extra-bundle": "1.1._",
"kriswallsmith/assetic": "1.1._@dev",
"doctrine/data-fixtures": "dev-master",
"doctrine/doctrine-fixtures-bundle": "dev-master",
"doctrine/migrations": "dev-master",
"doctrine/doctrine-migrations-bundle": "dev-master",
"knplabs/knp-menu-bundle": "1.1.*",
"sonata-project/exporter": "dev-master",
"sonata-project/jquery-bundle": "dev-master",
"sonata-project/block-bundle": "dev-master",
"sonata-project/admin-bundle": "dev-master",
"sonata-project/doctrine-orm-admin-bundle": "dev-master",
"sonata-project/intl-bundle": "dev-master",
"sonata-project/cache-bundle": "dev-master",
"friendsofsymfony/user-bundle": "dev-master",
"shtumi/useful-bundle": "dev-master",

```
"jms/serializer-bundle": "dev-master"
```

},
"scripts": {
    "post-install-cmd": [
        "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap",
        "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache",
        "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets",
        "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile"
    ],
    "post-update-cmd": [
        "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap",
        "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache",
        "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets",
        "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile"
    ]
},
"extra": {
    "symfony-app-dir": "app",
    "symfony-web-dir": "web"
},
 "minimum-stability": "dev",
  "prefer-stable": true

}

i was also tried to "jms/serializer-bundle": "0.13._@dev" OR "jms/serializer-bundle": "0.13._"

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved. 
(if not feel free to re open the issue or to comment here)

Thanks
