### ISSUE TITLE
Cannot redeclare class doctrine\orm\mapping\annotation

### ISSUE THREAD

**Issue by masterkaos** [schmittjoh/JMSSerializerBundle#339]
I am having this really weird issue, and I am not sure if it is an issue with JMSSerializerBundle or Symfony.

I used the built in FormErrorHandler class and it outputted fine. However, I wanted to change the format of the output, so decided to write my own.

So I went into my services and added the new class

```
    jms_serializer.form_error_handler:
        class: MyCompany\MyBundleBundle\Services\FormErrorHandler
```

When running with the new class (clearing cache and everything) I kept getting error
   Cannot redeclare class doctrine\orm\mapping\annotation

I tried debugging it but coulodn't figure out source of issue.

I then when into 
JMS\SerialzierBundle\Resources\config\services.xml  and replaced the form error handler class in that file with the new one, and then it worked fine with no exception

I had a custom FormErrorHandler in another project that worked fine using my above setup, but implementing it on this new project doesn't work. I may be  running a new version of JMSSerializerBundle than my other project.

I thought maybe an issue with overwriting the service but I completely removed parameter key  from the JMS config but still same issue.

As a temporary fix I will change the class in the JMS config, but don't like this option as if it gets upgraded then I will need to make the change again. Anyone have any ideas?

**Comment by goetas** [comment]
looks solved
