### ISSUE TITLE
Runtime Naming Strategy

### ISSUE THREAD

**Issue by mohdhallal** [schmittjoh/JMSSerializerBundle#347]
Hello,

we have an api which relies on the jms serializer to serve tabelized property names. We are implementing a newer version in which the serialized property names should be camelCased. Both representations must be maintained.
We tried to use Events subscribers (pre and post serialization) to intercept and modify the the data/flags but it seems not possible.
Any suggestions? Basically, it would be great if there is a way to force using camelCase when the Pre/Post events are triggered. I can only relate it to the NamingStrategy variable

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/859
