### ISSUE TITLE
Expected object but got array when serialize ArrayCollection of intermediate entity.

### ISSUE THREAD

**Issue by brpaz** [schmittjoh/JMSSerializerBundle#350]
I have a POPO PHP Class which an ArrayCollection property like this:

```
 /**
     * @Type("ArrayCollection<Ueb\Care\Bundle\TicketBundle\Entity\TicketNotifiedUser>")
     */
    protected $notifiedUsers;
```

The notifiedUsers is an intermidiate table between by Ticket and User entity.
But when i try to serialize the object, I got the following error:

```
Expected object but got array. Do you have the wrong @Type mapping or could this be a Doctrine many-to-many relation? 
```

If I remove the @Type annotation the serialization works just fine, but I cant deserialize it.
Is there any workaround?

Thank you.

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved. 
(if not feel free to re open the issue or to comment here)

Thanks
