### ISSUE TITLE
perform default deserialization in the custom handler

### ISSUE THREAD

**Issue by pleerock** [schmittjoh/JMSSerializerBundle#353]
I'm interested in this feature: http://stackoverflow.com/questions/20489479/jms-serializer-visitor-continue-default-deserialization . Sometimes you want to continue default serialization if some of conditions failed. or perform default serialization and then your custom over it. Any support?

**Comment by felixhayashi** [comment]
Bumped into this as well. I want to manipulate the data in the handler and then simply tell the serializer to continue as usual but with the updated data.
