### ISSUE TITLE
Documentation error for installation in AppKernel.php: 

### ISSUE THREAD

**Issue by linuxatico** [schmittjoh/JMSSerializerBundle#354]
In the documentation at http://jmsyst.com/bundles/JMSSerializerBundle#installation I found that my Symfony 2.3 installation needs in AppKernel.php

new JMS\SerializerBundle\JMSSerializerBundle($this)

instead of 

new JMS\SerializerBundle\JMSSerializerBundle()

because I get the following error:

ContextErrorException: Catchable Fatal Error: Argument 1 passed to JMS\SerializerBundle\JMSSerializerBundle::__construct() must implement interface Symfony\Component\HttpKernel\KernelInterface, none given

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved. 
(if not feel free to re open the issue or to comment here)

Thanks
