### ISSUE TITLE
[Feature request] Relations Serialization Strategy

### ISSUE THREAD

**Issue by loostro** [schmittjoh/JMSSerializerBundle#358]
Hi @schmittjoh,

first, thanks for all your bundles and work, without you the symfony world wouldn't be as friendly as it is :)

However great it is, the current JMSSerializerBundle seems to lack one very useful feature: customizable Relations Serialization Strategy.

Frontend apps like EmberJS (`ember-data`) expect relation fields to return only the ID (not the whole object) and collection fields to return an array of IDs in JSON response.

Right now, I have to add a special getter to my model, eg:

``` php
<?php
protected $parent; /* single entity relation */
protected $children; /* collection of related entities */

public function getParent() { 
    return $this->parent;  // retuns an object
}
public function getChildren() {
    return $this->children; // return an array collection
}

public function getParentID { 
    return $this->parent->getId(); // return id integer
}
public function getChildrenIDs {
    return $this->children->map(function($item){
        return $item->getId();
    });  // return array of id integers
}
```

And then I can add @VirtualProperty to include these in my serialization results.

However, these are redudant methods, unnecessarily fatteing the model, where their job could (and should!) be automatically handled.
### Relations Serialization Strategy

What I'm proposing, is to add a new Annotation `@SerializationStrategy` avaliable for CLASS and PROPERTY (defined on class, sets the default strategy for the class, defined on property, sets/overwrites the strategy only for that property) with possible options:
- `object` (default) -> serialize the object, just like it's doing right now

> Example output for **$parent**: `parent: { id: 0, name: 'foo' }`
> Example output for **$children**: `children: [ { id: 3, name: 'bar' }, { id: 4, name: 'baz' }]`
- `primary_key` -> return object's primary key instead of the object itself

> Example output for **$parent**: `parent: 0`
> Example output for **$children**: `children: [ 3, 4 ]`

Also, it would be nice if we could define a default strategy for the whole symfony2 application (so we don't have to add `@SerializationStrategy('primary_key')` on every class, if we wish that to be the default behaviour).

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved. 
The solution proposed here is too specific and solves an exact use case.
(if not feel free to re open the issue or to comment here)

Thanks
