### ISSUE TITLE
Include Entity Name in JSON

### ISSUE THREAD

**Issue by ch1986** [schmittjoh/JMSSerializerBundle#364]
Hello,
When I serialize an object of a class I get a JSON with this format:
{
  "field1": "value1",
  "field2": "value2",
  ...
  "fieldn": "valuen"
}
For example:
{
  "id": 1,
  "name": "name",
  "surname": "surname" 
}
And i want get the following:
{
  "entity_name":
  {
    "field1": "value1",
    "field2": "value2",
    ...
    "fieldn": "valuen"
  }
}
For example:
{
"user":
  {
    "id": 1,
    "name": "name",
    "surname": "surname" 
  }
}
Is there any way?
Thanks!

**Comment by gnilekaw** [comment]
+1

**Comment by goetas** [comment]
Sorry for the long feedback loop. The issue in this case can be solved using a custom handler.
The issue in this case is too specific to be included as core featrue of this library.

This issue is probably already solved. 

(if not feel free to re open the issue or to comment here)

Thanks
