### ISSUE TITLE
Error View::create

### ISSUE THREAD

**Issue by ch1986** [schmittjoh/JMSSerializerBundle#365]
Hello,
I have a problem when i try to return an array using the method View::create.
For example:
   $em = $this->getDoctrine()->getManager();
   $users = $em->getRepository('RestRestBundle:User')->findAll();
   return View::create($users, 200);

   Warning: json_encode(): recursion detected

Thanks.

**Comment by goetas** [comment]
closing,
sorry for the incredibly long feedback loop (almost 4 years). the issue seems to be solved long time ago. do not hesitate to re open a new issue if the problem persists
