### ISSUE TITLE
Question: How can i generate formated response for  JSON.

### ISSUE THREAD

**Issue by ajaypatelbardoli** [schmittjoh/JMSSerializerBundle#367]
Hi i need to prototype my all JSON response in following way.

```
{ 
     "status":"OK or FAILED",
     // incase of sucess
     "data":{
      }, 
     // in case of failed
     "error_code" : "respective error code",
     "error_messages" : " respeted error messages"
}
```

Thanks in advance :)

**Comment by theofidry** [comment]
I see to way of doing this:

First (not recommanded): create an object with the wished attributes and then serialise it.

Second (recommanded): use the headers and response status. If your response is correct, it's status is `200` which is equivalent to your `"status": "OK"`. For `"status": "FAILED"`, you can use the status `400`, and the the errors are in you response content. To set your response as a JSON one, you have to set the data as JSON and specify that your response is in JSON by setting the headers `Content-Type` as `application/json`.

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved and @theofidry solution looks a good option. 

(if not feel free to re open the issue or to comment here)

Thanks
