### ISSUE TITLE
ServiceNotFoundException: You have requested a non-existent service \"serializer\"

### ISSUE THREAD

**Issue by jesmarquez** [schmittjoh/JMSSerializerBundle#368]
Because I'm getting the following error: 

ServiceNotFoundException: "You have requested a non-existent service "serializer"." at C:\wamp\www\symensay\app\bootstrap.php.cache line 1967 {"exception":"[object](Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "serializer". at C:\wamp\www\symensay\app\bootstrap.php.cache:1967)

Install the component as indicated in the documentation!

in the controller i have:
...
use JMS\SerializerBundle\Serializer\Serializer;
...

$usuarios = $query->getResult();
$serializer = $this->container->get('serializer');
$entityserializer= $serializer->serialize($usuarios, 'json');

Thank!

**Comment by theofidry** [comment]
Depending of the context, you can try `$this->get('serializer')`instead of `$this->container->get('serializer')`.

If you're in a service, you have to **inject** the service `serializer`, cf. [this link](http://symfony.com/doc/current/components/dependency_injection/types.html).

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved and @theofidry solution looks  good.

(if not feel free to re open the issue or to comment here)

Thanks
