### ISSUE TITLE
Reflection Exception after upgrade from 0.14.0 to 0.15.0

### ISSUE THREAD

**Issue by sdoerig** [schmittjoh/JMSSerializerBundle#369]
Hello 
After upgrading from 0.14.0 to 0.15.0 I'm getting the error below:

request.CRITICAL: Uncaught PHP Exception ReflectionException: "Class Cyberlink\StatusBundle\Entity\Company does not exist" at /var/www/oss/vendor/jms/metadata/src/Metadata/MetadataFactory.php line 164 {"exception":"[object](ReflectionException: Class Cyberlink\StatusBundle\Entity\Company does not exist at /var/www/oss/vendor/jms/metadata/src/Metadata/MetadataFactory.php:164)"} []

Same code works fine with version 0.14.0.
On the machine reproducing this the packages below are installed:
ii  libapache2-mod-php5                       5.5.3+dfsg-1ubuntu2.1                         amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  pear-phpunit-channel                      1.1-1                                         all          PEAR pear.phpunit.de channel definition file
ii  php-apc                                   4.0.1-4                                       all          APC User Cache for PHP 5 (transitional package)
ii  php-codecoverage                          1.1.2+dfsg1-3                                 all          provides collection, processing and rendering for PHP code coverage information
ii  php-file-iterator                         1.3.1-2                                       all          FilterIterator implementation for PHP
ii  php-invoker                               1.1.0-1                                       all          utility class for invoking callables with a timeout
ii  php-pear                                  5.5.3+dfsg-1ubuntu2.1                         all          PEAR - PHP Extension and Application Repository
ii  php-symfony-yaml                          1.0.6-1                                       all          Symfony YAML: A PHP library that speaks YAML
ii  php-text-template                         1.1.1-2                                       all          Simple php template engine
ii  php-timer                                 1.0.2-2                                       all          PHP Utility class for timing
ii  php-token-stream                          1.1.3-2                                       all          Wrapper around PHP's tokenizer extension
ii  php5                                      5.5.3+dfsg-1ubuntu2.1                         all          server-side, HTML-embedded scripting language (metapackage)
ii  php5-apcu                                 4.0.1-4                                       amd64        APC User Cache for PHP 5
ii  php5-cli                                  5.5.3+dfsg-1ubuntu2.1                         amd64        command-line interpreter for the php5 scripting language
ii  php5-common                               5.5.3+dfsg-1ubuntu2.1                         amd64        Common files for packages built from the php5 source
ii  php5-curl                                 5.5.3+dfsg-1ubuntu2.1                         amd64        CURL module for php5
ii  php5-dev                                  5.5.3+dfsg-1ubuntu2.1                         amd64        Files for PHP5 module development
ii  php5-gd                                   5.5.3+dfsg-1ubuntu2.1                         amd64        GD module for php5
ii  php5-intl                                 5.5.3+dfsg-1ubuntu2.1                         amd64        internationalisation module for php5
ii  php5-json                                 1.3.1+dfsg-2                                  amd64        JSON module for php5
ii  php5-mongo                                1.4.1-1ubuntu1                                amd64        MongoDB database driver
ii  php5-mysql                                5.5.3+dfsg-1ubuntu2.1                         amd64        MySQL module for php5
ii  php5-readline                             5.5.3+dfsg-1ubuntu2.1                         amd64        Readline module for php5
ii  php5-sybase                               5.5.3+dfsg-1ubuntu2.1                         amd64        Sybase / MS SQL Server module for php5
ii  php5-xdebug                               2.2.3-1build1                                 amd64        Xdebug Module for PHP 5
ii  phpunit                                   3.6.10-1                                      all          Unit testing suite for PHP5
ii  phpunit-mock-object                       1.1.1-2                                       all          Mock Object library for PHPUnit
ii  phpunit-story                             1.0.0-3                                       all          extension to facilitate Behaviour-Driven Development

Symfony Version:
2.3.10

**Comment by houximing** [comment]
I actually have this issue when I downgrade from 1.0 to 0.14.0 which have not sorted out yet

**Comment by goetas** [comment]
Sorry for the long feedback loop. 
This issue is probably already solved. 

(if not feel free to re open the issue or to comment here)

Thanks
