### ISSUE TITLE
serializing a json array using {} instead of []

### ISSUE THREAD

**Issue by javiern** [schmittjoh/JMSSerializerBundle#373]
HI, im using version 1.3, if i call serialize() with something like
array(
   $obj
)

y get this

{"0": { ***_the object serialization**_*}}

but i spect something like this

[{ ***_the object serialization**_*}]

i manage to get it working by commeting this lines on JsonSerializationVisitor class:

```
public function endVisitingObject(ClassMetadata $metadata, $data, array $type, Context $context)
    {
        $rs = parent::endVisitingObject($metadata, $data, $type, $context);
        // Force JSON output to "{}" instead of "[]" if it contains either no properties or all properties are null.
        // if (empty($rs)) {
        //    $rs = new \ArrayObject();
        //
        //    if (array() === $this->getRoot()) {
        //        $this->setRoot(clone $rs);
        //    }
        //}

        return $rs;
    }

```

**Comment by ggregoire** [comment]
Same issue here, but I noticed that:

When I return a response from a `@ParamConverter` conversion, I get:

 `[ {}, {}, {} ]`

When I return a response from a `$this->getDoctrine()->getRepository(...)->find(...)`, I get:

`{ 3: {}, 4: {}, 5: {} }`

**Comment by theofidry** [comment]
+1

**Comment by bassrock** [comment]
+1 for a fix! Seeing the same inconsistent behavior too

**Comment by bassrock** [comment]
I am seeing this issue on a OneToMany situation explained here: https://github.com/schmittjoh/serializer/issues/387

Even when I try to create a virtualized solution like @ggregoire I still get an object response.

**Comment by dotstormz** [comment]
+1

**Comment by ch3ric** [comment]
+1

**Comment by joshribakoff** [comment]
Same issue here. its converting {} to [], which messes up Angular $watch

**Comment by pasxel** [comment]
+1

**Comment by coatezy** [comment]
I'm experiencing this issue when the context is removed from the array within GenericSerializationVisitor::visitArray and where the context's key is 0. 

I have solved this by extending JsonSerializationVisitor, overriding the visitArray function and then rebuilding array's indexes returned by the parent with array_values. 

I then replaced the 'jms_serializer.json_serialization_visitor.class' parameter with my class.

Of course this a JMSSerializer issue rather than the bundle but I thought I'd post my findings here just in case it saves somebody else an hour of head banging.

**Comment by Soullivaneuh** [comment]
:+1: 

The most strange, I have different results:

If I get array of object from a find on doctrine:
```php
$incidents = $this->getDoctrine()->getRepository('AppBundle:Incident')->findAll();
```

This returns a proper json result.

But If y create an `ArrayCollection` object:
```php
/** @var Object[] $objects */
$objects = [];
foreach ($state as $objectName => $objectInfo) {
    $object = new Object();
    $object->setName($objectName);
    array_push($objects, $object);
}

return new ArrayCollection($objects);
```

Then I get an ugly associative array.

Using thoses vendor packages:
```sh
$ composer info -i | grep jms
jms/aop-bundle                           1.0.1               Adds AOP capabilities to Symfony2
jms/cg                                   1.0.0               Toolset for generating PHP code
jms/di-extra-bundle                      1.4.0               Allows to configure dependency injection using annotations
jms/metadata                             1.5.1               Class/method/property metadata management in PHP
jms/parser-lib                           1.0.0               A library for easily creating recursive-descent parsers.
jms/security-extra-bundle                1.5.1               Enhances the Symfony2 Security Component by adding several new features
jms/serializer                           0.16.0              Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                    0.12.0              Allows you to easily serialize, and deserialize data of any complexity
```

**Comment by Soullivaneuh** [comment]
Same issue using dev-master:
```
jms/serializer                           dev-master e619ca4  Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                    dev-master 8bce2e8  Allows you to easily serialize, and deserialize data of any complexity
```

**Comment by Soullivaneuh** [comment]
@coatezy I'm trying to apply your solution.

Can you paste your new Visitor class and your fos_rest configuration file please?

Thanks.

**Comment by Soullivaneuh** [comment]
Another clue, for the ArrayCollection, I'm using  filter like this

```php
        return $objects->filter(function (Object $object) {
            return $object->condition() === true;
        });
```

So my array has missing numeric keys. By adding an array_values, this is fixed.

**Comment by stof** [comment]
@Soullivaneuh if your array is not indexed with a sequence from ``0`` to ``count($array) - 1``, getting an JS object rather than an array is the expected behavior, because this is how associative arrays need to be converted to JSON. And if keys are not such sequence, your array is a map, not a list.

**Comment by Soullivaneuh** [comment]
Yeah, I learned that on my depend. ;)

Thanks.

Sullivan SENECHAL

**Comment by stormsson** [comment]
i tried commenting the JsonSerializationVisitor class, using array_values, but nothing worked , also the array of objects i'm trying to serialize it has keys from  0 -> count(array) -1 .

Is there some other workaround for this? :(

**Comment by joshribakoff** [comment]
No. Unfortunately these bundles in the "Symfony ecosystem" are using arrays because Symfony forces it to be so. Its request bag only holds arrays. Its forms are made to work with arrays, etc. Even if you fix JMS Serializer, you can POST your data and get an empty object in your `$request` because what am I saying is this problem occurs in almost every PHP script built around the Symfony framework.

As it turns out, plain PHP can handle it just fine, so thats your workaround:

```
$str = "{foo:[], bar:{}}";
var_dump(json_encode(json_decode($str)) === $str); // true
```

As you can see, it would be unfair to blame PHP. Blame the "PHP Style" (Symfony style). It introduces the concept of casting objects to arrays, doing some processing, then converting back to objects. Presumably this is so the programmer can type `foo['bar']` instead of `foo->bar`. I say its just laziness/ignorance of data types... but now its a part of the standard (Symfony core). You can see the mess its created. Its forced JMS Serializer to work the way it does, and if they change it they loose Symfony support so thats a no go.

**Comment by theofidry** [comment]
Ok thanks for your explanation @joshribakoff

**Comment by erichfosse** [comment]
@joshribakoff I believe this is not the same issue. What you are ranting about in https://github.com/FriendsOfSymfony/FOSRestBundle/issues/980 is the invalid handling of empty objects.

I do believe this issue is about the serialization of actual data, and more specifically, the fact that arrays or array collections of data sometimes are serialized into objects of data with integer property names.

**Comment by joshribakoff** [comment]
@erichfosse  oops you're right. I still contend that  its somewhat related. The PHP community has a coding standards problem. Having "Array" objects is just confounding the issue(s), which manifests itself as an issue where programmers get a different data type than expected.

**Comment by stormsson** [comment]
I have some news, but maybe someone could help me understanding what's happening.

Some background info:
* i am trying to serialize objects that contains an array of objects.
* In the model, i defined a virtual property that returns an array of objects with the keys that go from 0 -> count() -1
* in the final json , the result is the "wrong" array as stated in this whole thread.

I started throwing exceptions everywhere to understand what's going on under the hood and i finally noticed that something odd is happening in the visitArray function.
Therefore:
1) i copied the JsonSerializationVisitor so i had MY serialization visitor object
2) the function visitArray starts with:
```php
$result = parent::visitArray($data, $type, $context);
```
and this $result is an array with the keys starting from **ONE**
is this a bug or a wanted behavior?

**Comment by wtw** [comment]
For me it was using Doctrine's [`getArrayResult()` instead of `getResult()`](http://doctrine-orm.readthedocs.org/en/latest/reference/dql-doctrine-query-language.html#query-result-formats). Did not look into possible root causes.

**Comment by nschurmann** [comment]
Is this fixed?, i have this same problem and we have to "workaround" it with an angular.forEach... very frustrating.

**Comment by noyg** [comment]
Any solution \ workaround for this?

**Comment by paztek** [comment]
For me it happens when I have a OneToMany relationship (e.g Category > Products) and I remove the first element (a Product) from the ArrayCollection.
The initial ArrayCollection:

```
    0 => product0
    1 => product1
    2 => ...
    ...
```
is serialized correctly while the resulting ArrayCollection:

```
    1 => product1
    2 => ...
    ...
```
is incorrectly serialized as an object.

I fixed it by completing the ```removeProduct```method of the Category class like that:

```
    public function removeProduct(Product $product)
    {
        $this->products->removeElement($product);

        // Fix the keys of the ArrayCollection
        $this->products = new ArrayCollection($this->products->getValues());
    }
```

This certainly isn't optimal but it helped me overcome this issue.

**Comment by theofidry** [comment]
otherwise there is the new serializer of Symfony2.7!

**Comment by paztek** [comment]
I oversight this new feature. I'll definitely give it a try.

**Comment by paztek** [comment]
The problem with my fix is if there are objects holding references to the old ArrayCollection.

Here is a lesser optimal solution which preserves the reference to the collection:

```
public function removeProduct(Product $product)
    {
        $this->products->removeElement($product);

        // Fix the keys of the ArrayCollection
        $elements = $this->products->getValues();
        $this->products->clear();
        foreach ($elements as $element) {
            $this->products->add($element);
        }
    }
```

This isn't very DRY if you have a lot of these XXXToMany relationships but it works.

**Comment by andrej-vasilj** [comment]
I started having this issue seemingly for no reason. Upon further inspection, I noticed that I had a null element inside my array. When I removed it, it worked as expected and used [] instead of {}. I believe I'm running version 1.3 of the serializer.

**Comment by ARoddis** [comment]
Seems like a bug to me.

```php
public function endVisitingObject(ClassMetadata $metadata, $data, array $type, Context $context)
    {
        $rs = parent::endVisitingObject($metadata, $data, $type, $context);

        // Force JSON output to "{}" instead of "[]" if it contains either no properties or all properties are null.
        if (empty($rs)) {
            $rs = new \ArrayObject();

            if (array() === $this->getRoot()) {
                $this->setRoot(clone $rs);
            }
        }

        return $rs;
    }
```

If this happens, than due to this:

```php
/**
     * @param array $data
     * @param array $type
     */
    public function visitArray($data, array $type, Context $context)
    {
        if (null === $this->root) {
            $this->root = array();
            $rs = &$this->root; <------REFERENCE
        } else {
            $rs = array();
        }

        foreach ($data as $k => $v) {
            $v = $this->navigator->accept($v, $this->getElementType($type), $context);

            if (null === $v && (!is_string($k) || !$context->shouldSerializeNull())) {
                continue;
            }

            $rs[$k] = $v;
        }

        return $rs;
    }
```

The first mentioned method sets the root to ArrayObject.

And an ArrayObject serializes to {0:bla} and not [bla].

**Comment by ARoddis** [comment]
Easy fix for now:

```php
namespace YourOwnNamespace;

class JsonSerializationVisitor extends \JMS\Serializer\JsonSerializationVisitor{
    public function getResult()
    {
        //EXPLICITLY CAST TO ARRAY
        $result = @json_encode((array) $this->getRoot(), $this->getOptions());

        switch (json_last_error()) {
            case JSON_ERROR_NONE:
                return $result;

            case JSON_ERROR_UTF8:
                throw new \RuntimeException('Your data could not be encoded because it contains invalid UTF8 characters.');

            default:
                throw new \RuntimeException(sprintf('An error occurred while encoding your data (error code %d).', json_last_error()));
        }
    }
} 
```

and than in you config:

```yml
parameters:
  jms_serializer.json_serialization_visitor.class: YouOwnNamespace\JsonSerializationVisitor
```

**Comment by tesenwein** [comment]
In my case this error occurred only when using @GROUPS and only if one property contained a entity with no matching @GROUPS attributes.

Maybe this helps you....

**Comment by AlmogBaku** [comment]
I'm facing the same issue when I use `serializerGroups` in the `@View` annot.
Is there any solution by far?

**Comment by AlmogBaku** [comment]
Based on @ARoddis solution:
```
use \JMS\Serializer\JsonSerializationVisitor as JsonSerializationVisitorBase;

class JsonSerializationVisitor extends JsonSerializationVisitorBase
{
    public function getResult()
    {
        if($this->getRoot() instanceof \ArrayObject) {
            $this->setRoot((array) $this->getRoot());
        }
        return parent::getResult();
    }
}
```

**Comment by ARoddis** [comment]
Looks good.

**Comment by ggnet** [comment]
Annotation in controller helped me: `@View(serializerGroups={"Default"})`

**Comment by AlmogBaku** [comment]
Using the group annotation in my case actually *caused* it :|

--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by jeremygachet** [comment]
+1 for ggregoire's solution. simple and quick fix.

The problem is also cause by the  group annotation in my case, when I have only 1 object in the collection (with 2 or more, I receive an array)

**Comment by cfoehrdes** [comment]
+1 we have the same issue when using the JMS serializer with serialization groups. The serialization group causes the array to be serialized as object with index and removing the group results in a json array

**Comment by cfoehrdes** [comment]
We expected the same issue when serializing with serialization groups, what really caused the array to be serialized as object with key property instead of json array was that it contained a subelement which exposed no property for the used list.

**Comment by jeremygachet** [comment]
I had the same issue as cfoehrdes. 
An inconsistent rendering, sometimes it's an array sometimes it's an object. 
I also have an object with a numeric key when the serializer returned only 1 data.

**Comment by alafon** [comment]
confirmed @cfoehrdes & @jeremygachet : this only occurs when using `@Groups` where subelements are entities and have nothing to expose with the specified group(s)

**Comment by alafon** [comment]
Note : when using FOSRestBundle, this little trick (usage of `setSerializeNull(true)`) might help : 

```
        $context = new SerializationContext();
        $context->setSerializeNull(true);
        $view = View::create($objects,200);
        $view->setSerializationContext($context);
        return $this->handleView($view);
```

**Comment by TomiS** [comment]
The workaround provided by @AlmogBaku based on @ARoddis code worked for me for the case in hand. Thanks for that! I hope there will be no unwanted side-effects in other serialization cases. Is there a reason that could not be a patch for this bug?

**Comment by smartpierre** [comment]
Same problem : when a subelement does not have any exposed property (or the property is null), it will fuck the output. I lost 3 hours on that, I'm quite happy that I managed to find this thread, but please fix this, do something.

**Comment by avegao** [comment]
+1

It reproduces when I add two groups or more to an entity

**Comment by smartpierre** [comment]
Can we have any news on this ? Every once in a while, routes are returning objects instead of arrays, it's so random and dependant of the data, that it would take me a week to go through each route of my API and do tests. The mobile developers I work for are upset and I look like an idiot because the serialization is random. Can we have an official response if this issue will be handled or not ?
Please, react.
@schmittjoh

**Comment by tim-massey** [comment]
:+1:

**Comment by AngryDeveloper** [comment]
@ttibensky PR fixed it for our use case, any news about a potential merge @schmittjoh  ?

**Comment by ttibensky** [comment]
@AngryDeveloper unfortunately no. I also sent them an email asking if they could merge it, but got no response. So I forked the bundle, applied the patch on a fork and used the fork instead official bundle. I believe you can do the same thing.

check this for more information about how to override official bundle with a fork using compose https://getcomposer.org/doc/05-repositories.md#vcs

**Comment by Bluestart83** [comment]
I have the same problem too, coming only when updating the object serialized.

Thanks  @ggregoire for your solution

**Comment by Ovski4** [comment]
Hi,
Just passing by to share my experience on the same issue.
I got the same issue on a collection (got an object instead of an array). I had 3 collections, only one was affected by this issue after some changes but I didn't understood why, there was no obvious reason(s).
Strangely, right after i persisted a new object in database for this collection, the bug disappeared and I got an array. (For anyone wondering, I cleared the symfony cache as well as my browser cache many times before - without success)

**Comment by Ovski4** [comment]
For anyone affected by this issue, I solved it by simply adding a max_depth property.

```yml
Dynergie\Bundle\PatentBundle\Entity\ApplicationZone:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        countryCode:
            expose: true
        patents:
            expose: true
            max_depth: 4
```

I can finally retrieve applicationZones in an json array instead of a json object.

ApplicationZone got a OneToMany relation with Patent. Patent is an entity related to itself with a OneToMany a well. So as stated above by stormsson, there is indeed a recursion issue.

It's strange as the issue remains with a max_depth equal to 0, 1, 5 and more, but i got a json array when max_depth equal 2, 3 and 4.

**Comment by rdarricau** [comment]
+1 and Thx @AlmogBaku for your patch, it works well :) -> https://github.com/schmittjoh/JMSSerializerBundle/issues/373#issuecomment-115238225

**Comment by mickadoo** [comment]
The root of the problem seems to be how json_encode works. 
```
$c = new stdClass();
$c->foo = 'bar';

$arrayOne = [
    0 => $c,
    1 => $c
];

$arrayTwo = [
    0 => $c,
    3 => $c
];

echo json_encode($arrayOne) . PHP_EOL;
echo json_encode($arrayTwo);
```

Will print 
```
[{"foo":"bar"},{"foo":"bar"}]
{"0":{"foo":"bar"},"3":{"foo":"bar"}}
``` 

because the keys in `$arrayTwo` are not sequential. I found this since I was using the `filter()` method. In my example I had an `ArrayCollection` with two entries. In cases where the `0` key element was returned from the filter it was fine. However if the `0` element was excluded based on the filter then I had an array where the first key was `1` -> this led to being serialized as an object.

Maybe the reason @schmittjoh isn't responding is because it's quite hard to fix. You could fix it on the doctrine side, inside `Doctrine\Common\Collections\ArrayCollection` changing the `filter` method to 

```
return new static(array_values(array_filter($this->elements, $p)));
```

It could also be changed inside the `serializeCollection` method of the `ArrayCollectionHandler`, returning 

`return $visitor->visitArray($collection->getValues(), $type, $context);` 

But in either case I have doubts if this is a real solution, obviously in my case I don't care about the array keys since they're nothing more than the order of the entities in the database. But if I have an `ArrayCollection` where the keys are actually important then I'd be frustrated if they were reset.

**Comment by rodnaph** [comment]
I ran into this issue when I changed a sub-entity (ie. a relation to one of the entities in the array i was serializing) to use exclusion strategy all without remembering to expose any fields, so it became blank, and caused this problem. thanks @lwojciechowski

**Comment by maxolasersquad** [comment]
I ran into this when implementing serialization on an entity that extends \Serializable. Because it implements its own serialization method, the JMS serializer was apparently not being invoked, which in turn meant the max_depth property was not being recognized. The entity has children, which in turn had properties back to their parents that was attempting to be serialized, which I think caused this issue.

Putting in the work-around provided by @alafon did the trick with the only drawback being that the depth causes a very hefty result-set to be returned.

**Comment by belackriv** [comment]
For the case where the null value is happening due to self-referencing (ie serializing an item that has a group that contains an ArrayCollection of items) I used this:
```php
<?php

namespace AppBundle\Serializer\Handler;

use JMS\Serializer\VisitorInterface;
use Doctrine\Common\Collections\Collection;
use JMS\Serializer\Context;

class ArrayCollectionHandler extends \JMS\Serializer\Handler\ArrayCollectionHandler
{
    public function serializeCollection(VisitorInterface $visitor, Collection $collection, array $type, Context $context)
    {
        // We change the base type, and pass through possible parameters.
        $type['name'] = 'array';
        //don't include items that will produce null elements
        $dataArray = [];
        foreach($collection->toArray() as $element){
        	if(!$context->isVisiting($element)){
        		$dataArray[] = $element;
        	}
        }

        return $visitor->visitArray($dataArray, $type, $context);
    }
}
```
and setting:
```yml
parameters:
    jms_serializer.array_collection_handler.class: AppBundle\Serializer\Handler\ArrayCollectionHandler
```

**Comment by CedricMaillot** [comment]
@mickadoo You're right ! with array_values for remapping the indexes 

```php
$serializer->serialize(array_values($toSerialize), 'json'));
```

it gives back a proper json array.

**Comment by rud-felix** [comment]
I have the same problem
```"[{\"id\":50,\"text\":\"some text\"}, ... ]"```

I resolved this problem like this

``` php
$result = [];
$serializer = $this->get('jms_serializer');

foreach ($user->getMessages() as $message) {
       /** @var UserMessages $dto **/
       $dto = $shifter->toDto($message, new UserMessages());
       $result[] = (array) json_decode($serializer->serialize($dto, $format = 'json')); // I use serializer map for exclude some fields
}

return $this->view(["data" => $result], Codes::HTTP_OK);
```

result: 
```{"data": [{"id": 50, "text": "some text"}, {"id": 50, "text": "some text"}, ... ]}```

**Comment by chalasr** [comment]
@rud-felix felix perfect alternative, thanks. 
`json_decode($serializer->serialize($user, 'json', SerializationContext::create()->setGroups(array('api'))))`

**Comment by vurcease** [comment]
Throwing my experience into the ring for new-comers - @AlmogBaku 's solution worked immediately and like a charm. I tried other things, like making sure annotations existed for sub-items, rebuilding the Doctrine collection as a simple array, etc. to no avail. 

Thanks, everyone, for the time spent providing suggestions and discussions. It's greatly appreciated.

**Comment by frodosghost** [comment]
For me it may have been a case of over configuration. I had both `MaxDepth` and `Groups` defined, but were not using them with the `SerializationContext`.

For this to work, I *did not* serialize the JMS defined object before passing it to the View. I configured the `SerializationContext` to use both _Groups_ and _MaxDepthChecks_, and then created the View and passed Context into that.

```
use JMS\Serializer\SerializationContext;
use FOS\RestBundle\Util\Codes;
use FOS\RestBundle\View\View;

...

$context = SerializationContext::create();
$context->setGroups(array('track'));
$context->enableMaxDepthChecks();

$view = View::create($track, Codes::HTTP_CREATED);
$view->setSerializationContext($context);

return $this->handleView($view);
```
Worked for me. Work for anyone else?

**Comment by erikbaan** [comment]
ran into the same issue today. little bit surprised to see that an issue reported early 2014 is still not fixed today.

**Comment by tom10271** [comment]
I think the serializer will check to see if the array is a numeric array or not and decide serializing it to JS `Array` or `Object`.


If there is a cell inside a array is `null`, it will first skip that cell, skipping it makes indexes discontinue and serializer will recognize it as associative array.


```
array:28 [
  0 => "High Fashion"
  1 => "Contemporary"
  2 => "Streetwear"
  3 => null
  4 => "Grooming"
]
```

Since `$arr[3]

**Comment by yannchoquet** [comment]
You can add this lines in your config.yml :

```
jms_serializer:
    visitors:
        json:
            options: [JSON_FORCE_OBJECT]
```

**Comment by mickadoo** [comment]
@yannchoquet I think the original problem was that the serializer was returning an object when an array was expected.

**Comment by peterpro** [comment]
I've slightly modified @AlmogBaku 's solution, cause it wasn't working for me.
My situation:
I have player (P1), who have a team (T), which have array of players. And P1 obviously didn't exist in T players, to avoid self-reference. But it caused array to hash transformation :(

Here is solution:  

```
<?php

/**
 * @author  Almog Baku
 *          almog.baku@gmail.com
 *          http://www.AlmogBaku.com
 *
 * 25/06/15 15:28
 *
 * @author Peter Prokunin
 * mailto:peterprokunin@yandex.ru
 * 20.07.16
 */

namespace CommonWPBundle\Serializer;

use JMS\Serializer\Context;
use \JMS\Serializer\JsonSerializationVisitor as JsonSerializationVisitorBase;

class JsonSerializationVisitor extends JsonSerializationVisitorBase
{
// Almog's code
    public function getResult()
    {
        if($this->getRoot() instanceof \ArrayObject) {
            $this->setRoot((array) $this->getRoot());
        }
        return parent::getResult();
    }
// Peter's code
    public function visitArray($data, array $type, Context $context)
    {
        $array = parent::visitArray($data, $type, $context);
        $keys = array_keys($array);
        foreach ($keys as $key){
            if(!is_numeric($key)){
                return $array;
            }
        }
        return array_values($array);
    }

}

```

**Comment by vurcease** [comment]
Thanks, @peterpro - I had implemented the previous solution from @AlmogBaku and it was working fine until I ran into one particular data set I needed serialized and it started coming back as named hash. I applied your visitArray method and it's looking good again. Thank you.

**Comment by Enase** [comment]
the same troubles.. is someone going to solve it? any PR or branch where we can help?

**Comment by tom10271** [comment]
@Enase I don't think anything need to fix when you understand while it serialize your array to JS object, read some of the comments here to know more, or may be mine. 

https://github.com/schmittjoh/JMSSerializerBundle/issues/373#issuecomment-218934026

**Comment by heilgar** [comment]
```
preSerialize(){
    $this->setSmth(array_values($this->getSmth()));
}
```

**Comment by little-boy** [comment]
Same problem, spent 1 hour on it.

Same here, I use @Groups, @Expose. With ManyToMany and ManyToOne.

I solved it by specifying @Expose and @Groups on at least one property of all entities concerned. Don't know where was actually the problem.

**Comment by emericspiroux** [comment]
Same problem but i found a fix !!! :)
Your put : `use ApiBundle\Entity\EntitiesName;`
i've got `{{"0": <object entities serialized>[...]}}`

But when i put `use ApiBundle\Entity\EntitiesName as EntitiesName;` 
i've got `[{<object entities serialized>}]`

hope this fix can help someone !

**Comment by emericspiroux** [comment]
+1 !!!!!

**Comment by jbenezech** [comment]
Same here when specifying a serialization group

**Comment by jedi4z** [comment]
I has the same problem, I fix it with that:

$serializer->serialize(['data' => $data], 'json');

so, i get:

`
{
  "data": [
    {
      "id": 1,
      "name": "Parent"
    },
   {
      "id": 2,
      "name": "Parent 2"
    }
  ]
}
`

**Comment by jedi4z** [comment]
I fix it with @MaxDepth() and @type annotations ([look at this](http://jmsyst.com/libs/serializer/master/reference/annotations)) you need to be careful with the array collections fields and prevent the huge nested.

```php
<?php

namespace Amoblando\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as JMS;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Category
 *
 * @JMS\ExclusionPolicy("all")
 * @ORM\Table(name="category")
 * @ORM\Entity(repositoryClass="Amoblando\AdminBundle\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @JMS\Type("integer")
     * @JMS\Expose()
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank()
     *
     * @JMS\Type("string")
     * @JMS\Expose()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     *
     * @JMS\Type("string")
     * @JMS\Expose()
     */
    private $description;

    /**
     * @var int
     *
     * @ORM\OneToMany(targetEntity="Item", mappedBy="category")
     */
    private $items;

    /**
     * @var int
     *
     * @ORM\OneToMany(targetEntity="Category", mappedBy="parent", cascade={"persist", "remove"})
     *
     * @JMS\Type("ArrayCollection<Amoblando\AdminBundle\Entity\Category>")
     * @JMS\Expose()
     * @JMS\MaxDepth(2)
     */
    private $children;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     *
     * @JMS\Type("Amoblando\AdminBundle\Entity\Category")
     * @JMS\Expose()
     */
    private $parent;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->items = new \Doctrine\Common\Collections\ArrayCollection();
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
    }

// Getters and setters



```

Then I get:

```json
[
  {
    "id": 1,
    "name": "Parent",
    "description": "Esta es la padre",
    "children": [
      {
        "id": 2,
        "name": "Child 1",
        "children": []
      },
      {
        "id": 3,
        "name": "Child 2",
        "children": []
      }
    ]
  },
  {
    "id": 2,
    "name": "Child 1",
    "children": [
      {
        "id": 4,
        "name": "Sub child 1",
        "children": []
      }
    ],
    "parent": {
      "id": 1,
      "name": "Parent",
      "description": "Esta es la padre",
      "children": [
        {
          "id": 3,
          "name": "Child 2",
          "children": []
        }
      ]
    }
  },
  {
    "id": 3,
    "name": "Child 2",
    "children": [
      {
        "id": 5,
        "name": "Sub child 2",
        "children": []
      }
    ],
    "parent": {
      "id": 1,
      "name": "Parent",
      "description": "Esta es la padre",
      "children": [
        {
          "id": 2,
          "name": "Child 1",
          "children": []
        }
      ]
    }
  },
  {
    "id": 4,
    "name": "Sub child 1",
    "children": [],
    "parent": {
      "id": 2,
      "name": "Child 1",
      "children": [],
      "parent": {
        "id": 1,
        "name": "Parent",
        "description": "Esta es la padre",
        "children": [
          {
            "id": 3,
            "name": "Child 2",
            "children": []
          }
        ]
      }
    }
  },
  {
    "id": 5,
    "name": "Sub child 2",
    "children": [],
    "parent": {
      "id": 3,
      "name": "Child 2",
      "children": [],
      "parent": {
        "id": 1,
        "name": "Parent",
        "description": "Esta es la padre",
        "children": [
          {
            "id": 2,
            "name": "Child 1",
            "children": []
          }
        ]
      }
    }
  }
]
```

**Comment by pestaa** [comment]
I think I have figured this out...

```php
    public function endVisitingObject(ClassMetadata $metadata, $data, array $type, Context $context)
    {
        $rs = parent::endVisitingObject($metadata, $data, $type, $context);

        // Force JSON output to "{}" instead of "[]" if it contains either no properties or all properties are null.
        if (empty($rs)) {
            $rs = new \ArrayObject();

            if (array() === $this->getRoot() && $context->getDepth() <= 1) {
                $this->setRoot(clone $rs);
            }
        }

        return $rs;
    }
```

The change is the additional check `&& $context->getDepth() <= 1` before changing the root result type to ArrayObject.

The library traverses the graph deeper before inserting the first root item. So if the first root item contains another nested (at any level) entity with "no properties or null properties only" (taking expose and exclusion strategies into account), then it correctly returns an empty ArrayObject -- but it also sets the root object to that type.

**Comment by rdohms** [comment]
Is it maybe a possibility that is the `@Type` is array, JMS does an implicit `array_values` before serializing, i mean you are making clear you want an array not an object?

Also the same could happen with the ArrayCollectionHandler, doing the implicit `array_values`.

**Comment by desmax** [comment]
>javiern opened this issue on Mar 21, 2014
Soon is the anniversary, guys! 3 years!

**Comment by Florin-Birgu** [comment]
For me the problem was when one of the children was the parent itself

**Comment by dTrimon** [comment]
Thanks @jedi4z , I had this problem, seaking fo a solution, and you gave it, . I have Arraycollection, and when typing it in the annotation 

> type: ArrayCollection<BddBundle\Entity\object
It works, and I get my nice arrays! You saved my life!

**Comment by BentCoder** [comment]
I had the same issue yesterday and solved it.

**Test example**

Given we have these objects.
```
class Product
{
    public $id;
    public $name;
    public $price;
}

class Price
{
    public $amount;
    public $source;
}
```

**EXAMPLE**

**Original response**
```
$product = new Product();
$product->id = 111;
$product->name = 'Tomato';
$price = new Price();
$price->amount = null;
$price->source = null;
$product->price = $price; // As you can see, we set all properties of $price as null

Product Object
(
    [id] => 111
    [name] => Tomato
    [price] => Price Object
        (
            [amount] => 
            [source] => 
        )
)
```
When I call `$this->serializer->serialize($product)`, response is this format `{"0": {...},"1": {...}, .....}`.

**Refactored response**

```
$product = new Product();
$product->id = 111;
$product->name = 'Tomato';
$price = new Price();
$price->amount = null;
$price->source = null;
$product->price = !array_filter((array) $price) ? null : $price; <------ Solution

Product Object
(
    [id] => 111
    [name] => Tomato
    [price] => 
)
```

Now, when I call `$this->serializer->serialize($product)`, response is this format `[{...}, {...}, ....]`.

**OUTCOME**
If your response object has a property (`price`) that holds an object (`Price`) and if **all** the properties of that object (`Price`) are empty, JMSSerializer messes things up. At least in my case!

**Comment by goetas** [comment]
Do you mind trying https://github.com/schmittjoh/serializer/pull/728?

**Comment by unti1x** [comment]
It still uses object notation if serialized object has virtual_properties/relations which are being transformed to empty object, e.g. because of serialization groups.

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/728 makes consistent the fact that an empty array is an array and an empty object stays an object.

If you want to have `null` instead of `{}`, then this is not the case.

I doubt that with the current available feature-set can be achieved. 

You will need something as "convert empty to null" as per-property serialization option

Is this your the case? 

There is a similar [feature](https://github.com/schmittjoh/serializer/blob/82ee7327ffebe93fb94ce4c14b6661cce1f89210/src/JMS/Serializer/Annotation/XmlCollection.php#L41) for the XML serialization process in `@XmlList(skipWhenEmpty=true)`

**Comment by unti1x** [comment]
I don't want to have `null`, I want it to use array notation for top level collection, not an object one

**Comment by goetas** [comment]
So we are talking of  `[]` instead of `[{},{},{},{}]` ?

**Comment by unti1x** [comment]
No, `[{}, {}, {}]` instead of `{"0": {}, "1": {}, ...}`

**Comment by goetas** [comment]
then just put `@Type("array<Classname>")`

**Comment by goetas** [comment]
this has been added in schmittjoh/serializer#728  so you will have to use  `master-dev` version on composer for `jms/serializer`

**Comment by unti1x** [comment]
I've tested it already and it's not my case (it was wrong serialization group and I fixed it before comment).

**Comment by unti1x** [comment]
Problem is that whole output turns into object instead of array if one of related objects is empty

**Comment by goetas** [comment]
did you follow this in case you are serializing a top-level array https://github.com/schmittjoh/serializer/blob/master/doc/cookbook/arrays.rst ?

**Comment by goetas** [comment]
> output turns into object instead of array if one of related objects is empty

that should have been fixed with https://github.com/schmittjoh/serializer/pull/730

**Comment by unti1x** [comment]
What a shame, :man_facepalming: I tested `master` branch of serializer bundle, not serializer itself. Yep, schmittjoh/serializer#730 does its job. Sorry.

**Comment by mikemix** [comment]
Still an issue here too

**Comment by goetas** [comment]
@BentCoder  your issue will be fixed with 1.7.0,  the option `@SkipWhenEmpty` has been introduced with https://github.com/schmittjoh/serializer/pull/757 and is doing exactly what you need

**Comment by serk1284** [comment]
Ok I figured it out.

**Comment by boskee** [comment]
Me too. That was easy.
