### ISSUE TITLE
Arrays beginning with index 1 are parsed as an object 

### ISSUE THREAD

**Issue by turbo-ele** [schmittjoh/JMSSerializerBundle#375]
I'm having the following problem: 
when i'm manipulating an entities relation, let's say a users phones, it sometimes appears that the resulting ArrayCollection starts with index 1 (deleting the first entry). The serializer then passes the array as an object with property 1.
Is there any way to bypass this and pass it as an array? Any help is appreciated!

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/728
