### ISSUE TITLE
Deserialize json array to array of entities

### ISSUE THREAD

**Issue by manonthemoon42** [schmittjoh/JMSSerializerBundle#376]
I have a json object that I received by making a get API call. I make this call to receive a list of objects. It's a list of post... So I have an array of Post Objects.

Here the output :

```
{
"total":2, 
"data":[
  {
    "id":2,
    "user":{
      "id":1,
      "username":"sandro.tchikovani"             
    },
    "description":"cool",
    "nb_comments":0,
    "nb_likes":0,
    "date_creation":"2014-04-13T20:07:34-0700"
  },
  {
    "id":1,
    "user":{
       "id":1,
       "username":"sandro.tchikovani",
     },
    "description":"Premier pooooste #lol",
    "nb_comments":0,
    "nb_likes":0,
    "date_creation":"2014-04-13T15:15:35-0700"
  }
  ]
 }
```

I would like to deserialize the data part... The problem is that the Serializer in Symfony gives me an error ...

The error that I have :

```
Class array<Moodress\Bundle\PosteBundle\Entity\Poste> does not exist
```

How I do deserialize :

```
$lastPosts = $serializer->deserialize($data['data'], 'array<Moodress\Bundle\PosteBundle\Entity\Poste>', 'json');
```

How can I deserialze the data array... To have an array of Postes. I want to give to my view .twig an array Poste... I did precise the type when I deserialize... So I can't find what is the problem...

Thanks.

**Comment by zeevin** [comment]
Have you solved the problem?
