### ISSUE TITLE
custom handler documentation

### ISSUE THREAD

**Issue by mikeSimonson** [schmittjoh/JMSSerializerBundle#379]
Hum.

Do you know where there might be any documentation on how to implement the handler of the handlercallback or the encoder ?

Right now I can output 

``` xml
<MyElement generator="zend" version="1.0">
    <xml_method>
        <getVersion>
            <response>1</response>
            <status>success</status>
        </getVersion>
    </xml_method>
</MyElement>
```

And I need to be able to remove the the <xml_method> element to have this : 

``` xml
<MyElement generator="zend" version="1.0">
        <getVersion>
            <response>1</response>
            <status>success</status>
        </getVersion>
</MyElement>
```

I can't find any documentation on how to do that.

**Comment by goetas** [comment]
Sorry for the incredibly long feedback loop. 
http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration#handlers you have a way to register a  custom handler. 

Inside it you can just visit the inner object with `graphNavigator->accept(object.getVersion())
