### ISSUE TITLE
Anotation "@Enum" was never imported error

### ISSUE THREAD

**Issue by pmartelletti** [schmittjoh/JMSSerializerBundle#380]
Hi guys,

I'm having an error trying to serialize an Doctrine Entity. I get the following error:

> [Semantical Error] The annotation "@Enum" in property Doctrine\ORM\Mapping\ManyToMany::$fetch was never imported. Did you maybe forget to add a "use" statement for this annotation?

The entity has excluded all the properties explicitly, and some are exposed with the `@Expose` method. Here is the code:

``` php
<?php

namespace Aaa\Bundle\CoreBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

use FOS\UserBundle\Model\User as BaseUser;
use Sylius\Bundle\AddressingBundle\Model\AddressInterface;
use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Expose;


/**
 *
 * @ORM\Entity
 * @ORM\Table(name="aaa_as_user")
 * @ExclusionPolicy("all")
 *
 */
class AsUser extends BaseUser
{
    /**
     * @var integer $id
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Expose
     */
    protected $id;

    /**
     * @var integer $aaaId
     * @ORM\Column(type="string", length=13, nullable=true)
     */
    protected $aaaId;

    /**
     * @var string $firstName
     * @ORM\Column(type="string", length=255)
     * @Expose
     */
    protected $firstName;

    /**
     * @var string $lastName
     * @ORM\Column(type="string", length=255)
     */
    protected $lastName;

    /**
     * @var DateTime $createdAt
     * @ORM\Column(name="created_at", type="datetime")
     * @Gedmo\Timestampable(on="create")
     * @Expose
     */
    protected $createdAt;
...
}
```

So, I don't have any ideas what could be wrong. It seems that the doctrine anotations are not being loaded correctly in the anotations I use here.

I've read a similar issue [here](https://github.com/schmittjoh/JMSSerializerBundle/issues/51) but it's not a proxy issue so I have no idea how to solve this (as the property that has the ManyToOne is excluded, as you can see in the code above; only the present properties are exposed).

So.. is this a bug? Or I'm missing some config? Any ideas?

Thanks a lot for your help!

**Comment by bichotll** [comment]
@solazs can you write down an example? I'm also in trouble...
I tried some ways, but still...error promped.

I checked composer show -i. And as I just checked I'm using the last of everything :(
doctrine/annotations 1.2.3
jms/serializer 0.16.0
jms/serializer-bundle 0.13.0

**Comment by bichotll** [comment]
@solazs oks, solved. I didn't expect it was needed on the pagination object :'p
Just if someone needs it on the future:
```php
$paginator = new Paginator($query);
$paginator->getQuery()->getArrayResult();
```

**Comment by bichotll** [comment]
@solazs never mind. Solved :'p

I was trying to parse an Paginator instance with JMSSearializer (I'm using FOS Rest).

```php
        //Paginator object returned
        $paginatorResult = $em->getRepository('BicVoucherEntityBundle:Offer')->findSearched($what, $categories, $tags, $offerTypes, $where, $when, $firstResult, $nResults);
        
        return $this->handleView(
                $this->view(
                        //because Paginator class implements IteratorAggregate
                        $paginatorResult->getIterator()->getArrayCopy(), 200
                        )
                //just to create the pagination
                ->setHeader('n_results', count($paginatorResult)));
```

Hope it helps someone.

**Comment by Ziiweb** [comment]
Im still gettig this error: 

`The annotation '@Enum' in property Doctrine\ORM\Mapping\GeneratedValue::$strategy was never imported. Did you maybe forget to add a 'use' statement for this annotation?`

Im just trying to serialize a paginator object:
```
$paginator = new Paginator($query, $fetchJoinCollection = true);
$serializer = \JMS\Serializer\SerializerBuilder::create()->build();
$jsonContent = $serializer->serialize($paginator, 'json');
```

These are my composer.json packages installed:

`doctrine/annotations                 v1.2.3             Docblock Annotations Parser`

**Comment by bichotll** [comment]
You can not parse paginator object straight away (JMSSerializer is not prepared for that), do the following:
```
$paginatorResult->getIterator()->getArrayCopy()
```

**Comment by alainhl** [comment]
If you are using PagerFanta as your paginator, you must do something like this: 

```$objPager = new Pagerfanta(new DoctrineORMAdapter($objQuery));
        $objPager->setMaxPerPage(100);
        $objPager->setCurrentPage(1);
        $objPager->getCurrentPageResults()->getArrayCopy()
```

**Comment by anjalirana** [comment]
@solazs :+1:  for saving my time :)

**Comment by ATLSAPI** [comment]
Very helpful guys Thanks!!

**Comment by Sabistik** [comment]
Hi, i have the same issue but when i use Doctrine\Common\Collections\Criteria to find rows:
```php
[Semantical Error] The annotation "@Enum" in property Doctrine\ORM\Mapping\GeneratedValue::$strategy was never imported. Did you maybe forget to add a "use" statement for this annotation?
```


When i use 
```php
$oItemsRows = $this->getEntityManager()->getRepository('Application\Entity\Item')->findBy(array(), $aOrder, $iLimit);
```
is serialized right but when i use:
```php
$oCriteria = Criteria::create();
$oCriteria->setMaxResults(2);

$oItemsRows = $this->getEntityManager()->getRepository('Application\Entity\Item')->matching($oCriteria);
````
i got error... Any suggestion?

Regards

**Comment by bichotll** [comment]
I guess that the object returned is not an array. 
Try to convert it to an array, then you'll be able to parse it.

**Comment by el-negro** [comment]
@solazs solution worked for me :+1:

**Comment by MaximStrutinskiy** [comment]
@solazs TY man, it's help.
