### ISSUE TITLE
Usage of @Groups

### ISSUE THREAD

**Issue by cincas** [schmittjoh/JMSSerializerBundle#382]
Hi everyone,

I think the usage of current @Groups annotation is a little bit limited.

Like say we have a main entity A with multiple sub entities B,C,D

In order to use @Groups, we have to put annotation across all entities, which is hard to maintain sometime.

I was hoping to have a feature like multi-level group policy.
such as 
@Groups({"foo"}) A
@Groups({"foo.taz"}) B
@Groups({"foo.bar", "foo.taz"}) C

Then if group is set to "foo", A, B and C will be shown.
if group is set to "foo.bar", both A and C will be shown, but not B

Will this be possible to make it?

Thanks.

**Comment by FullMoonIssue** [comment]
+1

Hello everyone,

I have exactly the same context.

group_public_api
    group_A  |  group_B  |  group_C  |  group_D
group_intern_api
    group_E  |  group_F

In order to write : @Groups({"group_public_api"}) => To apply to the four subgroups.

Nice day.

Best Regards,

**Comment by goetas** [comment]
I apologize for the late feedback, this probably is not your problem anymore, but for those who can still find similar issues, there are many different ways to achieve exclusion of some properties, each approach has advantages and drawbacks. Currently you can use: 

- [groups](http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#creating-different-views-of-your-objects)
- [groups per property](http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#overriding-groups-of-deeper-branches-of-the-graph)
- [expression language](http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#dynamic-exclusion-strategy)
- custom exclusion policy

Just use the one that works better for you, there is no reason to do this:

![square-peg-round-hole1](https://cloud.githubusercontent.com/assets/776743/24863642/fa0df568-1e01-11e7-856a-7199b9f47327.jpg)
