### ISSUE TITLE
custom type using a custom handler for primitives

### ISSUE THREAD

**Issue by sebastianreloaded** [schmittjoh/JMSSerializerBundle#385]
It's nice to have the @Type annotation to format e.g. datetime database fields. 

Why is it not possible to write a custom handler to modify primitives like string. My use case is to run htmlpurifier on certain fields that contain html. 

I now use the event pre_serialize, but a type annotation would be more flexible. Is there a reason it is not possible to use a custom type?

**Comment by nnmer** [comment]
The same here.
Always getting Logic Exception "Expected object but got string. Do you have the wrong @Type mapping or could this be a Doctrine many-to-many relation?"

**Comment by nnmer** [comment]
A half way done.
The manual not clear.

Looks that there are 2 types to consider - the field and class.
I finally find out how to get handle to class.

do not need in handler method **getSubscribingMethods**, but manual saying needed. The handler service should has a tag 
```
- { name: jms_serializer.subscribing_handler, type: 'Your\Entity\Class', direction: 'serialization', method: 'callThisMethod' }
```

this works.

but still a big question about the entity field Type.


@schmittjoh, it could be awesome if you can put a little bit more explanations in the manual

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/pull/610
