### ISSUE TITLE
Wrong Json Response 

### ISSUE THREAD

**Issue by selmanon** [schmittjoh/JMSSerializerBundle#387]
In the same response i get a field as object and a field as Array, how can i correct this ?
All details available by this link : http://stackoverflow.com/questions/23547419/fosrestbundle-jmsserializer-wrong-json-response

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved with https://github.com/schmittjoh/serializer/commit/b0a46c80cf3dbd97205f2e2ffeb9229080899c76 and available from serializer v1.2.0. 

(if not feel free to re open the issue or to comment here)

Thanks
