### ISSUE TITLE
if DiExtraBundle not available, JMSSerializer crash

### ISSUE THREAD

**Issue by asquel** [schmittjoh/JMSSerializerBundle#392]
If you uninstall DiExtraBundle, you get this error : 
Compile Error: Symfony\Component\Debug\DebugClassLoader::loadClass(): Failed opening required '/home/asquel/www/pnp2014/vendor/jms/di-extra-bundle/JMS/DiExtraBundle/DependencyInjection/Compiler/LazyServiceMapPass.php' 

If I comment the 3 following lines in JMSSerializerBundle : 
 /_if (class_exists('JMS\DiExtraBundle\DependencyInjection\Compiler\LazyServiceMapPass')) {
            return new \JMS\DiExtraBundle\DependencyInjection\Compiler\LazyServiceMapPass($tagName, $keyAttributeName, $callable);
        }_/

it works ...

**Comment by goetas** [comment]
Sorry for the long feedback loop.
This issue is probably already solved.

(if not feel free to re open the issue or to comment here)

Thanks
