### ISSUE TITLE
Warning: Erroneous data format for unserializing object constructor

### ISSUE THREAD

**Issue by akramfares** [schmittjoh/JMSSerializerBundle#394]
Hello,

I get this error after an update of my host (OVH shared hosting), i'm using the latest version of Symfony and JMS (updated via composer):

Warning: Erroneous data format for unserializing 'djepo\UserBundle\Entity\User' in /home/imgapps/www/vendor/jms/serializer/src/JMS/Serializer/Construction/UnserializeObjectConstructor.php line 29

My PHP version is 5.3.

Many thank's,
Akram

**Comment by eddiejaoude** [comment]
Has this been fixed now or still an issue?

**Comment by PalliDotCom** [comment]
Has this been fixed now or still an issue? Because I am getting the same problem.

**Comment by tmilos** [comment]
I got it too after upgrading php from 5.4.19 to 5.6.3

**Comment by eddiejaoude** [comment]
Yes, I had to downgrade the PHP version :cry:

**Comment by schmittjoh** [comment]
Could someone provide a pull-request using doctrine/instantiator? I promise, I'll merge this super-fast :)

**Comment by tmilos** [comment]
Made a quicky PR in schmittjoh/serializer#431

**Comment by schmittjoh** [comment]
Thanks, merged!
