### ISSUE TITLE
DateTime ISO8601 in PHP doesnt support milliseconds

### ISSUE THREAD

**Issue by farconada** [schmittjoh/JMSSerializerBundle#395]
dates from javascript code doesnt as in:

   dat = new Date();
   dat.toISOString();
   "2014-06-24T16:49:51.439Z"

has fractions of seconds.
PHP doesnt support fractions of seconds https://bugs.php.net/bug.php?id=51950 
Drupal has a workaround https://api.drupal.org/api/drupal/core%21vendor%21zendframework%21zend-stdlib%21Zend%21Stdlib%21DateTime.php/function/DateTime%3A%3AcreateFromISO8601/8
You could workaround this in jms config with

  jms_serializer:
      handlers:
        datetime:
            default_format: "Y-m-d\TH:i:s.uO" # ISO8601
            default_timezone: "UTC"

but it should be better coded in the bundle with a patch like the Drupal one

**Comment by pculka** [comment]
has this actually been fixed with PHP7?
https://3v4l.org/ADn0l

**Comment by goetas** [comment]
see https://bugs.php.net/bug.php?id=51950
