### ISSUE TITLE
Using jms_serializer.cache_naming_strategy.class overrides @SerializedName annotation

### ISSUE THREAD

**Issue by johnpez** [schmittjoh/JMSSerializerBundle#397]
I'm using jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy to use camel case instead of underscores, but when I have this activated my SerializedName annotation directives are ignored by the serializer.

Is this a bug or is there a workaround?

Thanks!

**Comment by maff** [comment]
See #445 for a solution without adding a new strategy.

**Comment by skiff-ff** [comment]
Brilliant! Great job, @wesnick !
