### ISSUE TITLE
PreSerialize Proxy Class

### ISSUE THREAD

**Issue by qpautrat** [schmittjoh/JMSSerializerBundle#407]
Hi there,

I'm facing an issue about serializing a Doctrine Proxy Class. I have a custom `EventSubscriber` with an `onPreserialize` method which is called to modify `Acme\Bundle\Entity\Address`object.
But, sometimes, which means when i'm trying to load an `Address` owned by my `User` authenticated (one-to-one relation), the `get_class()` function returns `Proxies\__CG__\Acme\Bundle\Entity\Address`.

So the `EventDispatcher` doesn't load my custom Subscriber: https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/EventDispatcher/EventDispatcher.php#L113

Because example are better than explanation (even more when you don't speak english very well...) I give you my use case:

I get an `Address` using `ParamConverter`
```PHP
public function getAction(Address $address)
{
    return $address;
}
```

And i have my subscriber referenced in my DIC config but it is not initialized in listener list of `EventDispatcher`:
```PHP
public static function getSubscribedEvents()
{
    return array(
        array('event' => 'serializer.pre_serialize', 'method' => 'onPreSerialize', 'class' => 'Acme\Bundle\Entity\Address')
    );
}

public function onPreSerialize(PreSerializeEvent $event)
{
    // Some stuff
}
```

How can i fix this ?

Thanks.

**Comment by hugomn** [comment]
Having the same issue here. Did you have any luck with this? Thanks!

**Comment by qpautrat** [comment]
Hi @hugomn ,

If i remember well, you don't have to specified a [class](https://github.com/schmittjoh/JMSSerializerBundle/blob/55bb8fc449c626ab8d47d58fa13fd37f84376dfc/DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php#L53).

But if you do, it will works if you specified Proxy class name
`Proxies\__CG__\Acme\DemoBundle\Entity\Class`

**Comment by hugomn** [comment]
Thanks, @qpautrat! I've just found another good solution. I've used `@Type` annotation specifying the full namespace in the one-to-one relation, and looks like it overrides proxy especification and then gets the serializer pre_serialize run! ;)

In your case, test if  `@Type("Acme\Bundle\Entity\Address")` solves your problem.

**Comment by qpautrat** [comment]
Thanks i will test asap !
