### ISSUE TITLE
Fatal error: Invalid opcode 153/1/8

### ISSUE THREAD

**Issue by JonnyD** [schmittjoh/JMSSerializerBundle#408]
I'm getting this error after deploying Symfony2 to VPS:

> Fatal error: Invalid opcode 153/1/8. in /home/mysite/public_html/beta/vendor/jms/serializer-bundle/JMS/SerializerBundle/JMSSerializerBundle.php on line 36

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved.
(if not feel free to re open the issue or to comment here)

Probably is an issue of your OPCache library

Thanks
