### ISSUE TITLE
Add kernel.cache_clearer and/or kernel.cache_warmer support

### ISSUE THREAD

**Issue by gena01** [schmittjoh/JMSSerializerBundle#415]
Please add support for either cache_clearer or cache_warmer. This will resolve a number of issues as well as providing a way to warm the cache and catch any serializer mapping errors during app/console cache:clear

**Comment by rande** [comment]
One of the reason is that JMS can serialize anyclass. So the solution will be to create a dedicated cache warmup (for doctrine entities).

**Comment by goetas** [comment]
Symfony is going to remove the `cache:clear` command since nobody was using it.... if you need to remove the cache.. just do `rm -rf carchedir`
