### ISSUE TITLE
When serialized collection of extendend objects returns {/*...*/} and must be [/*..*/]

### ISSUE THREAD

**Issue by rkmax** [schmittjoh/JMSSerializerBundle#418]
Example

``` php
MyClassA {
  //...
}
MyClassB extends MyClassC {
  //...
}
MyClassC {
  //...
}
```

when i serialize a collection of MyClassA i dont have problems i get

```
[

    {
        "property":  "value"
    }
]
```

but when i serialized a extended like MyClassB i get

```
{

    "0": {
        "property":  "value"      
    }

}
```

i'm using the same logic for both

```
$context = SerializationContext::create();
$context->setGroups(array(/*...*/));
$context->enableMaxDepthChecks();
return $serializer->serialize($collection, 'json', $context);
```

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved with schmittjoh/serializer@b0a46c8 and available from serializer v1.2.0.

(if not feel free to re open the issue or to comment here)

Thanks
