### ISSUE TITLE
filtering doctrine entites with  `ExclusionPolicy(All)`

### ISSUE THREAD

**Issue by Kifah** [schmittjoh/JMSSerializerBundle#419]
I am at the process of filtering the doctrine entites, with `ExclusionPolicy(All)`...

Is there a method call I can use, to get a list of all entites (in a project or a bundle), where the exclusionPolicy annotation is activated?

**Comment by goetas** [comment]
closing, 
sorry for the incredibly long feedback loop. the feature you asked do not exists. do not hesitate to re open a new issue if the problem persists
