### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by bmancone** [schmittjoh/JMSSerializerBundle#421]
Hi,

I'm using this Bundle on quite a big project.
Could you please tag a new version ?

Thank you for your awesome work on this Bundle.

Regards,

**Comment by jewome62** [comment]
+1

**Comment by eventhorizonpl** [comment]
+1

**Comment by allan-simon** [comment]
+1 , in China github is not very reliable, and having a tag release, make it easier to leverage cache proxy

**Comment by ivoba** [comment]
can be closed i guess, v1.0.0 is tagged and released
