### ISSUE TITLE
Exclude based on condition

### ISSUE THREAD

**Issue by websirnik** [schmittjoh/JMSSerializerBundle#422]
What is the right approach to exclude certain objects being serialized based on condition.
For example, when I serializing `User`, `User` has both pubic and private `Posts`. In a public context, I don't want private posts to be exposed. How should I prevent private posts from serialization?

I need to do something like the following. I know that the usage of `@Exclude` is not right, but just to illustrate the point.

``` php
class User
{
    /**
     *
     * @JMS\Groups({"user"})
     * @JMS\Exclude({"privacy.type":"private"})
     * @JMS\Type("array<Org\AppBundle\Document\Post>")
     * @MongoDB\ReferenceMany(targetDocument="Org\AppBundle\Document\Post")
     */
    protected $posts;
```

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/pull/673
