### ISSUE TITLE
Discriminator bug fix by upgrading required src

### ISSUE THREAD

**Issue by laurently** [schmittjoh/JMSSerializerBundle#423]
after experiencing the bug on a discriminator , i realized my problem was solved with 
https://github.com/schmittjoh/serializer/pull/238 
But this is only available on jms/serializer v0.16

so the question is :
How about an upgrade of the required jms/serializer to the version 0.16 for this bundle ? which is now ~0.11

**Comment by pipo02mix** [comment]
+1

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved since is a couple of years old.

(if not feel free to re open the issue or to comment here)

Thanks
