### ISSUE TITLE
Deserialize YAML

### ISSUE THREAD

**Issue by RedactedProfile** [schmittjoh/JMSSerializerBundle#428]
Is this a feature in the works, or?

Seems kind of strange to be able to one way serialize something... I mean I know I can just use Symfony's `Yaml::parse()` but I'd like to just kind of stick to one system, even if it is just transparent

**Comment by goetas** [comment]
in serializer 2.0 the yaml serialization/deserialization has been abandoned, suggested to use directly `Yaml::*` functions
