### ISSUE TITLE
Serializer does not seem to visit virtual properties recursively

### ISSUE THREAD

**Issue by erichfosse** [schmittjoh/JMSSerializerBundle#429]
I've got an entity with a virtual property that returns a subset of related entities, and these entities have a similar virtual property that returns a subset of their related entities, and those entities do as well.

```
Venue
  -> virtual property returns a subset of Exhibitions
    -> Exhibition
      -> virtual property returns a subset of Installations
        -> Installation
          -> virtual property returns a subset of Clients
```

When serializing all existing venues, the serializer returns venues with their exhibitions, but none of the exhibitions have any installations.
If I set the serialization groups so that the entities' whole collection of related entities are returned, I get all related entities. The problem only occurs when using virtual properties.

Any feedback is appreciated.

**Comment by goetas** [comment]
closing,
sorry for the incredibly long feedback loop. if the problem persists, please elaborate a bit more or provide a unit test, and will be happy to re open the issue. thank you
