### ISSUE TITLE
add option to alias field names

### ISSUE THREAD

**Issue by bazo** [schmittjoh/JMSSerializerBundle#433]
in our doctrine entities we have remnants after the previous programmer who left fields with names as mobil(instead of mobile), comId and many other.

now we want to expose these entities via an api, but need to present the fields under different names
e.g.: mobil -> mobile
comId -> businessId, etc

refactoring is not really an option i would like to pursue, since we also serialize some objects to json and that complicates things

so i had an idea about an alias annotation

``` php
    /** @JMS\Alias(value='mobile') */
    private $mobil;
```

what do you think?

**Comment by oxidec** [comment]
You can use the ```@VirtualProperty``` annotation
```php
/** @JMS\VirtualProperty */
public function getMobile() 
{
    return $this->mobil;
}
```

**Comment by kmfk** [comment]
[SerializedName](http://jmsyst.com/libs/serializer/master/reference/annotations#serializedname) does this already...?

    /** @JMS\SerializedName('mobile') */
    private $mobil;
