### ISSUE TITLE
Problem with namespace for XMLList

### ISSUE THREAD

**Issue by coolder** [schmittjoh/JMSSerializerBundle#438]
I'm trying to create a XML using JMSSerializerBundle, and this XML must have some nodes with namespace (please see gist linked below for full code example) but I get a node with wrong namespace, and this wrong namespace is repeated even in parent node (XMLList).

Have you ever faced a problem like this? 
Can you please help me figuring out how to solve this issue?
Tnx!

example code - https://gist.github.com/coolder/38157850a45cfef7ff22

**Comment by mattwells** [comment]
Its a bug in Goetas' customised version of the JMS Serializer for xsd2php in the [XmlSerializationVisitor::createElement()](https://github.com/goetas/serializer/blob/xsd2php/src/JMS/Serializer/XmlSerializationVisitor.php#L444-L461) not with the official release.

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/pull/301
