### ISSUE TITLE
SerializeNull

### ISSUE THREAD

**Issue by theofidry** [schmittjoh/JMSSerializerBundle#440]
Duplicate of [this issue](https://github.com/schmittjoh/JMSSerializerBundle/issues/276#issuecomment-71428288) that has been closed although the problem has not been solved (I can't reopen the issue...)

So, the question is how to serialise null attributes? If an attribute has the null value, my serialised entity doesn't have the attribute. Is there a way to specify that we which to have this attribute with the value `null` in our serialised object?

I found an [interesting issue](https://github.com/schmittjoh/JMSSerializerBundle/issues/293) about that. Is suggest to use the `SerialisationContext`:

```php
$context = new SerializationContext();
$context->setSerializeNull(true);
$serializer->serialize($object, 'json', $context);
```

And indeed it works fine for some entities:
```json
{
    "0": {
        "id": 1,
        "complementary_home": null,
        "complementary_location": "Bâtiment A",
        "street": "60, boulevard Louise Herve",
        "complementary_street": null,
        "postal": "80063",
        "city": "Vidalboeuf",
        "country": "Christmas Island"
    }
}
```

But when I check it on entities which some attributes are resolved with Doctrine, the problem is still there:
```json
{
    "0": {
        "id": 4,
        "name": "Caroline Rossi",
        "phone": {
            "id": 4,
            "number": "(552)312-9471"
        },
        "address": {
            "id": 4,
            "street": "179, avenue Xavier Peltier",
            "complementary_street": "BP 77 Belleville",
            "postal": "69 875",
            "city": "Leroux",
            "country": "Guyana"
        }
    }
}
```

**Comment by theofidry** [comment]
My bad, seems that there was an error in my code due to the fact that the context cannot be reused.

**Comment by lony** [comment]
@theofidry Is there something more general? I have multiple controllers (>10) each witch multiple methods and would love to have the serializer do this by default without configuring it for each method directly!

**Comment by theofidry** [comment]
I'm sorry @lony it's been so long I don't remember it at all :( That being said now Symfony serializer 2.7 has been greatly improved there is not much interest to use JMSSerializerBundle anymore if you can use it. (and it's more performant too!)

**Comment by lony** [comment]
@theofidry thank you but so far I can not switch. I will try around :)
