### ISSUE TITLE
Custom Class Type Mapping

### ISSUE THREAD

**Issue by bassrock** [schmittjoh/JMSSerializerBundle#446]
It should be possible to allow custom type mapping in the Symfony 2 Config. For instance, I use Carbon for my date fields. When serialized without a Type annotation they are just empty objects. But when I add the @Type("DateTime") they serialize correctly. 

Is there a way to map class types to specific Serializer Types in the config?

**Comment by goetas** [comment]
sorry for the incredibly long feedback loop.
the feature you asking does not exists. the solution you are using is the preferred, it does not rely on external configs, is simple and explicit

Do not hesitate to re open a new issue if the problem persists
