### ISSUE TITLE
Is it possible to prevent type casting of deserialize method?

### ISSUE THREAD

**Issue by feridmovsumov** [schmittjoh/JMSSerializerBundle#448]
I need prevent type casting because I am validating entity after deserializing it 

For example If I deserialize following json it will create entity with sort order 5. I am using this validation for my api and I don't give incorrect error messages. 

``` json
{"sort_order":"5aaa"} ==> Sort Order will be 5
{"sort_order":"aaa"} ==> Sort Order will be 0
```

Is there a way to prevent type casting?

**Comment by pwm** [comment]
I would like to know this as well.

**Comment by feridmovsumov** [comment]
I made all field types string in entity and then checked values with Validation class of Symfony.

**Comment by pwm** [comment]
Thanks, this is what I was thinking to do too.

Still, it would be nice to know if it's possible to disable automatic type casting (I don't have time atm to dig into the source).

**Comment by goetas** [comment]
Validation is a step that should happen before the deserialization. 

If you need validation, probably a better solution for you should be a pre-serialization listiner/subscriber.

**Comment by faridmovsumov** [comment]
Thanks @goetas it is good idea.
