### ISSUE TITLE
PHP Fatal error:  Using $this when not in object context in JMS/Serializer/Serializer.php on line 99

### ISSUE THREAD

**Issue by simonhayre** [schmittjoh/JMSSerializerBundle#450]
PHP Fatal error:  Using $this when not in object context in JMS/Serializer/Serializer.php on line 99

**Comment by davidmaraba** [comment]
Got the same error

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved (was a php 5.3 issue, now the serializer requires php 5.5 at least).

(if not feel free to re open the issue or to comment here)

Thanks
