### ISSUE TITLE
Add server url to image on serialization

### ISSUE THREAD

**Issue by manelselles** [schmittjoh/JMSSerializerBundle#451]
I have an attribute which references the path inside the public directory to a certain image.

When I serialize the entity I want this attribute to be prefixed with server url to obtain the absolute URL to the image. 

Example:
- **Attribute:** img/product/323124.jpg
- **Desired:** www.serverwithimages.com/img/product/323124.jpg

Any way to add this prefix to the serialized attribute? I could obtain the server url from the request but I don't know how to send/inject to the serializer.

Thank you!

**Comment by penoa** [comment]
Hi,

You may use the PRE_SERIALIZE event.

2015-05-07 9:38 GMT+02:00 manelselles <notifications@github.com>:

> I have an attribute which references the path inside the public directory
> to a certain image.
>
> When I serialize the entity I want this attribute to be prefixed with
> server url to obtain the absolute URL to the image.
>
> Example:
>
>    -
>
>    *Attribute:* img/product/323124.jpg
>    -
>
>    *Desired:* www.serverwithimages.com/img/product/323124.jpg
>
> Any way to add this prefix to the serialized attribute? I could obtain the
> server url from the request but I don't know how to send/inject to the
> serializer.
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schmittjoh/JMSSerializerBundle/issues/451>.
>



-- 
*Benoit Henner*
18 Avenue du 8 Mai 1945
57300 HAGONDANGE
Tél. : 00336 75 39 47 39
Tél. : 00339 50 57 92 82

**Comment by manelselles** [comment]
Thank you! It works perfect now!

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue looks solved.

(if not feel free to re open the issue or to comment here)

Thanks
