### ISSUE TITLE
@JMS\Serializer\Annotation\Type("DateTime<'c'>") doesn't works properly

### ISSUE THREAD

**Issue by ghost** [schmittjoh/JMSSerializerBundle#459]
When decoding date in format ISO8601 the annotation with format @JMS\Serializer\Annotation\Type("DateTime<'c'>") doesn't works. 
You should use the annotation @JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:sP'>") instead.

**Comment by goetas** [comment]
thanks for the info.
