### ISSUE TITLE
Jms serializer @JMS\Inline() annotation overrides an actual id

### ISSUE THREAD

**Issue by feridmovsumov** [schmittjoh/JMSSerializerBundle#460]
I have product and product_detail tables in database.

Every product has a product detail.

``` php
class Product
{
   /**
     * @var ProductDetail
     * @JMS\ReadOnly()
     * @ORM\OneToOne(targetEntity="ApiBundle\Entity\ProductDetail", mappedBy="product", cascade={"persist"})
     * @JMS\Inline()
     */
    private $detail;
}
```

I use @JMS\Inline() annotation to show only detail information of product_detail table. But when I serialize a product I get wrong id. It must be product id but id returns an product detail id. Is it bug or I am doing something wrong?

**Comment by mvrhov** [comment]
You should not expose the id from the detail when using inline.

**Comment by feridmovsumov** [comment]
Thank you very much.

**Comment by goetas** [comment]
> You should not expose the id from the detail when using inline.
