### ISSUE TITLE
Fix PHP requirements inside composer.json

### ISSUE THREAD

**Issue by b00giZm** [schmittjoh/JMSSerializerBundle#465]
You currently require `php >=5.3.2` for your bundle, but also require `jms/serializer: ^1.0.0`, which itself requires PHP >= 5.4.0 and breaks for PHP 5.3.*

Don't know why, but somehow this wasn't caught by the Composer check and caused trouble on our production servers which run PHP 5.3.*

**Comment by stof** [comment]
@b00giZm have you run your ``composer update`` command on a machine using a higher PHP version ? This might be the reason why it was not caught.
another possible cause would be that the dev used the ``--ignore-platform-reqs`` option (in which case he is totally responsible and changing the bundle requirements would not change anything).

Btw, to avoid issues like that in case your local PHP version does not match the prod, you should use the ``config > platform`` setting in your composer.json: https://getcomposer.org/doc/06-config.md#platform

**Comment by goetas** [comment]
Sorry for the long feedback loop. This issue is probably already solved.
(if not feel free to re open the issue or to comment here)

Thanks
