### ISSUE TITLE
PreSerialize + Groups

### ISSUE THREAD

**Issue by pe77** [schmittjoh/JMSSerializerBundle#471]
Hey bro!

I can use Groups and Preserialize at same time?

For example, in my case:

```
    /**
     * @JMS\PreSerialize
     * @JMS\Groups({"Admin"})
     */
    public function onPreSerialize()
    {
     ...
```

Just don't work. The group ignored. The function is always called.

I could not tell if this is just a problem. Anyway, is there anything I can do?

**Comment by rodrigorigotti** [comment]
You can create a subscriber which extends the `JMS\Serializer\EventDispatcher\EventSubscriverInterface` and create the `onPreSerialize` method, which receives the `JMS\Serialzier\EventDispatcher\PreSerializeEvent` event object.

Then use the following method to get access to the current request's groups:

    $event->getContext()->attributes->get('groups')->get()

**Comment by pe77** [comment]
Thanks! Work perfectly!!!

**Comment by elvispdosreis** [comment]
Could you give me an example of how to implement this I'm having the same problem
