### ISSUE TITLE
Eror while composer install

### ISSUE THREAD

**Issue by dkovalenko** [schmittjoh/JMSSerializerBundle#478]
I have this string in my require section in composer.json:
"jms/serializer-bundle": "0.12.0",

Running composer install results in 
[RuntimeException]                                                                                                                                       
  Could not load package jms/serializer-bundle in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0.0: Invalid ver  
  sion string "^1.0.0"

**Comment by rodrigorigotti** [comment]
Your composer version might be too old. Try updating it:

    composer selfupdate

**Comment by gielfeldt** [comment]
Updating composer worked for me.

**Comment by rodrigorigotti** [comment]
If the issue is solved, then please close it. :)

**Comment by dkovalenko** [comment]
It worked, thank you!
