### ISSUE TITLE
When serializing subentities discriminator value is always added to serialized output

### ISSUE THREAD

**Issue by johnpez** [schmittjoh/JMSSerializerBundle#479]
I have an abstract parent entity with several sub entities. The discriminator column is called "type". No matter what, when serializing these sub entities, the "type" column is added to the output, even though it isn't a property that I can access on the entity, thus I can't get rid of it.

I've solved through a rather roundabout method of overriding GenericSerializationVisitor (via overriding JsonSerializationVisitor) and adding a method "removeData". 

```
public function removeData($key){
    if (isset($this->data[$key])) unset($this->data[$key]);
}
```

Then, I have a listener function set up on post_serialize of my sub entities, in which I call

```
public function postSerializeSubEntity(ObjectEvent $event)
{
    $event->getVisitor()->removeData('type');
}
```

Hope this is helpful to someone else. If there is a better way of solving this issue that I missed please let me know!

**Comment by goetas** [comment]
sorry for the incredibly long feedback loop.
 you can put the "type" in a non existent group. see "groups" option on `@discriminator` annotation
