### ISSUE TITLE
Pagerfanta and Groups possible bug

### ISSUE THREAD

**Issue by antonioperic** [schmittjoh/JMSSerializerBundle#485]
Hi guys,
I am usign pagerfanta for pagination

```
        $pagerFactory = new PagerfantaFactory();
    $paginatedColl = $pagerFactory->createRepresentation(
        $paginator,
        new Route($route, $routeArgs, true)
    );
```

and after that I am trying to get JsonReponse in this way

```
        $context = SerializationContext::create();
    $context->setGroups(array('Events'));

    return new JsonResponse(
        $this->get('serializer')->toArray($cities, $context)
    );
```

I am also using HateoasBundle.

My problem is that if I setGroups to only Events I got empty array for reposnse if I set Default, Events I got everything fine.

**Comment by snwFlake** [comment]
Same problem here.

**Comment by bblue** [comment]
I am using pagerfanta and the group's exclusion is working fine, think you have an error in your configuration or mapping data.

Seeing this issue is from 2015 I propose to close it.

**Comment by goetas** [comment]
:+1:
