### ISSUE TITLE
AccessorOrder is ignored

### ISSUE THREAD

**Issue by fedebalderas** [schmittjoh/JMSSerializerBundle#488]
I got a problem ordering serialized output order of my fields.
This is my code 
`
/**
- @ORM\Entity(repositoryClass="AppBundle\Entity\CustomerRepository")
- @ExclusionPolicy("all") 
- @AccessorOrder("custom", custom = {"custom_id", "company_name", "first_name", "last_name", "email", "phone_number", "line1", "line2", "line3", "city", "state", "postal_code", "country_code", "created_at"})
  */
  class Customer
  ....
  ....
  `

And the response is the same, like if AccessorOrder was ignored.
`
{
    "id": "edf007d651855ab64f9c",
    "state": "Guanajuato",
    "created_at": "2015-09-17T12:42:21-0500",
    "company_name": "Foograde",
    "line1": "Gral. Ortega #223D",
    "first_name": "Federico",
    "city": "Celaya",
    "postal_code": "38010",
    "last_name": "Mata",
    "email": "federico.balderas@foograde.com",
    "country_code": "MX",
    "line2": "Col. Alameda"
  }`
`

Any idea?

**Comment by hacfi** [comment]
@fedebalderas just had the same issue..use your property names like `customId`,  `companyName` etc. and it should work.

**Comment by eugene-matvejev** [comment]
it works as expected, proof: https://github.com/eugene-matvejev/battleship-game-api/blob/master/src/GameBundle/Entity/Battlefield.php

**Comment by goetas** [comment]
> @fedebalderas just had the same issue..use your property names like customId, companyName etc. and it should work.
