### ISSUE TITLE
Ability to add custom exclusion strategies and override existing one

### ISSUE THREAD

**Issue by vishalmelmatti** [schmittjoh/JMSSerializerBundle#489]
I am using FOSRestBundle and JMSSerializerBundle. I have use case to override MaxDepthExclusionStrategy or add  custom strategy. 

I understand it can be done by

```
$context = new SerializationContext();
$context->addExclusionStrategy($this->get('acme.my_exclusion_strategy_service'));

$serial = $this->get('jms_serializer')->serialize($object, 'json', $context);
```

But it needs SerializationContext object to be created separately. 

May be having configuration 'exclusion_strategies'  with the list of services (or tagged services) could help lot something like 'visitors' configuration.'

**Comment by ktounet** [comment]
:+1:

**Comment by goetas** [comment]
with https://github.com/schmittjoh/serializer/pull/645 you can provide a default contrext factory
