### ISSUE TITLE
Twig_Function_Method class is deprecated since version 1.12

### ISSUE THREAD

**Issue by tuanquynh0508** [schmittjoh/JMSSerializerBundle#490]
Hi !

I use Symfony 2.3 with jms/serializer-bundle 1.0. But, I have a problem can not run Unit test because in SerializerExtension use Twig_Filter_Method. And I recieve error:
"The Twig_Function_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead."

Help me please!.

**Comment by michaelperrin** [comment]
@tuanquynh0508 You need to upgrade the `jms/serializer` package to version 1.1 . So try to upgrade using `composer update jms/serializer`.

**Comment by tuanquynh0508** [comment]
Thanks @michaelperrin  so much!
