### ISSUE TITLE
How to change Strategy

### ISSUE THREAD

**Issue by Nainterceptor** [schmittjoh/JMSSerializerBundle#493]
Hello,

How can I change strategy to "Identical" ?

I've done the following workaround and it's working but it's weird...

```
parameters:
    #Workaround camel case on JMSSerializer
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
```

If I have tried to do something like the following, successless. (Strings are capitalized)

```
            property_naming:
                separator:  null
                lower_case: false
```

Thanks,

Gaël

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/JMSSerializerBundle/commit/7308fa4427bde363282fe8507d14d98469e29a9f see commint and documentation for reference
