### ISSUE TITLE
Are there any way to select entity fields dinamically?

### ISSUE THREAD

**Issue by xserrat** [schmittjoh/JMSSerializerBundle#496]
Hi,

I'm using JMSSerializer in order to create an API REST. For each API route you can select **which fields** you want to display in the response through query string parameters, for example:

Route `/users/123?fields=name,surname,age`

``` json
{
    "name": "Mark",
    "surname": "Spencer",
    "age": "12"
}
```

So, my question is about how can I choose entity fields dinamically?

Thanks,

**Comment by goetas** [comment]
possible with https://github.com/schmittjoh/serializer/pull/673

**Comment by xserrat** [comment]
Thank you so much @goetas ! :)
