### ISSUE TITLE
Ignore entity and/or subentity based on attribute value

### ISSUE THREAD

**Issue by phackwer** [schmittjoh/JMSSerializerBundle#499]
Assume we are serializing an entity which has logical exclusion on the database. And that this exclusion is set a flag (let's assume the name isActive - is_active for it).

To avoid the entire entity to be serialized, should I create a Listener for the preSerialized? Would it ignore subentities with excluded attributes, like a person registry with 2 addresses, and one address flaged as inactive?

**Comment by goetas** [comment]
Create a virtual property, and inside decide how to serialize your data. 

http://jmsyst.com/libs/serializer/master/reference/annotations#virtualproperty

If you need external data to decide if serialize or not your data, use the expression language
