### ISSUE TITLE
@MaxDepth should hide the property from the serialized result

### ISSUE THREAD

**Issue by Seb33300** [schmittjoh/JMSSerializerBundle#500]
Hello,

When using `@MaxDepth` combined to the `SerializeNull` option, the children properties on which we set the `@MaxDepth` option appear in the result with `null` value since it should be ignored.

Is there a way to fix it?

Another thing, is it possible to set the `enableMaxDepthChecks` globally?

Thanks

**Comment by goetas** [comment]
I'm working on a similar issue this days.. can you provide an example?

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/serializer/pull/743
