### ISSUE TITLE
The FormErrorHandler forces the translation domain to 'validators'

### ISSUE THREAD

**Issue by vbourdeix** [schmittjoh/JMSSerializerBundle#501]
I have configured my application to use 'messages' as the translation domain with the following configuration in my config.yml.

```
framework:
    validation:      { translation_domain: messages }

```

But when I have validation errors in my forms, the FormErrorHandler forces the translation catalogue to validators in the getErrorMessage method. It should take into account the framework parameter validator.translation_domain.

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/JMSSerializerBundle/pull/580 and https://github.com/schmittjoh/serializer/pull/783
