### ISSUE TITLE
Installation issues using composer

### ISSUE THREAD

**Issue by bretanac93** [schmittjoh/JMSSerializerBundle#507]
Hi, yesterday i'd installed this package using composer and everything goes simply fine, then I'd updated the composer phar file to the beta 1, and then when I'd try to install today in another project, I'd got this installation problem, what could be this?, thanks and best regards.

Problem 1
    - Installation request for jms/serializer-bundle ^1.1.0 -> satisfiable by jms/serializer-bundle[1.1.0].
    - jms/serializer-bundle 1.1.0 requires php >=5.4.0 -> your PHP version (5.6.8) overriden by "config.platform.php" version (5.3.9) does not satisfy that requirement.

**Comment by mikejw** [comment]
I'm also having this issue using MacPorts on OS X 10.11.

**Comment by mikejw** [comment]
@bretanac93 hey man, this was the fix for me: http://stackoverflow.com/a/35538178/6108127

**Comment by davidpestana** [comment]
HI,

i have similar issue

  Problem 1
    - Installation request for jms/serializer-bundle ^1.1 -> satisfiable by jms/serializer-bundle[1.1.0].
    - jms/serializer-bundle 1.1.0 requires php >=5.4.0 -> your PHP version (5.6.11-1ubuntu3.1) does not satisfy that requirement.


solved, overwriting version at composer.json

   ```
 "config": {
        "bin-dir": "bin",
        "platform": {
            "php": "5.6.11"
        }
    },
```

**Comment by mvrhov** [comment]
Imo it would be best to report this to composer. as it seems that the composer is unable to properly parse your php version
