### ISSUE TITLE
Can't override third party serializer config file

### ISSUE THREAD

**Issue by oatto** [schmittjoh/JMSSerializerBundle#511]
I'm using symfony v2.8.4-dev and I have noticed that the overriding file didn't work anymore, because symfony doesn't bring the config key as config name. 

The temporary solution that I have fixed by adding this line in JMS\SerializerBundle\DependencyInjection\Configuration

`->useAttributeAsKey('name')`
next to
`->arrayNode('directories')`
so it becomes:
`->arrayNode('directories')
->useAttributeAsKey('name')`

**Thank you**

**Comment by goetas** [comment]
duplicate of https://github.com/schmittjoh/JMSSerializerBundle/pull/531
