### ISSUE TITLE
SerializationListener not being called for sub entities after upgrading to 1.1.0

### ISSUE THREAD

**Issue by hugomn** [schmittjoh/JMSSerializerBundle#514]
I was using JMSSerializer 0.16.0 and SerializationListener was working fine. I have entities like this:

```
/**
 * @ExclusionPolicy("all")
 */
class EntityA {
    /**
     * @Expose
     */
    private $entityB;
}
```

I have two SerializationListeners, for EntityA and EntityB. Before upgrading to 1.1.0 the listener was beign called correctly for EntityB when deserializing EntityA. But now it's not working anymore. I´ve tried to find any updates in the documentation but couldn't find it. Any ideas? Is it happening with anyone else? Thanks!

**Comment by tiemevanveen** [comment]
Any updates on this, did you fix the problem @hugomn 

The "Upgrading From 0.11 to 1.0" section is still empty, I was wondering if anything came up. 
https://github.com/schmittjoh/JMSSerializerBundle/blob/master/UPGRADING.md

**Comment by hugomn** [comment]
Hi @tiemevanveen! No updates on this. I've just reverted my version to 0.16.0. I need to try 1.1.0 again. Did you have the same problem?

**Comment by tiemevanveen** [comment]
No problems here, but I'm updating a lagacy project and wanted to be aware of breaking changes.

**Comment by goetas** [comment]
probably related to https://github.com/schmittjoh/serializer/pull/677
