### ISSUE TITLE
Twig deprecation in Serializer 

### ISSUE THREAD

**Issue by rehoehle** [schmittjoh/JMSSerializerBundle#516]
There are some old dependencies in this bundle that contains an old version of the "serializer" in the new serializer version there are fixes for the deprecation. Is it possible to change the dependency to the new version? Or are there some problems?

**Comment by BallisticPain** [comment]
Did you ever get this figured? We are looking to upgrade to SF 3.x and this is one of our limitations... haven't just tried it yet though.

**Comment by goetas** [comment]
I'm using this project in many sf 3.2 applications... which specific problems do you have?

**Comment by BallisticPain** [comment]
@goetas Thanks for letting me know that. Which version are you using?

Though I must say, I'm not sure I'm going to be using this any further as it caused Doctrine to hydrate objects that I had not exposed which then caused a TON of queries that weren't necessary.

**Comment by goetas** [comment]
as said, im using sf 3.2, with doctrine 2.5 ....

if you have deprecations in your symfony profiler, can you post them here?

**Comment by BallisticPain** [comment]
@goetas 
I meant which version of *this* project are you using. I did notice you said SF 3.2 ;).

Here are the ones I believe are related to the serializer...
```
23:41:37
php	The Twig_Filter_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead. Show stack trace
23:41:37
php	The Twig_Filter class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.  Show stack trace
23:41:37
php	Using an instance of "Twig_Filter_Method" for filter "serialize" is deprecated since version 1.21. Use Twig_SimpleFilter instead. Show stack trace
23:41:37
php	The Twig_Function_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead. Show stack trace
23:41:37
php	The Twig_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead. Show stack trace
23:41:37
php	Using an instance of "Twig_Function_Method" for function "serialization_context" is deprecated since version 1.21. Use Twig_SimpleFunction instead.  Show stack trace
```

**Comment by goetas** [comment]
jms serializer bundle 1.1.0
and jms serializer 1.5-rc

**Comment by BallisticPain** [comment]
@goetas 
I have
JMSSerializerBundle 0.13
JMSSerializer 0.15

So that may explain the issues I've been seeing. My version seems ancient.

**Comment by goetas** [comment]
closing the issue
