### ISSUE TITLE
Error in security.access.decision_manager service in Symfony 3.1

### ISSUE THREAD

**Issue by mkrause** [schmittjoh/JMSSerializerBundle#518]
Under JMSSerializerBundle 1.1, I get the following exception when upgrading to Symfony 3.1:

    [Symfony\Component\Debug\Exception\ContextErrorException]
    Catchable Fatal Error: Argument 1 passed to Symfony\Component\Security\Core
    \Authorization\DebugAccessDecisionManager::__construct() must be an instance of 
    Symfony\Component\Security\Core\Authorization\AccessDecisionManager, instance of 
    JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager given

It looks like Symfony 3.1 introduced a new class [DebugAccessDecisionManager](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Authorization/DebugAccessDecisionManager.php), which wraps around the `AccessDecisionManager` instance. This conflicts with the serializer bundle's own `RememberingAccessDecisionManager` wrapper class.

**Comment by mkrause** [comment]
On further inspection this looks like it should be fixed in JMSSecurityExtraBundle. May be related to [this issue](https://github.com/schmittjoh/JMSSecurityExtraBundle/issues/201)?

**Comment by Ener-Getick** [comment]
This looks like an error in symfony, i'll submit a patch.

**Comment by Ener-Getick** [comment]
I opened https://github.com/symfony/symfony/issues/18938

**Comment by mkrause** [comment]
I'll close this, in favor of schmittjoh/JMSSecurityExtraBundle#207
