### ISSUE TITLE
What's the purpose of 'id' under 'property_naming' namespace in configuration.

### ISSUE THREAD

**Issue by martinsik** [schmittjoh/JMSSerializerBundle#522]
[Configuration.php](https://github.com/schmittjoh/JMSSerializerBundle/blob/master/DependencyInjection/Configuration.php#L81) defines `'id'` option under `property_naming` namespace but it doesn't seem to be used anywhere, it's not even covered in the documentation.

**Comment by monobook** [comment]
@schmittjoh

PS: from @weaverryan the [same](https://github.com/schmittjoh/JMSSerializerBundle/issues/449) old issue

**Comment by goetas** [comment]
duplicate of https://github.com/schmittjoh/JMSSerializerBundle/issues/449
