### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by matiux** [schmittjoh/JMSSerializerBundle#525]
Hi, I have some problem to understand how can I configure the bundle on Symfony 3.
For now, zero-config works. In a test that extends `KernelTestCase,` I get `jms_serializer` from the container, then I call
`
$this->serializer->serialize($dummyEntity);`

But I need to:
1) specify what fields is need to serialize because not all fields are necessary
2) enable cache system

How can I configure them?

**Comment by goetas** [comment]
what about http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration
