### ISSUE TITLE
Configurable defaults (groups) for serialization

### ISSUE THREAD

**Issue by akomm** [schmittjoh/JMSSerializerBundle#530]
Related to [this](https://github.com/schmittjoh/JMSSerializerBundle/issues/491).

Basically if you want to hide information by default and explicitly provide it via group, you are doomed to take care of setting 'Default' group every time you serialize data. This might be a potential security problem.

My proposal is to provide a defaults configuration, including the groups as a starter (any other defaults useful?)

**Comment by goetas** [comment]
closing this for the same reasons emerged in https://github.com/schmittjoh/JMSSerializerBundle/pull/427
