### ISSUE TITLE
Check for broken serialization metadata mappings

### ISSUE THREAD

**Issue by markri** [schmittjoh/JMSSerializerBundle#534]
I just got my self in a very long debug session, trying to found out why my YAML (but will also apply for XML i guess) mapping wasn't applied on serialization. Finally it became clear that my mapping file just wasn't found and therefore simply skipped. And no single layer reporting about it.

The strict naming is a good thing, however it now results in quite some harsh results. 
Looking at following config

    jms_serializer:
        metadata:
            directories:
                my_models:
                    namespace_prefix: "Customer\\Project\\Domain"
                    path: "@CustomerProjectBundle/Resources/config/serializer"

Isn't it a good idea to test for all available configs in that directory to test for unmapped entities? This way it will become clear very quickly that a mapping is skipped and should be fixed. Also when someone refactors a model to a different name, than the developer isnt notified of broken serialization (which was there before).

**Comment by sanderfreshheads** [comment]
Thnx! I had a similar problem. A typo in my path config had me debugging my code for over 2 hours!!!

**Comment by ahilles107** [comment]
Hey, for us it was BC break ;) But good one as we had left in config not used anymore path. Thanks for developing that bundle!

**Comment by goetas** [comment]
Was mentioned in the [UPGRADING.md](https://github.com/schmittjoh/JMSSerializerBundle/blob/master/UPGRADING.md#upgrading-from-1x-to-20)
