### ISSUE TITLE
All services are broken

### ISSUE THREAD

**Issue by adadgio** [schmittjoh/JMSSerializerBundle#541]
I just did a composer update yesterday, and I use jms/di-extra-bundle from `dev- master`.

On cache clear, ALL services defined with `@DI\Service` are broken (`Symfony\...\ServiceNotFoundException`).

I've not beeing changin any service definition for over a year. Any chance something bad happened recently on this repository ?

**Comment by goetas** [comment]
After the composer update, probably other packages get the updates too..

Which other deps have been upgraded?

**Comment by adadgio** [comment]
Sorry, wrong repository ! I was trying to post on JMSDIExtraBundle

**Comment by adadgio** [comment]
Its strange, my composer file hasn NOT changed a bit.

**Comment by goetas** [comment]
dependencies gets updated even if you do not change your composer file

**Comment by adadgio** [comment]
So there is no way to find what/which is broken ?

**Comment by goetas** [comment]
you can compare your `composer.lock` files, that file contains the detailed  list of dependencies including the exact version/commit-id of all the packages installed by composer

**Comment by adadgio** [comment]
And i did not even think about that... You actually just saved my day here...
