### ISSUE TITLE
PreSerializationListener not being called anymore after updating

### ISSUE THREAD

**Issue by tzfrs** [schmittjoh/JMSSerializerBundle#554]
I upgraded my SerializerBundle from version `0.16.0` to `1.5.0` and started to execute some tests. I noticed that some tests failed and had to see that my PreSerializationListener is not getting called anymore. The PostSerializationListener works without problems

This is the content of `getSubscribedEvents` in the working Serializer (Post)

```
public static function getSubscribedEvents()
{
    return [
        [
            'event' => Events::POST_SERIALIZE,
            'method' => 'addAdditionalFields',
            'class' => Product::class,
            'format' => 'json',
        ],
    ];
}
```

and this from the not working Serializer (Pre)

```
public static function getSubscribedEvents()
{
    return [
        [
            'event'  => Events::PRE_SERIALIZE,
            'method' => 'addProductTitle',
            'class'  => Product::class,
            'format' => 'json',
        ],
    ];
}
```

What is the best way to find out why it doesn't work anymore? Worked without any problems with the `0.16.0` ve3rsion.

**Comment by goetas** [comment]
that's a good question. a lot of things changed from 0.16.0 to 1.5.0.

Are you using it via symfony-bundle or is a unit test failure?

**Comment by goetas** [comment]
What is the value of `Events::PRE_SERIALIZE`? `Events` is your class right?

**Comment by goetas** [comment]
related probably to https://github.com/schmittjoh/JMSSerializerBundle/issues/514

**Comment by tzfrs** [comment]
Hey. It's both a UnitTest failure and when I use it in production. The value is `serializer.pre_serialize` and is in both classes coming from the class `JMS\Serializer\EventDispatcher\Events`

**Comment by goetas** [comment]
can you post your unit test... i tried to check, but can not find anything wrong with it at the moment

**Comment by tzfrs** [comment]
No sorry, can't post it here.

**Comment by goetas** [comment]
ok. unfortunately without a way to reproduce the issue, can't help you.

**Comment by goetas** [comment]
If you find a way to reproduce the issue, let me know, will re-open the issue

**Comment by tzfrs** [comment]
I'm not sure as to why you need my unit test to reproduce it? What's failing is that the EventDispatcher calls my SerializationListener. In a UnitTest the dispatcher would be mocked anyway, so I don't see the point of posting my unit test.

**Comment by goetas** [comment]
Ad you can see in https://github.com/schmittjoh/serializer/commit/982288ec60b12f58a0b5c3a3c96a3cfd929ccc56 i tried to reproduce case  and the test is green https://travis-ci.org/schmittjoh/serializer/builds/211324875 

Notice "Called" in the console output

**Comment by tzfrs** [comment]
I just reproduced it as well in my own test

```
class Test extends \PHPUnit_Framework_Testcase
{
    public function testSomething()
    {
        $dispatcher = new EventDispatcher();
        $dispatcher->addSubscriber(new MockSubscriber());
        $obj = new \stdClass();

        $namingStrategy = new SerializedNameAnnotationStrategy(new CamelCaseNamingStrategy());
        $objectConstructor = new UnserializeObjectConstructor();
        $serializationVisitors = new Map(array(
            'json' => new JsonSerializationVisitor($namingStrategy)
        ));
        $deserializationVisitors = new Map(array(
            'json' => new JsonDeserializationVisitor($namingStrategy)
        ));

        $serializer = new Serializer(
            new MetadataFactory(new AnnotationDriver(new AnnotationReader())),
            new HandlerRegistry(),
            $objectConstructor,
            $serializationVisitors,
            $deserializationVisitors,
            $dispatcher
        );



        $serializer->serialize($obj, 'json');
    }
}

class MockSubscriber implements EventSubscriberInterface
{
    public static $events = array();

    public static function getSubscribedEvents()
    {
        return [array(
            'event'  => 'serializer.pre_serialize',
            'method' => 'method',
            'class'  => \stdClass::class,
        )];
    }

    public function method()
    {
        var_dump("Called");
    }
}
```

So this confuses me even more. Both listeners are defined as `<tag name="jms_serializer.event_subscriber" />` and the `getSubscribedEvents` is as I already posted here, so no idea what makes it fail.

**Comment by tzfrs** [comment]
A different Listener which uses the `EVENTS::PRE_SERIALIZE` event works as well without problems. So it has to do something with that class.

**Comment by goetas** [comment]
Is it a doctrine proxy?

**Comment by tzfrs** [comment]
It is one in the working `PostSerializationListener`. However, it isn't one in the other `PreSerializationListener` which is working as well. So I have

* Working `PostSerializationListener` where `$event->getObject()` is a proxy
* Working `PreSerializationListener` where `$event->getObject()` is not a proxy
* Non-working `PreSerializationListener` where I don't know why it's not working.

**Comment by tzfrs** [comment]
Could it be a problem that it is a Proxy? I just checked other EventListeners. Everywhere where the object where the `PreSerializationEvent` is not fired, the object is a Proxy. When I call the object directly (no proxy) the Listener gets called

**Comment by goetas** [comment]
If is a proxy, it is a known bug. TherE is also a pr to fix it. HAve a look
it it

**Comment by tzfrs** [comment]
Which PR?

**Comment by goetas** [comment]
I you define explicitly the type using the type annotation, should work

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/677

**Comment by tzfrs** [comment]
Can confirm. With the PR it works.
