### ISSUE TITLE
JMSSerializerBundle 2.0 minimum requirements

### ISSUE THREAD

**Issue by goetas** [schmittjoh/JMSSerializerBundle#561]
In JMSSerializerBundle 2.0 I'm planning to drop support for:

- PHP 5.X versions. This means only 7.x will be supported
- Symfony 2.x version. This means only 3.x (and most probably 4.x) will be supported
- Complete HHVM support drop

HHVM was looking to be a pretty important project, but after PHP7 show up, HHVM faded a bit. It this true or is just my impression? 

see https://github.com/schmittjoh/JMSSerializerBundle/compare/2.0...2.0-min-deps

Any feedback on this decision?

(Backward incompatible changes between 1.x and 2.0 are in [UPGRADING.md](https://github.com/schmittjoh/JMSSerializerBundle/blob/2.0/UPGRADING.md))

**Comment by lbayerl** [comment]
looks fine - but is there any specific usage of PHP 7 functionality? because usually I don't see why 5.6 shouldn't be supported as long it's supported and there's no need to use new language features in the bundle

**Comment by goetas** [comment]
the initial idea was to have a chance to add new features to the serializer using new php7 improvements in the subsequent 2.x releases... 

 but looking at the development in the [serializer 2.0](https://github.com/schmittjoh/serializer/pull/743), i was considering keeping the bundle compatibile with 5.6 at least

Anyway the bundle does really few things, so being compatible with the widest set of php versions might be a good idea

**Comment by goetas** [comment]
decided to stay with the current minimum requirements
