### ISSUE TITLE
 requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by 5-digits** [schmittjoh/JMSSerializerBundle#566]
when i try to install  JMSSerializerBundle related to the FOSRestBundle i get this error
==========
please how to Fix that 👍 

Problem 1
    - The requested package jms/serializer-bundle (locked at 0.13.0, required as ^1.0) is satisfiable by jms/serializer-bundle[0.13.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for jms/serializer dev-master -> satisfiable by jms/serializer[dev-master].
    - jms/serializer dev-master requires php >=5.5.0 -> your PHP version (5.6.25) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.

  Problem 3
    - jms/serializer 1.7.x-dev requires php >=5.5.0 -> your PHP version (5.6.25) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - jms/serializer-bundle 1.4.0 requires php >=5.4.0 -> your PHP version (5.6.25) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - jms/serializer-bundle 1.3.1 requires php >=5.4.0 -> your PHP version (5.6.25) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - jms/serializer-bundle 1.3.0 requires php >=5.4.0 -> your PHP version (5.6.25) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - jms/serializer-bundle 1.2.1 requires php >=5.4.0 -> your PHP version (5.6.25) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - jms/serializer-bundle 1.2.0 requires php >=5.4.0 -> your PHP version (5.6.25) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - jms/serializer-bundle 1.1.0 requires php >=5.4.0 -> your PHP version (5.6.25) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - jms/serializer-bundle 1.0.0 requires jms/serializer ^1.0.0 -> satisfiable by jms/serializer[1.7.x-dev].
    - Installation request for jms/serializer-bundle ^1.0 -> satisfiable by jms/serializer-bundle[1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].

**Comment by goetas** [comment]
please post your composer.json and php version

**Comment by goetas** [comment]
> your PHP version (5.6.25) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.

**Comment by 5-digits** [comment]
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "require": {
        "php": ">=5.3.9",
        "doctrine/doctrine-bundle": "~1.4",
        "doctrine/orm": "^2.4.8",
        "friendsofsymfony/rest-bundle": "^1.8",
        "incenteev/composer-parameter-handler": "~2.0",
        "jms/serializer-bundle": "^1.0",
        "nelmio/api-doc-bundle": "^2.13",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "sonata-project/block-bundle": "^3.3",
        "sonata-project/doctrine-orm-admin-bundle": "^3.1",
        "sonata-project/formatter-bundle": "^3.2",
        "sonata-project/news-bundle": "^3.1",
        "symfony/assetic-bundle": "~2.3",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/swiftmailer-bundle": "~2.3,>=2.3.10",
        "symfony/symfony": "^2.8",
        "twig/twig": "^1.0||^2.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.1",
        "symfony/phpunit-bridge": "~2.7"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "bin-dir": "bin",
        "platform": {
            "php": "5.3.9"
        },
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.8-dev"
        }
    }
}

My php version :: PHP 5.6.25

**Comment by goetas** [comment]
note the `overridden by "config.platform.php"`

**Comment by 5-digits** [comment]
I solve my problem by removing the "platform" tag from composer.json file,  that require  version (5.3.9)
to be like that 
```
    "config": {
        "bin-dir": "bin",
        "sort-packages": true
    },
```
