### ISSUE TITLE
[Question] DeserializedName ?

### ISSUE THREAD

**Issue by Adraesh** [schmittjoh/JMSSerializerBundle#572]
Using the annotations is there a way to specify on each entity property the name of the XML property it should use to deserialize it ? My entity properties don't have the same name as I have in the XML.

I found SerializedName but obviously this works only for serializing and not for deserializing ?

Thanks in advance.

**Comment by goetas** [comment]
if you are using `SerializedNameAnnotationStrategy`,  `SerializedName` works for deserialization too.
