### ISSUE TITLE
Serialize to xml : nested objects in single class

### ISSUE THREAD

**Issue by hiromik** [schmittjoh/JMSSerializerBundle#573]
Would it be possible with a single class "myclass" to serialize a xml output like this ?
My issue is here that I don't wanna create "toto" & "tata" classes just for the sake of serializing even though they're required and that toto doesn't contain anything.

```xml
	<myclass>	
		<context:BOBO>
			<context:toto>
			   <context:Id/>
			</context:toto>
			<context:tata>
			   <context:info>
				  <context:date>2014-02-27+01:00</context:date>
			   </context:info>
			</context:tata>
		 </context:BOBO>
	</myclass>

Thanks for your help.

**Comment by goetas** [comment]
Unfortunately without writing a custom serializer (that will vanify the usage of the serializer, you need  "toto" & "tata" classes
