### ISSUE TITLE
[Question] Is serialize() use adders ?

### ISSUE THREAD

**Issue by Adraesh** [schmittjoh/JMSSerializerBundle#574]
Hello guys,

I don't have any issue, everything is working great. Still I wonder if the serialize() method is using the adders because when I deserialize an object which is related to another via an OneToMany relation everything is going well except that objects from the Many side are not linked to the One side (I have to do it manually by looping through each item) even I specified the set method in my adder:

`private function addSomeObject(Object $object) {// .....   $object->setOther($this);  // ..... }`

Thanks in advance.

**Comment by goetas** [comment]
the serializer uses reflection or setter methods depending on your configurations.

for the "linking sides" of doctrine entities, that is exactly how needs to be done and that is the suggested way by doctrine (http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#owning-and-inverse-side-on-a-manytomany-association)

**Comment by Adraesh** [comment]
Thank you for you answer.

I don't have a ManyToMany but a OneToMany but still the association is well setup in the Many side as pasted in my code above:

`private function addSomeObject(Object $object) {// ..... $object->setOther($this); // ..... }`

It seems that the serializer does not pass into my addSomeObject() method.

**Comment by goetas** [comment]
the serializer by default uses reflaction... so your "adder" method probably is not called at all...

>EDIT: What you said about: "the serializer uses reflection or setter methods depending on your configurations." is very interesting, where I can check this configuration?

[accesstype](http://jmsyst.com/libs/serializer/master/reference/annotations#accesstype) and [accessor](http://jmsyst.com/libs/serializer/master/reference/annotations#accessor) are the options to use of you want your "adders" or "setters" to be called
