### ISSUE TITLE
Not work for Symfony 3.3?

### ISSUE THREAD

**Issue by TonyGao** [schmittjoh/JMSSerializerBundle#579]
composer require jms/serializer-bundle

I got a exception with this command, but It's fine in Symfony 3.2.

Exception below

[Composer\Downloader\TransportException]
  The "https://packagist.org/p/jms/serializer-bundle%2414ca8d00048c46fb729db8062190089544f1ae23ad7250df5fa6f88a6e45b3c9.json" file could not be downloade
  d: failed to open stream: Connection refused

**Comment by goetas** [comment]
>  file could not be downloade d: failed to open stream: Connection refused
connection issues, probably packagist was down for few seconds
