### ISSUE TITLE
Date deserialization (DateTime object)

### ISSUE THREAD

**Issue by bobvandevijver** [schmittjoh/JMSSerializerBundle#582]
I'm having an issue with the deserialization of a DateTime object which only contains a date: the time is set to zero, and is not serialized. I have the following property:

```php
  /**
   * @var DateTime
   *
   * @ORM\Column(name="signin_start", type="date")
   * @JMS\Expose()
   * @JMS\Type("DateTime<'d-m-Y'>")
   * @Assert\NotNull
   * @Assert\Date
   */
  protected $signin_start;
``` 

When I deserialize this, I will get a DateTime object which has the current time set, due to this line ([L184](https://github.com/schmittjoh/serializer/blob/master/src/Handler/DateHandler.php#L184)) in the `DateHandler`:
```
$datetime = \DateTime::createFromFormat($format, (string)$data, $timezone);
```

What would be best practice to resolve this issue? Does adding a timezone work, or should I serialize the complete DateTime class including the zero time, to ensure correct functioning (which adds extra data). Or should we adjust the serializer to set the time to zero when it is not given?

**Comment by goetas** [comment]
Interesting... PHP behaves differently when using the constructor and `createFromFormat`

https://3v4l.org/W7fgD

**Comment by bobvandevijver** [comment]
Right. From the [PHP docs](http://php.net/manual/en/datetime.createfromformat.php):
> If format does not contain the character ! then portions of the generated time which are not specified in format will be set to the current system time.
>If format contains the character !, then portions of the generated time not provided in format, as well as values to the left-hand side of the !, will be set to corresponding values from the Unix epoch. 

So basically, if I set the format to contain the exclamation mark, it should be fixed for my case. Should we do this by default?

**Comment by bobvandevijver** [comment]
Okay, so it works when I use one of those specific characters during deserialization only, but as the type is also used during serialization, it fails with an unrecognized format (as the output becomes `01-06-2017|`). Any suggestions?

**Comment by goetas** [comment]
is not the first time I see this type of problem... basically the root cause is that the dateformat can be different when serializing and when deserializing...

PR with to allow serialization and (optional) deserialization format are welcome! :)

**Comment by bobvandevijver** [comment]
I've been looking into the optional deserialization parameter for the annotation, which should be fairly simple to add when using the existing annotation driver:
```
@JMS\Type("DateTime<'d-m-Y','','|d-m-Y'>")
```
Then you will always need to supply the timezone, when you want to supply the deserialization format. I would like to put instead of the timezone, but yeah, BC-breaking changes 😄 

What is you opinion on adding a new type, specific for deserialization? So the `@DeserializationType` annotation, which is used only during deserialization (if given), with the same behavior as the `@Type` annotation?

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/pull/788
