### ISSUE TITLE
Support for serializing arrays to XML

### ISSUE THREAD

**Issue by Seldaek** [schmittjoh/JMSSerializerBundle#59]
Example of desired output:

Granted that `$game` is an object.

``` php
$data = array(
    'game' => $game,
    'players' => array(
        'Alice',
        'Bob',
    ),
);
```

``` xml
<results>
    <game>
        <id>3</id>
        <name>Foo</name>
    </game>
    <players>
        <entry>Alice</entry>
        <entry>Bob</entry>
    </players>
</results>
```

To name xml elements, distinction between lists (players) and maps (the top-level array) could be done by using `isset($array[0])`, or alternatively `ìs_numeric($key)` on every key to know if it should be called `$key` or `entry`.

**Comment by Wirone** [comment]
Is it possible to serialize array without having object with `@XmlKeyValuePairs` annotation? Just like @Seldaek wrote in first post, if I have raw array and I want serialize it to xml directly, how to achieve it?

**Comment by jeanCarloMachado** [comment]
I'm struggling with the same problem as @Wirone. I need xml tags by array indices, there's some news about this problem? An official way of doing it?

**Comment by goetas** [comment]
see https://github.com/schmittjoh/serializer/pull/868

**Comment by ekonoval** [comment]
sorry, can't see any examples there
