### ISSUE TITLE
Allow event listener/susbcriber services to be private

### ISSUE THREAD

**Issue by weaverryan** [schmittjoh/JMSSerializerBundle#593]
If you use the `jms_serializer.event_listener` or `jms_serializer.event_subscriber` tags, they require the service to be public: https://github.com/schmittjoh/JMSSerializerBundle/blob/067ff257c1e185464314a2c5fab3f908c64fbc10/DependencyInjection/Compiler/RegisterEventListenersAndSubscribersPass.php#L15-L17

That's going to begin to confuse Symfony 3.3 users (in fact, I received a question on KnpU this morning... which is where this issue came from!). The pass should be refactored to allow these to be private. I'm not sure if the custom `EventDispatcher` itself might need some refactoring to support this... a good guide is the core pass from symfony/symfony: https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php

Cheers!

**Comment by goetas** [comment]
See https://github.com/schmittjoh/JMSSerializerBundle/issues/593 

Can you review it?

**Comment by goetas** [comment]
moving conversation to  #593
