### ISSUE TITLE
Gedmo Unrecognized field: createdAt - Error!

### ISSUE THREAD

**Issue by safaksaylam** [schmittjoh/JMSSerializerBundle#599]
Hi,
I use to Gedmo TimestampableEntity. And I didn't serializer object to json. 
HTTP 500 Internal Server Error -  Unrecognized field: createdAt

**User Class Example:**
`class User extends \DPX\AdminBundle\Model\User
{
    use TimestampableEntity, SoftDeleteableEntity;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=255, unique=true)
     */
    protected $username;
`

**Action Example**
`$this->get('jms_serializer')->serialize($user, 'json')`

**Config Yaml added handlers**
`jms_serializer:
    handlers:
        datetime:
            default_format: "c"
            default_timezone: "UTC"`

I added JMS Type DateTime in TimestampableEntity createdAt and updatedAt. But It doesn't work. How can i fixed?

**Comment by goetas** [comment]
please clear  your cache directory

**Comment by safaksaylam** [comment]
I cleared cache. But it doesn't work.

**Comment by goetas** [comment]
can you post the full stack-trace for the exception?

**Comment by safaksaylam** [comment]
I can fixed. Problem is ORM\OrderBy doesn't work with serializer.
