### ISSUE TITLE
Example code for "Changing the Object Constructor" section does not show on the web page.

### ISSUE THREAD

**Issue by rgembalik** [schmittjoh/JMSSerializerBundle#601]
http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration#changing-the-object-constructor
Mentioned section should contain configuration examples mentioned in the source code here:
https://github.com/schmittjoh/JMSSerializerBundle/blob/master/Resources/doc/configuration.rst#changing-the-object-constructor

At the time of writing this section is followed up by the next section which confuses the reader.
![image](https://user-images.githubusercontent.com/2618837/29516643-6b21a3d0-8671-11e7-8ee9-4fe0ff5c001a.png)

**Comment by goetas** [comment]
PR are welcome :)

**Comment by kinow** [comment]
@goetas confirmed in the website that it's now looking OK! So I reckon this issue can also be closed :tada: 

Thanks for reviewing the pull request so quickly!

**Comment by goetas** [comment]
thank to you for taking the time for this improvement
