### ISSUE TITLE
Add symfony/translation to required bundles

### ISSUE THREAD

**Issue by ElectricMaxxx** [schmittjoh/JMSSerializerBundle#606]
As `symfony/framework-bundle` removed `symfony/translation` from versions >= 3.2.0 you should add it to your required packages or work out its usage as optional.
As far as ei know `jms_serializer.form_error_handler' uses the translator.

**Comment by goetas** [comment]
That has been solved with https://github.com/schmittjoh/JMSSerializerBundle/pull/604 and in `maser-dev` is an optional dependency.

I plan to release the new version when symfony 4.0 will be tagged

**Comment by ElectricMaxxx** [comment]
Ok, fine, cool :-) Thanks for the fast answer.
