### ISSUE TITLE
Error You must define a type for 

### ISSUE THREAD

**Issue by speeeeeed2006** [schmittjoh/JMSSerializerBundle#609]
I have tried various things adding Type annotation in entity, adding Yml to specify the type. like I already seen in some issues. 
To make it easy 

```
.....
use JMS\Serializer\Annotation as Serializer;
use JMS\Serializer\Annotation\Type;

class FormulaireSouscription extends FormulaireBase
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id_formulaire", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\SequenceGenerator(sequenceName="formulaire_souscription_id_formulaire_seq", allocationSize=1, initialValue=1)
     */
    protected $idFormulaire;

    /*
     * @Type("string")
     */
    protected $mail;
...
```
I use my entity as a inherited entity because I share it with another application. 
but I still have the error when I use it 
You must define a type for ~SouscriptionBundle\Entity\FormulaireSouscription::$mail`.
```
/**
     * @Route("/formulaire_ajout", name="souscription_formulaire_save")
     * @Method({"POST"})
     */
    public function saveAction(Request $request)
    {
        $data = $request->getContent();
        $formulaire = $this->get('jms_serializer')->deserialize($data, 'SouscriptionBundle\Entity\FormulaireSouscription', 'json');

        dump($formulaire);
        die();
```

**Comment by goetas** [comment]
can you post the stack trace?

**Comment by speeeeeed2006** [comment]
Here is:
INFO - Matched route "souscription_formulaire_save". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "FOS\RestBundle\EventListener\FormatListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "FOS\RestBundle\EventListener\BodyListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Nelmio\ApiDocBundle\EventListener\RequestListener::onKernelRequest". 
DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". 
CRITICAL - Uncaught PHP Exception JMS\Serializer\Exception\RuntimeException: "You must define a type for SouscriptionBundle\Entity\FormulaireSouscription::$mail." at D:\wamp\www\Ekwapi\vendor\jms\serializer\src\JMS\Serializer\GenericDeserializationVisitor.php line 178 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "FOS\RestBundle\EventListener\FormatListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "FOS\RestBundle\EventListener\BodyListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\TranslatorListener::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest". 
DEBUG - Notified event "kernel.request" to listener "Nelmio\ApiDocBundle\EventListener\RequestListener::onKernelRequest". 
DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\HttpCacheListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\SecurityListener::onKernelController". 
DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController". 
INFO - The Twig_Function_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead. 
INFO - The Twig_Function class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFunction instead. 
INFO - Using an instance of "Twig_Function_Method" for function "isDateTime" is deprecated since version 1.21. Use Twig_SimpleFunction instead.

**Comment by speeeeeed2006** [comment]
Sorry it's massive

**Comment by goetas** [comment]
can you make sure your symfony cache is clean?

**Comment by speeeeeed2006** [comment]
Yes I already done that twice.

**Comment by goetas** [comment]
Does `FormulaireBase` contains for some reason a filed named `mail` ?

**Comment by speeeeeed2006** [comment]
yes I have it inside too. I already used Type in FormulaireBase too but noting change.

**Comment by goetas** [comment]
then you have to use `yml` metadata and you need to specify the filed for `FormulaireBase`, not for `FormulaireSouscription`.

**Comment by speeeeeed2006** [comment]
using a directory location in app/Ressources ?

**Comment by goetas** [comment]
yes, check here for directory naming http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration

**Comment by speeeeeed2006** [comment]
I will try
