### ISSUE TITLE
Problem deserialize xml with namespace: xmlns="http://www.w3.org/2000/09/xmldsig#" in tag root

### ISSUE THREAD

**Issue by martinepic** [schmittjoh/JMSSerializerBundle#613]
Hello, I have an xml with namespace: xmlns = "http://www.w3.org/2000/09/xmldsig#" and Unfortunately the jms does not work when trying to deserialize, can someone help me?

Example:

```xml
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
     <TestValue>Hello Jms</TestValue>
</Signature>
```

**Comment by goetas** [comment]
duplicate of https://github.com/schmittjoh/serializer/issues/837
