### ISSUE TITLE
Stopwatch Subscriber not found (SF4)

### ISSUE THREAD

**Issue by juliusstoerrle** [schmittjoh/JMSSerializerBundle#617]
WIth SF4 and FOSRestbundle I'm getting follwoing Error during the dispatch of `pre_serialize`:
in EventDispatcher.php (line 104):
> Warning: call_user_func() expects parameter 1 to be a valid callback, class 'jms_serializer.stopwatch_subscriber' not found

Stacktrace:

> at EventDispatcher->dispatch('serializer.pre_serialize', 'App\\Domain\\Model\\Notification\\Templates\\Template', 'json', object(PreSerializeEvent))in GraphNavigator.php (line 188)
> at GraphNavigator->accept(object(Template), array('name' => 'App\\Domain\\Model\\Notification\\Templates\\Template', 'params' => array()), object(SerializationContext))in JsonSerializationVisitor.php (line 112)
> at JsonSerializationVisitor->visitArray(array(object(Template)), array('name' => 'array', 'params' => array()), object(SerializationContext))in GraphNavigator.php (line 153)
> at GraphNavigator->accept(array(object(Template)), array('name' => 'array', 'params' => array()), object(SerializationContext))in Serializer.php (line 193)
> at Serializer->visit(object(JsonSerializationVisitor), object(SerializationContext), array(object(Template)), 'json', null)in Serializer.php (line 112)

When setting the service to public in the services.xml. i'm getting following exception during cache:clear

> The service "jms_serializer.stopwatch_subscriber" has a dependency on a non-existent service "debug.stopwatch".

I haven't tried anything else yet, but i guess either I'm missing a dependency or there was a change in SF which results in following line not working correctly? 
`if (!$container->getParameter('kernel.debug')) {`
(JMSSerializerExtension:153)

Note: I'm on dev-master (dd40bfc)

**Comment by goetas** [comment]
Which version of the bundle are you using? are you in debug mode or not?

**Comment by juliusstoerrle** [comment]
I'm on dev-master (dd40bfc), with SF4-RC1.
I'm in debug mode

And i just required the stopwatch component, but it did not change anything

**Comment by goetas** [comment]
dd40bfc does not look to be the current master.... the current master is 6c953d1e79a8d67985798939cbeb8db73a3270d4

**Comment by juliusstoerrle** [comment]
Well, that's weird. I ran composer update multiple times and it did not update. I now specified the commit hash and that finally worked. 
My errors are all gone now. Next Time I will check the version more carefully! Thanks @goetas for all your hard work on this bundle and the update to SF4 combatibility!!
