### ISSUE TITLE
Exclude property on serialization, but not on deserialization

### ISSUE THREAD

**Issue by egonolieux** [schmittjoh/JMSSerializerBundle#619]
I have a class which contains an `imageBase64` property. This property is used when creating a new resource in a REST API, but should be excluded during serialization. Is this possible?

**Comment by goetas** [comment]
http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies

**Comment by goetas** [comment]
Ah, you can use the expression language exclusion strategy.

```php
/*
* @Exclude(if="context.getDirection() === 1")
*/
```
more info about it on http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#dynamic-exclusion-strategy

**Comment by egonolieux** [comment]
Ah yes, I already looked at the expression language but found it somewhat confusing. This is exactly what I needed. Thanks!
