### ISSUE TITLE
Move `symfony/stopwatch` to `require` instead of `require-dev`

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/JMSSerializerBundle#624]
It seems that `jms_serializer.stopwatch_subscriber` has a dependency on stopwatch `debug.stopwatch`. If `symfony/stopwatch` is not installed, it will result in:

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "jms_serializer.stopwatch_subscriber" has a dependency on a non-existent service "debug.stopwatch".
```

When I add `symfony/stopwatch` to my composer.json it works. 

How to solve this?

**Comment by edefimov** [comment]
Having the same problem, I think the solution for this should be in `\JMS\SerializerBundle\DependencyInjection\JMSSerializerExtension`:
```php
if (!$container->getParameter('kernel.debug') || !class_exists(Stopwatch::class)) {
    $container->removeDefinition('jms_serializer.stopwatch_subscriber');
}
```

**Comment by ruudk** [comment]
Nice, added a PR to fix it! Thanks for the hint :)
