### ISSUE TITLE
Subscribing Handler not used (FOSRestBundle: ExceptionHandler)

### ISSUE THREAD

**Issue by juliusstoerrle** [schmittjoh/JMSSerializerBundle#626]
Hey,
since upgrading I do get the "Resources not allowed in seralized data" error. This happens to me when serializing an exception via the ExceptionController in the FOSRestBundle. The Bundle registers a Handler for the `\Exception` Class which formats the exception and throws out all the resources... 

The Handler registers as:
           `[
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format' => 'json',
                'type' => \Exception::class,
                'method' => 'serializeToJson',
            ]`

ExceptionHandler::getSubscribingMethods() is actually being called and the handler gets registered but not called during serialization.
I actually also had problems with my very own handlers when setting the type in the handler to `\SomeObject::class`. Somehow it did not use the Handler then so I'm using strings there and configure the properties with Annotations, but that not possible here.

**Comment by goetas** [comment]
Are you using a "custom" exception ? (that maybe has a property of type `resource`) ?

**Comment by kbkk** [comment]
Confirmed. With sf4 and jms bundle ^2.3 I get the serialization error with Doctrine exceptions (which didn't happen before).
Simple test case:
```php
        $serializer = \JMS\Serializer\SerializerBuilder::create()->build();
        $ex = new \Doctrine\DBAL\Exception\UniqueConstraintViolationException(
            '',
            new \Doctrine\DBAL\Driver\Mysqli\MysqliException('', null)
        );
        $serializer->serialize($ex, 'json');
```

**Comment by goetas** [comment]
if the exception contains a resource, you have to take care of serializing (or excluding) it

**Comment by kbkk** [comment]
My point is the test case above works in a sf3.3 project with jms bundle ^2.2 without any additional configuration. Would you care to explain how to achieve this with jms ^2.3?

**Comment by goetas** [comment]
Can it be that some other library got updated?

**Comment by kbkk** [comment]
I am sorry for the trouble, the test case is wrong. I think it is an issue with FOS Rest Bundle. Seems like in the working project it falls back to Symfony Serializer but not in the new one. I should start an issue on FOS Rest Bundle..

**Comment by juliusstoerrle** [comment]
Hey, I had started an Issue over there already about this topic. The reason why I opened this Issue here is because the Handler from the Rest Bundle seems to  be registered correctly.

**Comment by juliusstoerrle** [comment]
@goetas Sorry for not responding to:

> Are you using a "custom" exception ? (that maybe has a property of type resource) ?

Yes the exception has a property of that type (its not a custom exception, but one from the sf framework), but the Serialization Handler is supposed to remove that.

**Comment by goetas** [comment]
"Serialization Handler"  ? which one?

**Comment by juliusstoerrle** [comment]
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Serializer/Normalizer/ExceptionHandler.php

**Comment by juliusstoerrle** [comment]
Well my bad, when changing from SF4 Rcs to the 4.0 release I also changed the fos/rest version which resulted in not pulling some changes from an open pull request @xabbuh made. I changed that back and now it seems to work fine (hope it stays like that).
