### ISSUE TITLE
Tag v2.3.1

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/JMSSerializerBundle#627]
Could you please tag a new patch so that stopwatch issue is resolved?

https://github.com/SimpleBus/RabbitMQBundleBridge/pull/35 is failing, and we have to require the stopwatch to let it pass, 

Muchas gracias 🙌

**Comment by goetas** [comment]
done https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/2.3.1

**Comment by ruudk** [comment]
Thanks 🙌
