### ISSUE TITLE
Symfony 3.4 - jms_serializer.json_deserialization_visitor service is private

### ISSUE THREAD

**Issue by bgarel** [schmittjoh/JMSSerializerBundle#632]
In Symfony 3.4, when using json deserialization, I have the deprecation warning :
The "jms_serializer.json_deserialization_visitor" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

Example :
```
$serializer = $this->getContainer()->get('jms_serializer');
$pro = $serializer->deserialize($json, Pro::class, 'json');
```
 My phpunit tests return exit code 1 because of  the warning.
Is there a way not to have this warning ?

Regards,

**Comment by goetas** [comment]
solved by https://github.com/schmittjoh/JMSSerializerBundle/pull/635
