### ISSUE TITLE
Problem with version 1.2.0 and library JMS\Serializer

### ISSUE THREAD

**Issue by janczer** [schmittjoh/JMSSerializerBundle#636]
> Catchable Fatal Error: Argument 2 passed to JMS\Serializer\AbstractVisitor::__construct() must implement interface JMS\Serializer\Accessor\AccessorStrategyInterface, instance of JMS\Serializer\Construction\UnserializeObjectConstructor given, called in /app/cache/dev/appDevDebugProjectContainer.php on line 6082 and defined

I found in `vendor/jms/serializer-bundle/JMS/SerializerBundle/Resources/config/services.xml`, that object `jms_serializer.object_constructor` should be instance of: `JMS/Serializer/Accessor/AccessorStrategyInterface.php`

```
<service id="jms_serializer.json_deserialization_visitor" class="%jms_serializer.json_deserialization_visitor.class%">
    <argument type="service" id="jms_serializer.naming_strategy" />
    <argument type="service" id="jms_serializer.object_constructor" />
    <tag name="jms_serializer.deserialization_visitor" format="json" />
</service>
```

**Comment by goetas** [comment]
Please update the JMSSerializerBundle to the latest 1.x or 2.x

**Comment by janczer** [comment]
Thank you for response, work with 2.3.0
