### ISSUE TITLE
Unable to override default handlers in Symfony 4

### ISSUE THREAD

**Issue by adiq** [schmittjoh/JMSSerializerBundle#642]
I am reopening issue #519, because it is valid again in Symfony 4. Bundled `jms_serializer.constraint_violation_handler` is always overriding custom defined handlers for e.g. `Symfony\Component\Validator\ConstraintViolationList`.

Mentioned workaround (changing bundles loading order) could not be applied to S4. Currently, the only option to get it working is to override the whole service `jms_serializer.constraint_violation_handler` by defining it with the same name.

**Comment by goetas** [comment]
How are you registering your custom validator?
Suggested way is a compiler pass, yo can set also a priority (see https://symfony.com/blog/new-in-symfony-3-2-compiler-passes-improvements)

**Comment by adiq** [comment]
Could you spare a moment to give some example of custom validators registering in a specific order?
I am not sure if it's a proper solution or I just didn't understand that concept.

I also looked into service decoration to add some custom serialization, but without results.

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/JMSSerializerBundle/pull/645
