### ISSUE TITLE
Serializer ignores criteria query

### ISSUE THREAD

**Issue by aliemre** [schmittjoh/JMSSerializerBundle#643]
Hi.

I have an rest API. My results are serialized by JMSSerializer. Mostly, the serialize processed after entity manager's results. It works as I wish, but on a entity, I apply doctrine criteria to the result. After that serializer ignores the criteria and returns all results. 

Here's an example. I would like to get serialized only visible posts. When I request to the API, it returns all posts in section resource. If I do the same process on the controller with entity manager, it returns filtered results as I wish.

**Endpoint:** `/api/v1/section/1`

**Section.php (Entity)**

```php
    /**
     * Get posts
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPosts()
    {
        $criteria = Criteria::create()->where(Criteria::expr()->eq('visible', true));
        return $this->posts->matching($criteria);
    }
```
**Results:**
```json
{
    "section": {
        "id": 1,
        "name": "Favourite Weekly Restaurants",
        "posts": [
             // all posts.
        ]
    }
}
```

**Comment by goetas** [comment]
can you please share your annotations or yaml/xml metadata mappings?

**Comment by aliemre** [comment]
Hi @goetas 

Here's my mappings as Yaml.

https://gist.github.com/aliemre/962dcf23f6e38980e0e098e272188ebb

**Comment by goetas** [comment]
the mappings you shared are the doctrine mappings, not the jms serializer mappings

**Comment by aliemre** [comment]
@goetas I did not get what you said as jms serializer mappings. I did not use any mapping related to jms serializer. I think it maps whole class in my situation and I restrict several data members with annotations such as @Serializer/Exclude(). Could you give me more detail about the mappings? or maybe I am doing wrong from the beginning.

I created a simple JsonManager to get serializer less complicated. I attached json manager and related controller example.

Thanks.

**Comment by goetas** [comment]
In order for the serializer to use your method `getPosts()` you have to tell it to the serializer. To do so you have or to use the `@VirtualProperty` annotation or to use YAML or XML jms-serializer mapping files.

More info about it on https://jmsyst.com/libs/serializer/master/reference/annotations#virtualproperty and  https://jmsyst.com/libs/serializer/master/reference/xml_reference and https://jmsyst.com/libs/serializer/master/reference/yml_reference

**Comment by aliemre** [comment]
Thanks for the detailed explanation. It works with @VirtualProperty

**Comment by aliemre** [comment]
Hi.

I understand how **VirtualProperty** works. However, I have encountered another issue after that. After adding VirtualProperty annotation, I have to exclude **$posts** data member from class. Otherwise, the serializer serialize association through the data member and API returns unfiltered results. As a result after excluding the data member, I get the error:

**Error: Call to a member function matching() on null**

My Case:

**Section.php (Entity)**

```php
    
    /**
     * @var \Doctrine\Common\Collections\Collection
     * @Serializer\Exclude()
     */
    private $posts;

    /**
     * Get posts
     *
     * @return \Doctrine\Common\Collections\Collection
     * @Serializer\VirtualProperty()
     */
    public function getPosts()
    {
        $criteria = Criteria::create()->where(Criteria::expr()->eq('visible', true));
        return $this->posts->matching($criteria);
    }
```

**Comment by goetas** [comment]
Do not forget to initialize `$this->posts` in your constructor with `$this->posts = new ArrayCollection()`
