### ISSUE TITLE
JMS Serializer add groups by some condition

### ISSUE THREAD

**Issue by shubaivan** [schmittjoh/JMSSerializerBundle#646]
I have entity `Notification` and when my entity contain some condition I want add additional groups for serializer, I create event `serializer.pre_serialize` for `Notification` and after check condition add additional groups in serialized context, but in response it's not works. Example I want add some nested to my `Notification` it would be some another Entity, example `Question` and this entity have some groups, and after set it when I create context `SerializationContext::create()` everything work, but when I try add additional group in `serializer.pre_serialize` it's not work

this my entity

    class Notifications
    {
    use TraitTimestampable;

    const GROUP_POST_NOTIFICATION = 'post_notifications';
    const GROUP_GET_NOTIFICATIONS = 'get_notifications';

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Annotation\Groups({
     *     "get_notifications"
     * })
     */
    private $id;

    /**
     * @var object
     *
     * @Annotation\Groups({
     *     "get_notifications"
     * })
     */
    private $providerEntity;

and another entity which I adding in event

    class Questions implements NotificationInterface
    {
    use TraitTimestampable;
    const GROUP_POST = 'post_question';
    const GROUP_GET = 'get_question';

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Annotation\Groups({
     *     "get_question"
     * })
     */
    private $id;

        /**
     * @return array
     */
    public static function getGetGroup()
    {
        return [self::GROUP_GET];
    }

but in response I have 

    public function onPreSerializeNotifications(PreSerializeEvent $event) 
    {
        /** @var Notifications $notifications*/
        $notifications = $event->getObject();
        $provider = $notifications->getProvider(); //this is Questions::class
        $this->providerEntity = $this->entityManager->getRepository($provider)
            ->findOneBy(['id' => $notifications->getProviderId()]);
        $notifications->setProviderEntity($this->providerEntity);

        $attr = $event->getContext()->attributes;
        $groups = array_merge($attr->all()['groups'], $provider::getGetGroup());
        $attr->set('groups', $groups);
    }

but in response I have

    "notifications": [
       {
          "id": 2,
          "provider_entity": {}
       }
    ]
why ?

**Comment by goetas** [comment]
You can not edit the context once the serialization is started. The context should be immutable. In 2.x `$attr->set` will be removed (to avoid confusion as you are facing)

**Comment by shubaivan** [comment]
ok, if I correct understand I don't have opportunity add additional group by some condition ?
