### ISSUE TITLE
Without CDATA and without escaping

### ISSUE THREAD

**Issue by patie** [schmittjoh/JMSSerializerBundle#649]
Hi its possible serialize data into xml without cdata tag and without escaping? In XmlValue for example. I need unescaped html in xml value without cdata tag. I know its not valid, but reality is sometimes not ideal :) 

thanks for any answer!

**Comment by goetas** [comment]
Not really. Suggest in this case to use a custom handler and use the
domfragment features to generate xml dom starting from a string
