### ISSUE TITLE
Adding incrementing counter to each item in collection

### ISSUE THREAD

**Issue by aschwin** [schmittjoh/JMSSerializerBundle#653]
Hi,

I think it is possible, but I'm not sure how to achieve this:

For each item in a collection, add another "obj_id" to the item that is incremented for that collection.

So, next to the id from the database, I want to have an index of the item in that fetched collection. I thought to serialize it on the fly, instead of adjusting 60+ repositories with the same functionality.

Any idea?

**Comment by goetas** [comment]
In this case event_listeners (http://jmsyst.com/libs/serializer/master/event_system), or virtual properties (http://jmsyst.com/libs/serializer/master/reference/annotations#virtualproperty) might help you.
