### ISSUE TITLE
Given object is not an instance of the class this property was declared in

### ISSUE THREAD

**Issue by BentCoder** [schmittjoh/JMSSerializerBundle#667]
I am getting error message below for given model mapping.

> {
    "message": "Given object is not an instance of the class this property was declared in",
    "code": 0
}

This is how I serialise the model object.

        $context = new SerializationContext();
        $context->setSerializeNull(true);

        $message = $this->serializer->serialize($recordObject, 'json', $context);

If I take out `@Serializer\Type("AppBundle\Model\Video\Price")` bit serialiser works. Any reason why I would get this error message?

I am using V2.3.1

Thanks

**Record**
```

declare(strict_types=1);

namespace AppBundle\Model\Video;

use JMS\Serializer\Annotation as Serializer;

class Record
{
    /**
     * @var string
     * @Serializer\Type("string")
     */
    public $reference;

    /**
     * @var Price
     * @Serializer\Type("AppBundle\Model\Video\Price")
     */
    public $price;

    /**
     * @var array
     * @Serializer\Type("array<string>")
     */
    public $images;
}

```

**Price**

```
declare(strict_types=1);

namespace AppBundle\Model\Video;

use JMS\Serializer\Annotation as Serializer;

class Price
{
    /**
     * @var int
     * @Serializer\Type("int")
     */
    public $min;

    /**
     * @var int
     * @Serializer\Type("int")
     */
    public $max;
}
```

**Comment by goetas** [comment]
did you check https://github.com/doctrine/doctrine2/issues/6360 ?

**Comment by BentCoder** [comment]
I've seen it but it seems a bit different. My classes don't extent any other classes nor dependent on anything else.

**Comment by goetas** [comment]
which serializer lib are you using? your cache was clear I guess, right?

**Comment by goetas** [comment]
it looks a problem with the reflection access strategy

**Comment by BentCoder** [comment]
Yes cache is clear. What do you mean by "which serializer lib are you using?"? I've been using JMS for long time but I've never seen this happening before.

**Comment by goetas** [comment]
Jms is composed by the serializer bundle and the serializer library. Each of it has its own version

**Comment by BentCoder** [comment]
Was it meant to solve issue?

**Comment by goetas** [comment]
knowing the versions of the libraries you are using is a fundamental step to be able to help you

**Comment by BentCoder** [comment]
jms/serializer: 1.12.1
jms/serializer-bundle: 2.4.2

**Comment by rela589n** [comment]
@bentcoder , why did you close this issue? Have you found the root cause of it?

**Comment by rivuletJitendra** [comment]
@bentcoder, found any solution for the above issue?
