### ISSUE TITLE
Symfony jms serializer enable when needed

### ISSUE THREAD

**Issue by shubaivan** [schmittjoh/JMSSerializerBundle#678]
I have jms serializer and in my class entity have annotation. I have case when I need apply jms serializer annotation only in some case. How to do this ? First I think need move annotation from entity class to yml maybe and create some handler where I can enable this annotation for this entity, in the rest of the time jms are not applicable to entity

my entity

    /**
     * @Annotation\ExclusionPolicy("all")
     */
    class Application implements ContainsRecordedMessages
    {
    /**
     * @var int
     *
     * @Annotation\Groups({
     *      "get_application"
     * })
     * @Annotation\Expose()
     */
    private $id;

    /**
     * @var int
     *
     * @Annotation\Groups({
     *      "post_application"
     * })
     * @Annotation\SerializedName("company_id")
     * @Annotation\Expose()
     */
    private $companyId;

    /**
     * @var string
     *
     * @Annotation\Groups({
     *      "post_application"
     * })
     * @Annotation\SerializedName("channel_sale")
     * @Annotation\Expose()
     */
    private $channelSale;

and I have class manager for this entity where I want enable jms and the disable jms serializer annotation

    class ApplicationManager
    {
    public function someFunction()
    {
        $this->enableJmsForEntity(Application::class);
        //some logic
        //
        $this->disableJmsForEntity(Application::class);     
    }
    }

**Comment by goetas** [comment]
I suggest you to use YAML/XML metadata. The case you have described is one of the drawbacks of using annotations (they are convenient in many cases but not in your of you have that specific need)

**Comment by goetas** [comment]
But reading better your question, I'm not sure if you want to disable all jms annotations or only a specific one.
