### ISSUE TITLE
Wrong boolean deserialization

### ISSUE THREAD

**Issue by peterprochaska** [schmittjoh/JMSSerializerBundle#684]
I use FosRestBundle together with JMS Serializer.

I have the following property in my Entity:

```
/**
* @var string $ecoOption
* @Serializer\Type("boolean")
* @Assert\NotBlank(payload={"error_code"="ERR_ECO_OPTION_EMPTY"})
*/
protected $ecoOption;

```

If i send "ecoOption" : true, everything is ok. But if i send "ecoOption" : false, the error ERR_ECO_OPTION_EMPTY appears.

Where is my error?

EDIT: I use this Entity together with the Symfony ParamConverter.

**Comment by goetas** [comment]
From what I know, notblank is a string type constraint and should not be
used on booleans. Maybe you want the not null?

**Comment by peterprochaska** [comment]
NotNull is a workaround, but actually i need NotBoolean, because it should only be true or false

**Comment by goetas** [comment]
If you typehint the setter to ensure booleans, will work.
Do not confuse normalization and validation,  suggested reading
https://www.goetas.com/blog/deserialization-normalization-validation-and-the-jms-serializer/

**Comment by goetas** [comment]
The validation rules you define should work for the type of the property
you have (in this case boolean). Avoiding to have strings there is a
different responsibility.
