### ISSUE TITLE
XML substitutionGroup support

### ISSUE THREAD

**Issue by pakomp** [schmittjoh/JMSSerializerBundle#685]
Hi,
I was wondering if there was any support for the substitutionGroup attribute in XML ([W3C](https://www.w3schools.com/xml/schema_complex_subst.asp)), can't seem to find any documentation mentioning it.

Or if anyone has a good workaround for handling a XML schema using it.

**Comment by goetas** [comment]
jms serialzer is not aware of XSD and is out of scope for this library.

XSD is a set of rules to define types in XML.
