### ISSUE TITLE
Metadata definition only in last class hiearchy.

### ISSUE THREAD

**Issue by mvrhov** [schmittjoh/JMSSerializerBundle#69]
Is there a way that you can override or define metadata only for the last class in hierarchy and that would be the rules you'd want the specific object to be serialized by.

The excellent example of where this would come in handy is when you are extending a user model from FOSUB and would like to exclude some properties from being serialized. The bundle doesn't ship with any serialization metadata and even if it would each user could have different expectations of what should and should not be serialized.

This would require some sort of merging all metadata in proper hierarchy.

**Comment by numesmat** [comment]
The problem with this solution (overriding third-party bundle metadata) is that it can be done only on the application level (on the serializer instance level, to be precise, but we do not want to have multiple serializer instances in one application, right?). But what if two different bundles need to have different behavior?

For example lets assume that we have some class *Basic* in some *BundleA*:
```php
abstract class Basic {
    public $id;
}
```

And we have two other bundles that depends on the first one and have to entities:
```php
class EntityFromBundleA extends Basic { ... }

class EntityFromBundleB extends Basic { ... }
```

And now suppose that BundleA needs to expose id property and BundleB needs to exclude it. And how one can achieve it without being able to override metadata on per-entity basis?
