### ISSUE TITLE
Lazy services - Final classes cannot be proxied by ProxyManager

### ISSUE THREAD

**Issue by vhejda** [schmittjoh/JMSSerializerBundle#690]
I am testing the 3.0.0@RC in a Symfony 3.4 project, and after installing, I am getting:

```
PHP Fatal error:  Uncaught ProxyManager\Exception\InvalidProxiedClassException: 
Provided class "JMS\Serializer\Handler\FormErrorHandler" is final and cannot be proxied
```
It is coming from `ocramius/proxy-manager`, as the FormErrorHandler is a final class and the service is registered as `lazy="true"`. `ocramius/proxy-manager` is a dev-dependency of `symfony/symfony`, so I suppose I will not be the only affected person.

Related issue on Symfony/Symfony suggest dropping the `final` keyword:
https://github.com/symfony/symfony/issues/20392

This might be fixing the problem, but looks like it's only merged to Symfony 4.x:
https://github.com/symfony/symfony/pull/27697

I'd be happy to give a hand here, but not sure what the solution in here should be. Dropping the `final` on the affected classes in `jms/serializer`, or dropping the `lazy=true` here in bundle? Or something else?

Thanks for looking into this!

**Comment by goetas** [comment]
My preferred solution here is to remove lazy=true from the handlers.
But I'm curious about the performance difference...

**Comment by goetas** [comment]
Curious to know if is worth keeping the final keyword in the classes...


The reason for adding the final keyword is that many devs were extending handlers and re implementating 100% of them. More than once inherentance introduced problems that without will not arise
