### ISSUE TITLE
Provided class "JMS\Serializer\Handler\ArrayCollectionHandler" is final and cannot be proxied

### ISSUE THREAD

**Issue by ankahla** [schmittjoh/JMSSerializerBundle#692]
Hi,
I am using 3.0.0-beta1 because I want to use jms/serializer 2.0.

But I am getting this error: Provided class "JMS\Serializer\Handler\ArrayCollectionHandler" is final and cannot be proxied.
When class is final you can't define the property lazy=true in the services.xml
So I am obliged to redefine jms services in my application as lazy=false.

I thing this is a bug.

**Comment by goetas** [comment]
it has been fixed yesterday with https://github.com/schmittjoh/JMSSerializerBundle/pull/691

to try it, just put in your compose

```
"jms/serializer-bundle": "^3.0@dev"

**Comment by goetas** [comment]
Thanks for trying jms/serializer 2.0 :)
