### ISSUE TITLE
It doesn't encode french accents ? 

### ISSUE THREAD

**Issue by Jacksons69** [schmittjoh/JMSSerializerBundle#697]
Hello,

Does this bundle support french accents like "é", "è", "à", etc.. Because for example, for the word "Planète", with JMSSerializer I get "plan\u00e8te" :(

I'm working on Symfony 4, someone else has this encoding problem ? Thx !

**Comment by goetas** [comment]
`\u00e8`  is the unicode equivalent of `é`, so the result is correct.

More info on JSON escaping on https://stackoverflow.com/questions/4901133/json-and-escaping-characters
