### ISSUE TITLE
Unrecognized option "xml" under "jms_serializer.visitors"

### ISSUE THREAD

**Issue by matias-pizarro** [schmittjoh/JMSSerializerBundle#698]
Hi,

I just created a Symfony Skeleton project and when I installed JMSSerializerBundle it gives me the error **Unrecognized option "xml" under "jms_serializer.visitors"**.

I ran the following commands:
- `composer create-project symfony/skeleton test`
- `cd test`
- `composer require jms/serializer-bundle` -> Here is the error

I tried then installing the Symfony serializer first but that way the error is thrown too.

**Comment by isakrubin** [comment]
Same issue

            "name": "jms/serializer",
            "version": "2.0.0",

**Comment by goetas** [comment]
This is a issue of the jms recipe for smfony flex

**Comment by puissanceweb** [comment]
on wamp with php 7.24 / and unders  versions
same issue with website-skeleton (SF4)  means all defaults bundle
composer create-project symfony/website-skeleton mysite
cd mysite
composer require jms/serializer-bundle

Error 
Unrecognized option "xml" under "jms_serializer.visitors"

**Comment by ahmadmayahi** [comment]
Same issue here.
Any suggestions?

**Comment by goetas** [comment]
Here a PR to fix it https://github.com/symfony/recipes-contrib/pull/559

**Comment by goetas** [comment]
https://github.com/symfony/recipes-contrib/pull/559 was merged

**Comment by PurushothamanKrishnamoorthy** [comment]
Hi @goetas ,

Issue is still reproducible in Symfony version 4.2, which has been recently released.  
Error log: 

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 331:
!!                                                                                 
!!    Unrecognized option "xml_serialization" under "jms_serializer.visitors". Av  
!!    ailable options are "json", "xml".                                           
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

**Comment by PurushothamanKrishnamoorthy** [comment]
@goetas  Thanks for quick reply.

Please find https://pastebin.com/d02Kh7cc

While updating/installing composer, manifest.json was not available

**Comment by goetas** [comment]
Which version of the jms serializer bundle do you have installed?

**Comment by PurushothamanKrishnamoorthy** [comment]
Jms/serializer-bundle": "^3.0
Symofny version 4.2
PHP version 7.2

**Comment by goetas** [comment]
@PurushothamanKrishnamoorthy the error you are reporting is different from the initial one in this issue.
From the error message, it look that you are using v3.x configs  with a v2.x bundle

**Comment by goetas** [comment]
@matias-pizarro is your issue solved?

**Comment by PurushothamanKrishnamoorthy** [comment]
@goetas  I have tried to install to jms/serializer-bundle 3.0 in symfony 4.1 but  I'm still getting the same error.  I have used below command to install jms_serializer . Issues happens only with 3.0 and it works fine for version 2.4
`composer require jms/serializer-bundle`


>  it look that you are using v3.x configs with a v2.x bundle - 

I have used fresh install jms serializer bundle of version 3.0. Could you please let me know, what I'm doing wrong here.

**Comment by goetas** [comment]
can you run `composer info` and post the output?

**Comment by PurushothamanKrishnamoorthy** [comment]
composer info: https://pastebin.com/FAnRysmx
composer json snippet:  
`"require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "friendsofsymfony/rest-bundle": "^2.4",
        "jms/serializer-bundle": "^3.0",
        "symfony/console": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.1",
        "symfony/lts": "^4@dev",
        "symfony/yaml": "^4.1"
    },`

**Comment by PurushothamanKrishnamoorthy** [comment]
@goetas  any updates for the issue.

**Comment by goetas** [comment]
@PurushothamanKrishnamoorthy 

Running on php 7.2

```sh
composer create-project symfony/skeleton test
cd test
composer require jms/serializer-bundle
bin/console cache:clear
```

No errors.

If you have a different issue, please open a new ticket and explain how to reproduce it
