### ISSUE TITLE
symfony4 with jms serializer is not working

### ISSUE THREAD

**Issue by elangovanshanthi** [schmittjoh/JMSSerializerBundle#700]
```
use JMS\Serializer\Annotation\Since;
use JMS\Serializer\Annotation\Until;
use JMS\Serializer\Annotation\ExclusionPolicy;

/**
 * @Version("v1")
 * @NamePrefix("v1")
 * @ExclusionPolicy("all")
 */
class ShareController extends FOSRestController
{
    /**
     * 
     * @Since("2")
    */
    
    public function getTestAction()
    {
        return new Response("Test1 Version Started...!");
    }
}
```
I have referred this page `http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#versioning-objects` . Based on this @until @Since annonations versioning is not working in symfony4.

**Comment by goetas** [comment]
JMS annotations have to be applied to your domain objects, not to controllers

**Comment by goetas** [comment]
Can you post a full example?

**Comment by elangovanshanthi** [comment]
```
**Routes.yaml**

guest_api:
    path:  /{version}/api/guesttest
    controller: App\Controller\TestController::test1
    #condition:  "request.attributes.get('version') == 'v1'"
    requirements: 
        version: 'v1|v2'
```

```
**TestController.php**

use FOS\RestBundle\Controller\Annotations\Version;
use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\Controller\Annotations\Route;
use FOS\RestBundle\View\View;
use FOS\RestBundle\Controller\Annotations\Get;
use FOS\RestBundle\Controller\Annotations\NamePrefix;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\HttpFoundation\JsonResponse;

use JMS\Serializer\Annotation\Since;
use JMS\Serializer\Annotation\Until;
use JMS\Serializer\Annotation\ExclusionPolicy;

/**
 * @Version("v1")
 * @NamePrefix("v1")
 * @ExclusionPolicy("all")
 */
class ShareController extends FOSRestController
{
    /**
     * 
     * @Until("v1")
    */
    
    public function getTestAction()
    {
        return new Response("Test1 Version Started...!");
    }
   
   /**
     *@Since("v2")
    */
    public function test2() 
    {
        echo "testing===> Block";
        exit;
    }

}

```
```
**jms_serializer.yaml** 

jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true 
```

My case : 

 When we accessing  the **http://127.0.0.1:8002/v1/api/guesttest** , that time if version1 means **test1()** method will call other wise **test2()** method will call. 

Note : I have tried this jms verioning example http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#versioning-objects .

can you provide some working example of symfony4 with jms versioning ?
Thanks goetas.

**Comment by goetas** [comment]
As said in my previous comment:

JMS annotations have to be applied to your **domain objects**, not to controllers, 

you are applying is still to controllers

**Comment by elangovanshanthi** [comment]
ok i will remove the  * @ExclusionPolicy("all") and now itself it is not working...

**Comment by elangovanshanthi** [comment]
can you share the small example of jms api versioning example? it will help to solve my issue. In docs also no example of api versioning...

**Comment by elangovanshanthi** [comment]
@goetas  Jms seriliser will support api versioning?? If yes means could you please share some example or else provide some examples. It will helpful to resolve my issues. 
Thanks.

**Comment by goetas** [comment]
What you are trying to do is not about jms serializer but fos rest.

https://symfony.com/doc/master/bundles/FOSRestBundle/versioning.html#how-to-match-a-specific-version-in-my-routing is the tutorial. 
Pay attention to the route condition using expression language, i guess that is what you need

**Comment by elangovanshanthi** [comment]
yes, inthe above links, they are mentioned 

```
**Use the JMSSerializer with the API versioning¶**
You should have tagged your entities with version information (@Since, @Until ...)
See this JMS Serializer article for details about versioning objects.
That's it, it should work now.
```
I want to achieve this one ? 
**https://symfony.com/doc/master/bundles/FOSRestBundle/versioning.html#use-the-jmsserializer-with-the-api-versioning**

I have tried this one also - http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#versioning-objects 

--
Thanks for quick reply

**Comment by goetas** [comment]
From your examples, it looks you are trying to call different controller
actions based on the version, and this is fos rest responsability.
While if you need to add remove fields from your responses, that is jms
responsability.

Which one do you need?
