### ISSUE TITLE
Symfony 4.2 deprecation: A tree builder without a root node is deprecated

### ISSUE THREAD

**Issue by shuhao-kibo** [schmittjoh/JMSSerializerBundle#707]
Similar to the error reported at https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/593

Error message is "A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0."

It happens here:
https://github.com/schmittjoh/JMSSerializerBundle/blob/master/DependencyInjection/Configuration.php#L25

**Comment by goetas** [comment]
solved in https://github.com/schmittjoh/JMSSerializerBundle/pull/705
