### ISSUE TITLE
Declaration must be compatible

### ISSUE THREAD

**Issue by ThomasTr** [schmittjoh/JMSSerializerBundle#708]
Hi,

get this error after upgrade to latest version:

> Compile Error: Declaration of JMS\Serializer\XmlSerializationVisitor::startVisitingObject(JMS\Serializer\Metadata\ClassMetadata $metadata, JMS\Serializer\object $data, array $type): void must be compatible with JMS\Serializer\Visitor\SerializationVisitorInterface::startVisitingObject(JMS\Serializer\Metadata\ClassMetadata $metadata, JMS\Serializer\Visitor\object $data, array $type): void

Stacktrace
```
  at vendor/jms/serializer/src/XmlSerializationVisitor.php:18
  at vendor/symfony/debug/DebugClassLoader.php:151
  at Symfony\Component\Debug\DebugClassLoader->loadClass()
     (vendor/jms/serializer/src/Visitor/Factory/XmlSerializationVisitorFactory.php:42)
  at spl_autoload_call()
     (vendor/jms/serializer/src/Visitor/Factory/XmlSerializationVisitorFactory.php:42)
  at JMS\Serializer\Visitor\Factory\XmlSerializationVisitorFactory->getVisitor()
     (vendor/jms/serializer/src/Serializer.php:145)
  at JMS\Serializer\Serializer->getVisitor()
     (vendor/jms/serializer/src/Serializer.php:157)
  at JMS\Serializer\Serializer->serialize()
     (src/Controller/ExportController.php:58)
  at App\Controller\ExportController->exportServiceReportAction()
     (vendor/symfony/http-kernel/HttpKernel.php:150)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:67)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:34)
  at {main}()
     (public/index.php:0)
```

The Part in the exportServiceReportAction()
```
        $xml = $serializer->serialize($rma, 'xml', SerializationContext::create()->setGroups(['exportServiceReport']));
```

Installed versions:
jms/serializer                      2.0.2
jms/serializer-bundle         3.0.1

**Comment by goetas** [comment]
which PHP version are you running?

**Comment by goetas** [comment]
It looks you are running php < 7.2

**Comment by ThomasTr** [comment]
Hi, thank you for your hint. Have multiple php versions installed an this project was running on 7.1.8.
Switched to 7.2 and it works fine.

You can close this issue.

**Comment by goetas** [comment]
:+1:

**Comment by LesovoyRoman** [comment]
👍

**Comment by MustaphaGhlissi** [comment]
Solution is to update you PHP to the version required by JMS
