### ISSUE TITLE
why there is backslash ?

### ISSUE THREAD

**Issue by PauchardThomas** [schmittjoh/JMSSerializerBundle#709]
S3.4
jms dev-master, 3.0.x-dev

Hello,

I would like to know why when I add groups,  my response has backslashs  like
 `"{\"items\":[{\"id\":100,\"content\":\" Hello !!\",\"created_on\":\"2018-12-11T15:57:12+01:00\",\"attribute\":true},{\"id\":101,\"content\":\"Test\",\"created_on\":\"2018-12-12T09:15:35+01:00\",\"attribute\":false}]}"`

instead of 

`"{"items":[{"id":100,"content":" Hello !!","created_on":"2018-12-11T15:57:12+01:00","attribute":true},{"id":101,"content":"Test","created_on":"2018-12-12T09:15:35+01:00","attribute":false}]}"`

Is there a way to remove them ?

Btw, when I get the reponse with newtonsoft json (c# library) I get triple backslashs which is pretty weird.

thank you.

**Comment by goetas** [comment]
well, it depends how do you output the json...

**Comment by PauchardThomas** [comment]
Sorry what do you mean ?

**Comment by PauchardThomas** [comment]
I finaly found whats wrong. In my api rest I replace :

```
return $this->get('jms_serializer')->serialize($message, 'json',
            SerializationContext::create()->setGroups(array(
                'detail_discussion'
            )));
```

By : 

```
        $data = $this->get('jms_serializer')->serialize($message, 'json',
            SerializationContext::create()->setGroups(array(
                'detail_discussion'
            )));
        
        $response = new Response($data);
        $response->headers->set('Content-Type', 'application/json');
        
        return $response;
```
