### ISSUE TITLE
Configuration property enable_cache is missing

### ISSUE THREAD

**Issue by nitso** [schmittjoh/JMSSerializerBundle#712]
I'm configuring bundle as of actual documentation (I'm using v3.0.1, but master has the same): https://github.com/schmittjoh/JMSSerializerBundle/blob/master/Resources/doc/configuration.rst#L143

But there is no `enable_cache` support in code: 
https://github.com/schmittjoh/JMSSerializerBundle/blob/3.0.1/DependencyInjection/Configuration.php#L121

So I get error: 

    Symfony\Component\Config\Definition\Exception\InvalidConfigurationException : 
      Unrecognized option "enable_cache" under "jms_serializer.property_naming". 
      Available options are "id", "lower_case", "separator".

Where is the error: cache is not supported or the configuration option is missing?

**Comment by goetas** [comment]
`enable_cache` has been removed. In the new jms/serializer property names are cached at cache-warmup time, so they are "always" cached

**Comment by goetas** [comment]
I have updated the docs

**Comment by nitso** [comment]
Thanks! Incredibly fast :+1:
