### ISSUE TITLE
DRIVERS

### ISSUE THREAD

**Issue by victorgp89** [schmittjoh/JMSSerializerBundle#715]
Hi, 
It's possible to add new drivers in DriverChain? 

Ideally to add any custom metadata properties. and add some other attribute if we need it for some function.

For example: 

Igm\Server\Models\Hotels\SoapEnvelope\Headers\GetHotelsInput:
    xml_namespaces:
        SOAP: 'http://schemas.xmlsoap.org/soap/envelope/'
    properties:
        requestHotelHeader:
            expose: true
            access_type: public_method
            **mapped_by**: some_value

**Comment by goetas** [comment]
Generally yes, but you have to do it manually. I do not suggest it to  be honest. It is a lot of work.

for some cases, expression language and virtual properties might help (see http://jmsyst.com/libs/serializer/master/reference/annotations#virtualproperty)

**Comment by goetas** [comment]
As this is a question, the conversation can continue on a closed issue

**Comment by victorgp89** [comment]
I use YamlDriver . not annotationDriver. 

I see SerializerBuilder DefaultDriverFactory doesn't accept one as a parameter an instance of factory.

![image](https://user-images.githubusercontent.com/9083812/51383563-119b4980-1b1a-11e9-8d50-a8ea0d2dc018.png)

My intention was to create a driver that extended YamlDriver to manage new attributes in a Yaml file that obviously should be added manually.

**Comment by goetas** [comment]
This is `schmittjoh/JMSSerializerBundle`, i guess this ticket is more related to https://github.com/schmittjoh/serializer or https://github.com/goetas-webservices/xsd2php

- if you are using `schmittjoh/JMSSerializerBundle` that is already possible by injecting one more driver tin the chain.
- if you are using `schmittjoh/serializer`, you should use `SerializerBuilder::setMetadataDriverFactory` and inject your metadata factory.
