### ISSUE TITLE
Unrecognized option "xml" under "jms_serializer.visitors". Available options are xml, json

### ISSUE THREAD

**Issue by rahulspnd** [schmittjoh/JMSSerializerBundle#719]
I newly installed new project with Symfony 4.2 . As the sonata-project/user-bundle requires  "jms/serializer-bundle": "^1.0 || ^2.0" .  After executing, it gives me error Unrecognized option "xml" under "jms_serializer.visitors". Available options are xml, json

Help me with the solution.

**Comment by goetas** [comment]
Attention that sonata-project/user-bundle uses require-dev, that is ignored in your project so you got jms/serializer-bundle v3.

So I suggest you downgrading to 2.x by adding it explicitly in your composer.json.

On the other side, if you wand to upgrade to jms/serializer-bundle v3, upgrading info are in 
https://github.com/schmittjoh/JMSSerializerBundle/blob/master/UPGRADING.md#upgrading-from-2x-to-30

**Comment by goetas** [comment]
Added feature request https://github.com/sonata-project/SonataUserBundle/issues/1082
