### ISSUE TITLE
DoctrinePHPCRTypeDrive is missing r

### ISSUE THREAD

**Issue by DennisStudent** [schmittjoh/JMSSerializerBundle#724]
https://github.com/schmittjoh/JMSSerializerBundle/blob/master/Resources/config/services.xml#L77

DoctrinePHPCRTypeDrive is missing an r
DoctrinePHPCRTypeDriver

**Comment by rachel-fizz** [comment]
When is this fix going to get tagged? I'm having to do this now: `class_alias(DoctrinePHPCRTypeDriver::class, 'JMS\\Serializer\\Metadata\\Driver\\DoctrinePHPCRTypeDrive');`

**Comment by goetas** [comment]
https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/3.2.0
