### ISSUE TITLE
How to use "service" in Expose / Exclude

### ISSUE THREAD

**Issue by hsb1007** [schmittjoh/JMSSerializerBundle#726]
I can see a function 'service' for Expose / Exclude Expression but when I use it,  it doesn't grab the service as intended.

Does anyone know how to use 'service' in if Expression in Exclude / Expose?

**Comment by goetas** [comment]
are you using the seraializerbuilder or the bundle-provided $serializer service?

**Comment by goetas** [comment]
I can from https://github.com/schmittjoh/JMSSerializerBundle/issues/725 that you are using the bundle. 
Please use the 'jms_serializer' service, that is already properly  configured.

here http://jmsyst.com/bundles/JMSSerializerBundle#installation you can find how to install and use it
