### ISSUE TITLE
(Deserializer) Internal Server Error when i set the id of a related entity to an id which does not exist

### ISSUE THREAD

**Issue by x00srch** [schmittjoh/JMSSerializerBundle#729]
```php
Argument 2 passed to JMS\Serializer\JsonDeserializationVisitor::startVisitingObject() must be an object, null given, called in (...)\vendor\jms\serializer\src\GraphNavigator\DeserializationGraphNavigator.php on line 184
```

Happens when i send (PATCH/PUT) this:
```json
{
    "id": 1000,
    "landing_page": {
        "id": 123,
        "name": "Test",
        "final_url": "https://www.google.com/"
    },
    "identifier": "test1234",
    "is_used": false
}
```

... to:

```php
/**
 * @Rest\Patch("/identifiers/v2/{id}")
 *
 * @ParamConverter("identifier")
 * @ParamConverter("identifierPatch", converter="fos_rest.request_body")
 */
```

It's about the related entity (landing_page) where the id does not exist in the database. (I am using the Doctrine Object Constructor.) 

The deserializer/startVisitingObject-function should return null and should continue to the next argument or it should at least throw an exception that the related entity does not exist. 

Greetings,
Danny

**Comment by goetas** [comment]
most likley Doctrine Object Constructor does not find the entity and you have not configured properly the UnserializeObjectConstructor as fallback.

**Comment by x00srch** [comment]
You can set it as solved - i had to set the "Fallback". :-)
