### ISSUE TITLE
Notice: Undefined property: JMS\Serializer\SerializationContext::$attribut

### ISSUE THREAD

**Issue by wajaja** [schmittjoh/JMSSerializerBundle#735]
Hi;

I use version 3.2.0 of this bundle and i got the error `Notice: Undefined property: JMS\Serializer\SerializationContext::$attribut` in symfony 4.2.3;  after calling `serializer.post_serialize` event.

the code of my `onPostSerializeMethod` function is:

```
public function onPostSerializeMethod(ObjectEvent $event) {
        $object  = $event->getObject();
        $visitor = $event->getVisitor();
        $context = $event->getContext();
        $type    = $event->getType();

        $attributes = $context->attributes;
    
        if (!$attributes->containsKey('groups')) {
             return [];
        }
        $grContext = $attributes->get('groups')->get(); 
       ...
}
```

**Comment by goetas** [comment]
Please check the upgrade document at https://github.com/schmittjoh/serializer/blob/master/UPGRADING.md

more precisely this https://github.com/schmittjoh/serializer/commit/3ab8fd2af23ef32843e2074d5f187c37693a73d0
