### ISSUE TITLE
TypeError when trying to serialize/cache anonymous class

### ISSUE THREAD

**Issue by jlekowski** [schmittjoh/JMSSerializerBundle#737]
The issue comes from `jms/metadata` and I reported it here https://github.com/schmittjoh/metadata/issues/79.

But in short, `TypeError` is thrown when a instance of anonymous class is returned in action to be serialized due to null byte issue (https://www.php.net/manual/en/security.filesystem.nullbytes.php).

```
// same with rename() function
$ php -r 'declare(strict_types=1); file_exists("file.php\0");'
PHP Fatal error:  Uncaught TypeError: file_exists() expects parameter 1 to be a valid path, string given in Command line code:1
Stack trace:
#0 Command line code(1): file_exists('file.php\x00')
#1 {main}
  thrown in Command line code on line 1
```

See the code lines:
https://github.com/schmittjoh/metadata/blob/master/src/Cache/FileCache.php#L31
https://github.com/schmittjoh/metadata/blob/master/src/Cache/FileCache.php#L64

There are ways to validate path:
- `strpos($class, "\0") !== false`
- `ctype_print($class)`
- `catch (\TypeError $e)`
- `$class->isAnonymous()`

or to fix it with `str_replace("\0", "", $class)`.

Eventually the class will not be cached using its name anyway because the name is like `class@anonymous/app/src/Controller/CoreController.php0x7f1f4ea446cf`. Also, according to the documentation https://www.php.net/manual/en/language.oop5.anonymous.php:
```
This name has to be regarded an implementation detail, which should not be relied upon.
```

In case it's not clear how to reproduce it, in a controller's action do something like:
```
return new class {
    public $property = 'name';
};
```

**Comment by goetas** [comment]
Anonymous classes can not have cached metadata, and currently not supported by jms/serializer and jms/metadata

**Comment by jlekowski** [comment]
@goetas, I understand that anonymous classes are not supported, and my intention was not to request such support. I believe that like in other cases (e.g. when InvalidArgumentException or RuntimeException is thrown), this should be validated to avoid unexpected `TypeError`.

**Comment by jlekowski** [comment]
Solved in https://github.com/schmittjoh/metadata/pull/90#issuecomment-636433149
