### ISSUE TITLE
Visitor Configuration XML - Serialization references to Deserialization Configuration node

### ISSUE THREAD

**Issue by dennzo** [schmittjoh/JMSSerializerBundle#738]
While using the JMS Serializer Bundle we tried to configure the XML settings.
Unfortunately the **serialization** configuration option seems to reference the **deserialization** configuration which should actually reference the **serialization** configuration.

jms/serializer-bundle/DependencyInjection/JMSSerializerExtension.php

```php
if (!empty($config['visitors']['xml_serialization']['encoding'])) {
    $container->getDefinition('jms_serializer.xml_serialization_visitor')
        // This seems to be an issue.
        ->addMethodCall('setDefaultEncoding', [$config['visitors']['xml_deserialization']['encoding']]);
        // If changed to following line it works
        ->addMethodCall('setDefaultEncoding', [$config['visitors']['xml_serialization']['encoding']]);
});
}
```

Also the documentation is not up to date.
For example these xml visitor options are not mentioned.
https://jmsyst.com/bundles/JMSSerializerBundle/master/configuration

**Comment by goetas** [comment]
Hmm. Something is weird. 
The source code is showing correctly  (see https://github.com/schmittjoh/JMSSerializerBundle/blob/master/Resources/doc/configuration.rst) but the website is not.

**Comment by dennzo** [comment]
Thanks very much for your quick response and action!
Unfortunately there may be something else within the configuration.

The Version is expected to be a boolean, but the documentation suggests it should be given as a scalarNode.

https://github.com/schmittjoh/JMSSerializerBundle/blob/master/DependencyInjection/Configuration.php#L283

```
->booleanNode('version')
```
Should be
```
->scalarNode('version')
```

**Comment by goetas** [comment]
Makes sense... can you submit a PR with the fixes?

**Comment by dennzo** [comment]
Sure I can! I can check a little further, maybe I find some more things :)
