### ISSUE TITLE
@Serializer\Type("boolean") problem

### ISSUE THREAD

**Issue by engharb** [schmittjoh/JMSSerializerBundle#743]
Hello,

I have a problem when I use the annotation @Serializer\Type("boolean") as the following:
```
/**
     * @var integer $abc
     * @Serializer\Type("boolean")
     * @myBooleanValidator()
     */
    private $abc;
```

The result is always true, therefore I can not use my validator to check if the url params is equal TRUE or FALSE.

I heard that @SerializeName is helpful but I could not find an example. Any suggestions or example shows how to solve it?

Thanks.

**Comment by goetas** [comment]
Are you serializing or deserializing?

**Comment by engharb** [comment]
@goetas Deserializing. I want to convert/valid the Request query params.

**Comment by goetas** [comment]
> The result is always true, therefore I can not use my validator to check if the url params is equal TRUE or FALSE.

JMS sets always the param as boolean, so `$abc` will always a boolean.

If you want it to be something else, you have to change `@Serializer\Type("boolean")`
