### ISSUE TITLE
Block serializer in Subscriber

### ISSUE THREAD

**Issue by NicolaPez** [schmittjoh/JMSSerializerBundle#745]
I guys,
I would block to serialized an object in certain case, inside my subscriber on serializer event. Is this possible? Somethings like this:

```
public function onPreSerialize(ObjectEvent $event)
    {
        /** @var \JMS\Serializer\JsonSerializationVisitor $visitor */
        $visitor = $event->getVisitor();
        $object = $event->getObject();

        $count = $this->em->getRepository('AppBundle:Object')->count($object);
        if($count == 0){
            //something to block serialize this object
        }
    }
```

**Comment by goetas** [comment]
you should not do so in a preSerialize but using exclusion strategies.

You can use a custom exclusion strategy or even better a expression bases exclusion strategy.

More info on https://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#dynamic-exclusion-strategy

**Comment by NicolaPez** [comment]
But my exclusion strategy would be on the entire object, not on single parameter. Maybe something about block the event? 
I need to serialize a collection of object, but exclude some of this in a certain condition.

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/blob/master/src/Exclusion/ExclusionStrategyInterface.php#L21 is invoked when serializing each object, from the context you can extract with `getObject` the "current" object, even for collections, and decide to skip it

**Comment by NicolaPez** [comment]
Ok, this seems what i need, thanks!

So I need to create my exclusione strategy and inject in the serializer, like [this]? Cool!(https://stackoverflow.com/a/23568060/5475228)
