### ISSUE TITLE
Serialize same object multiple times

### ISSUE THREAD

**Issue by lowki** [schmittjoh/JMSSerializerBundle#747]
I have a classic nested entities logic with Category and Section entities, and methods to get their parents and children.

When I serialize a Section entity I also want to have the Category it is attached to and all this Category's sections.

The problem is that the serializer removes the current Section from the Category's sections collection.

Here's the output json.
````json
    {
      "id": 1,
      "title": "Section 1",
      "thumb": null,
      "category": {
        "id": 1,
        "title": "Category 1",
        "sections": [
          {
            "id": 2,
            "title": "Section 2"
          },
          {
            "id": 3,
            "title": "Section 3"
          }
        ]
      }
    }
````
I'm not sure this is related to JMSSerializerBundle and I don't think it is an issue, but is there any way to avoid this behavior?

**Comment by goetas** [comment]
Are we talking here about circular references? Can you please clarify what is the expected JSON for you?

**Comment by lowki** [comment]
Ho yes sorry, here's the JSON I expect:

````json
    {
      "id": 1,
      "title": "Section 1",
      "thumb": null,
      "category": {
        "id": 1,
        "title": "Category 1",
        "sections": [
          {
            "id": 1,
            "title": "Section 1"
          },
          {
            "id": 2,
            "title": "Section 2"
          },
          {
            "id": 3,
            "title": "Section 3"
          }
        ]
      }
    }
````

**Comment by goetas** [comment]
Category 1 has a circular reference with Section 1, is skipped because of that.

**Comment by lowki** [comment]
Yes I understand, but is there any way to achieve what I expect?

**Comment by goetas** [comment]
Dont have in mind any clean solution.

Maybe putting a custom handler on the sections array property, removing the Section 1 object from the visiting stack, visit the sections array, and then put back the section 1 object in the stack.

Is not clean, but should work. A problem is that the serializer could go in recursion loop, as it will try to serialize the section recursively. 
You should make sure that that does not happen using some exclusion strategy

**Comment by lowki** [comment]
I already have exclusion strategy to avoid recursion loops, maybe I will try the custom handler approach (as I got it working now :D) , thanks a lot ;)

**Comment by goetas** [comment]
:+1:
