### ISSUE TITLE
Unable to register custom Handler

### ISSUE THREAD

**Issue by lowki** [schmittjoh/JMSSerializerBundle#748]
I can't declare a custom Handler service following the [doc](https://jmsyst.com/bundles/JMSSerializerBundle/master/configuration) 

Here's my custom handler class:
````php
<?php
use JMS\Serializer\JsonSerializationVisitor;
use JMS\Serializer\Context;
use JMS\Serializer\Handler\SubscribingHandlerInterface;

namespace AppBundle\Service;

class SerializerHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods()
    {
        return [
            [
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format' => 'json',
                'type' => 'integer',
                'method' => 'serializeIntToJson',
            ],
        ];
    }
    
    public function serializeIntToJson(JsonSerializationVisitor $visitor, $int, array $type, Context $context)
    {
        dump($int);
        return $int;
    }
}
````

And my service declaration:

````yml
AppBundle\Service\SerializerHandler:
        tags:
            - { name: 'jms_serializer.subscribing_handler', type: 'integer', format: 'json', method: 'serializeIntToJson' }
````

This throws this error

> The service "AppBundle\Service\SerializerHandler" must implement the SubscribingHandlerInterface.

Any idea?

**Comment by goetas** [comment]
You can not declare type handlers on primitive types. You can type hint your property with a virtual type and set a custom handler on it.

**Comment by goetas** [comment]
But the error your error seem related to something else. Can you please post a more complete stack trace?

**Comment by lowki** [comment]
I only have this 

(1/1) RuntimeExceptionThe service "AppBundle\Service\SerializerHandler" must implement the SubscribingHandlerInterface.
--
in CustomHandlersPass.php line 54
at CustomHandlersPass->process(object(ContainerBuilder))in Compiler.php line 141
at Compiler->compile(object(ContainerBuilder))in ContainerBuilder.php line 790
at ContainerBuilder->compile()in Kernel.php line 637
at Kernel->initializeContainer()in Kernel.php line 135
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request))in app_dev.php line 15

**Comment by goetas** [comment]
Correct me if I am wrong, but should nt the use statements be after the namespace statement?

**Comment by lowki** [comment]
OMG what a shame, thank you...
