### ISSUE TITLE
In ArrayNode.php line 331:Unrecognized option "json" under "jms_serializer.visitors". Available options are "json_deserialization", "json_serialization", "xml_deserialization", "xml_serialization". 

### ISSUE THREAD

**Issue by Pasuvan** [schmittjoh/JMSSerializerBundle#750]
Anyone know that issue *Symfony 3.4 to flex upgrade* please give me Solution ASAP.
Thanks

**Comment by goetas** [comment]
Please check https://github.com/schmittjoh/JMSSerializerBundle/blob/master/UPGRADING.md#upgrading-from-2x-to-30

**Comment by Pasuvan** [comment]
@goetas already i checked and changes are done, But the same issue happening, Please review it
https://github.com/symfony/recipes-contrib/issues/674 . Here i put my config and details.
