### ISSUE TITLE
Migrate from 2.4.4 to 3.0.1 :visitor->visitProperty do nothing

### ISSUE THREAD

**Issue by yalg** [schmittjoh/JMSSerializerBundle#754]
Hi,

I try to migrate from 2.4.4 to 3.0.1.

I made the changes in config file, and make tests.

But this code in a POST_SERIALIZE event seems not working, no error but no property added :

```
class TestSerializerSubscriber implements EventSubscriberInterface
{
    static public function getSubscribedEvents()
    {
        return array(
            array(
                'event' => Events::POST_SERIALIZE,
                'method' => 'onPostSerialize',
                'direction' => 'serialization',
            ),
        );
    }

    public function onPostSerialize(ObjectEvent $event)
    {
            $visitor = $event->getContext()->getVisitor();
            $property = new StaticPropertyMetadata('', 'test', 123456);
            $visitor->visitProperty($property, null,$event->getContext());
    }
}
```

I'm looking for issues, but I found nothing, it seems that I forget something... but what!

Thanks

**Comment by goetas** [comment]
Please check the [UPGRADING](https://github.com/schmittjoh/serializer/blame/cff99c4874a23a697c5c103e384ce15e7ae512a4/UPGRADING.md#L38) notes. Your code should be:

```php
$property = new StaticPropertyMetadata('', 'test', null);
$visitor->visitProperty($property, 123456);
```

**Comment by yalg** [comment]
Thanks! Sorry for this question, I didn't realise that it was inversed...
