### ISSUE TITLE
Since 3.4.0, JSON_PRESERVE_ZERO_FRACTION is no longer the default value `json_encode`

### ISSUE THREAD

**Issue by fbourigault** [schmittjoh/JMSSerializerBundle#755]
It looks like #749  caused a regression.

Before #749, the default value of `jms_serializer.visitors.json_serilization:options` which is 0 was ignored because an `!empty` check was used. So the `setOptions` method call was not added to the container builder (https://github.com/schmittjoh/JMSSerializerBundle/blob/2842e767bd0e64310ab803e05bb5f676c81c0bbe/DependencyInjection/JMSSerializerExtension.php#L198-L201).

In this case the `JMS\Serializer\JsonSerializationVisitor::$options` default (`JSON_PRESERVE_ZERO_FRACTION`) was used.

Now, the `!empty` check was replaced by a `!isset` check. By doing so, the default value of 0 is now used.

I suggest to set the default value of `jms_serializer.visitors.json_serilization:options` to `JSON_PRESERVE_ZERO_FRACTION` to fix the regression and keep the benefits of #749.

**Comment by goetas** [comment]
I agree. Can you make a PR?
