### ISSUE TITLE
Is it possible to overwrite the discriminator of the parent class for mapping?

### ISSUE THREAD

**Issue by happydaystech** [schmittjoh/JMSSerializerBundle#756]
Normally we used to map the object in an abstract class by using Discriminator mapping 

I can easily map by selecting one field and map the class.

But I am found difficulty  to map class by considering two field

```
<xml>
<call name="login" timestamp="2011/01/18 14:33:03.000" system=“normal”>
 <name first="24971455-aecc-4a69-8494-f544d49db3da" second=“name” id=“ff” />
</call>
</xml>

<xml>
<call name="login" timestamp="2011/01/18 14:33:03.000" system=“standard”>
 <name first="24971455-aecc-4a69-8494-f544d49db3da" second=“name” id=“ff” />
</call>
</xml>

@Serializer\Discriminator(
     field = "system",
     map = {
          "normal": "normalClass",
          "standard": "standardClass",
     }
 )
  
                        
@Serializer\Discriminator(
     field = "name",
     map = {
          "Login": "LoginClass",
          "registraton": "registratonClass",
     }
 )
```

**Comment by goetas** [comment]
Not really. The metadata are per class and the discriminator map has to be on top of the hierarchy.
It is also not possible to map classes based on two discriminator map fields.

I think this answers your question. 

If you have more comments, we can discuss it on the closed issue
