### ISSUE TITLE
Supporting multiple format with (Datetime or others) handlers

### ISSUE THREAD

**Issue by VincentLanglet** [schmittjoh/JMSSerializerBundle#758]
We were using this annotation to deserialize DateTime in files from different API.
```
@JMS\Type("DateTime<'Y-m-d\TH:i:s'>")
```

Recently one API send DateTime with a different format, example
```
2019-07-01T03:03:39+02:00
```

It should be great if it was possible to handle multiple format. With something like
```
@JMS\Type("DateTime<'Y-m-d\TH:i:s', 'Y-m-d\TH:i:sP'>")
```
Or 
```
@JMS\Type("DateTime<'Y-m-d\TH:i:s'>", "DateTime<'Y-m-d\TH:i:sP'>")
```

**Comment by goetas** [comment]
In a related project I have implemented a custom type handler to manage a similar situation. See https://github.com/goetas-webservices/xsd2php-runtime/blob/master/src/Jms/Handler/XmlSchemaDateHandler.php

This could a a nice feature to have. 

However in your proposed syntax I see few issues:
- the first conflicts with the existing syntax
- the second allows multi type declarations, not only multiple date formats 
- which format to choose when serializing?

**Comment by VincentLanglet** [comment]
> * the second allows multi type declarations, not only multiple date formats

Not a problem with a correct answer to the following question

> * which format to choose when serializing?

What about something like this:
```
@JMS\Type("Handler1", "Handler2", ...)
```

If handler1 return a value, use it
Else, If handler1 return null, use handler2
Then the same with handler2
If handler2 return a value, use it
Else, if handler 2 return null, use handler3 ...

In the case of DateTime, it will need to modify the handler to return `null` instead of `false` in case of error. But I think if multi-handler is introduce it's better to fall back to another handler only if the value is `null` than any falsy value.

**Comment by goetas** [comment]
`@JMS\Type("Handler1", "Handler2", ...)` still means "multiple types"... something that PHP is trying to get rid of.

For the specific date usecase, I can suggest something as:

```
@JMS\Type("DateTime<['Y-m-d\TH:i:s', 'Y-m-d\TH:i:sP']>")
```

Not that this syntax is not implemented... the current parser does not handle `[]`.... is just a proposal.

**Comment by VincentLanglet** [comment]
> For the specific date usecase, I can suggest something as:
> 
> ```
> @JMS\Type("DateTime<['Y-m-d\TH:i:s', 'Y-m-d\TH:i:sP']>")
> ```
> 
> Not that this syntax is not implemented... the current parser does not handle `[]`.... is just a proposal.

This would be great, should I start working on this parser ?

**Comment by goetas** [comment]
The current syntax is:
```
DateTime<?format?, ?zone?, ?deserializeFormat?>
```

So the `deserializeFormat` can be an array to.

So the following formats should be allowed:

```
@JMS\Type("DateTime<null, null, 'Y-m-d\TH:i:s'>")
@JMS\Type("DateTime<null, null, ['Y-m-d\TH:i:s', 'Y-m-d\TH:i:sP']>")
```

The first tow args even now should be optional... the third currently is a string, but it should be possible to make it an array.


Few info that might help you:
- https://github.com/schmittjoh/serializer/blob/master/src/Type/grammar.pp is the file with the grammar.
- https://github.com/schmittjoh/serializer/blob/master/src/Type/regenerate-parser.php is the executable to re-generate the parser
- https://github.com/schmittjoh/serializer/blob/master/src/Type/TypeVisitor.php is the parser visitor
- https://github.com/schmittjoh/serializer/blob/master/src/Handler/DateHandler.php is the date handler

**Comment by VincentLanglet** [comment]
Ok, I started here https://github.com/schmittjoh/serializer/pull/1108

**Comment by goetas** [comment]
Great

**Comment by VincentLanglet** [comment]
Sorry, I kinda forget this issue.
The PR https://github.com/schmittjoh/serializer/pull/1108 seems ready for review to me.

**Comment by VincentLanglet** [comment]
@goetas I close this issue since it will be fixed with the next releases.

**Comment by vasilvestre** [comment]
Does it work for ArrayCollection ? It doesn't seem documented here https://jmsyst.com/libs/serializer/master/reference/annotations
