### ISSUE TITLE
Symfony. User Deprcated warning.

### ISSUE THREAD

**Issue by nawataster** [schmittjoh/JMSSerializerBundle#759]
`User Deprecated: The type "jms_job_safe_object" was explicitly marked as commented in its configuration. This is no longer necessary and will be removed in DoctrineBundle 2.0. Please remove the "commented" attribute from the type configuration.`
Change, please, this type to another one at:
vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Entity/Job.php
Line 160.
Thanks.

**Comment by goetas** [comment]
I think your intention was to open a ticker for https://github.com/schmittjoh/JMSJobQueueBundle, not for this project...

**Comment by nawataster** [comment]
Sorry. yes.
