### ISSUE TITLE
BasicSerializerFunctionsProvider uses ExpressionFunctionProviderInterface but does not require or suggest it

### ISSUE THREAD

**Issue by tominventisbe** [schmittjoh/JMSSerializerBundle#764]
The class `BasicSerializerFunctionsProvider` uses classes from `symfony/expression-language` but this dependency is only announced in `require-dev`, so it does not propagate to packages using this bundle.

Is this perhaps intentional and an optional dependency? In that case it may be interesting to place it in `suggests`.

**Comment by goetas** [comment]
yes, it is an optional dependency. Feel free to crate a PR, adding it to the suggests section

**Comment by giansalex** [comment]
I have an error

```
Uncaught ReflectionException: Class "Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface" not found while loading "JMS\SerializerBundle\ExpressionLanguage\BasicSerializerFunctionsProvider"
```

**Comment by goetas** [comment]
Can someone make a pull request adding it to the suggested packages in https://github.com/schmittjoh/serializer/blob/master/composer.json#L25 ?
