### ISSUE TITLE
Interface 'Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface' not found

### ISSUE THREAD

**Issue by CmderQ** [schmittjoh/JMSSerializerBundle#765]
Hi，man，When I used 'composer install' ，It alert ：
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Interface 'Symfony\Component\ExpressionLanguage\ExpressionFunctionProviderInterface' not found in /var/www/html/code_info/system-service/vendor/jms/serializer-bundle/ExpressionLanguage/BasicSerializerFunctionsProvider.php on line 8

**Comment by goetas** [comment]
Can this be related to https://github.com/schmittjoh/JMSSerializerBundle/issues/764 ?

**Comment by CmderQ** [comment]
Yeah，It is helpful for me!
