### ISSUE TITLE
Explicitly defining which JSON field is to be mapped to a certain class property

### ISSUE THREAD

**Issue by BentCoder** [schmittjoh/JMSSerializerBundle#770]
Hi,

I haven't seen any annotation that does what I describe below unless I missed it. Is there a solution to it or should this be a feature request?

Thanks

**Payload**
```json
{
  "id": 1234,
  "properties": {
    "name": {
      "version": "v1",
      "value": "John"
    }
  }
}
```

**Model**
```php
class Payload
{
    /**
     * @Serializer\Type("string")
     */
    public $id;

    /**
     * @Serializer\Type("<properties.name.value>string") <--- Something like this
     */
    public $name;
}
```

**Comment by goetas** [comment]
Currently this is not implemented (and I'm also not sure if is a good idea to have something as it...).

What it seems to me is essentially some "path_mapping" of properties

**Comment by BentCoder** [comment]
In order for me to handle such request I'll have to create three different models (`payload`, `property` and `name`) which could be pain just for a single property mapping. It would even be more painful if the depth was bigger. I think it could be useful feature.

**Comment by goetas** [comment]
Something similar was already discussed in https://github.com/schmittjoh/serializer/issues/22

**Comment by goetas** [comment]
I see it very difficult to implement. Do you have an idea on how to do it?

**Comment by BentCoder** [comment]
I am currently doing it manually with is not scalable at all.

```php
        $payload = json_decode($request->getContent(), true);

        $extractedData['id'] = $payload['id'] ?? null;
        $extractedData['name'] = $payload['properties']['name']['value'] ?? null;

        // I then encode $extractedData and pass it to deserializer.
```

If there was such option (not necessarily the same) as I `<properties.name.value>`, I simple `explode` would work to build `$payload['properties']['name']['value'] ?? null`. Just a rough idea though - not perfectly though!
