### ISSUE TITLE
Bad Serialization : object instead of array

### ISSUE THREAD

**Issue by alexdu98** [schmittjoh/JMSSerializerBundle#773]
Hello,

I have a problem of serialization. An array with non-consecutive keys is serialized as an object.

Examples of arrays :
```php
$a1 = array(
    NULL,
    array('prop1' => 2),
    array('prop1' => 3)
);
$a2 = array(
    array('prop1' => 1),
    NULL,
    array('prop1' => 3)
);
$a3 = array(
    array('prop1' => 1),
    array('prop1' => 2),
    NULL
);
```

The Serialization results are :
$a1 :
```json
{
    "1": {
        "prop1": 2
    },
    "2": {
        "prop1": 3
    }
}
```
$a2 :
```json
{
    "0": {
        "prop1": 1
    },
    "2": {
        "prop1": 3
    }
}
```
$a3 :
```json
[
    {
        "prop1": 1
    },
    {
        "prop1": 2
    }
]
```
I found [issue 321](https://github.com/schmittjoh/JMSSerializerBundle/issues/321) that mentions this behavior.
I conclude with the same thing, the problem is due to the indexes of the array.

The problem is that in my case the result comes from a Doctrine query and sometimes contains null values.
2 possible but not viable solutions in my opinion :
The first one is to add setSerializeNull(true), but this forces you to check in post traitement if the foreach that the value is not null.
The second is to browse the array before serialization to delete the null values and reorder the array, but it's not very optimal in terms of performance.

Would it not be possible to plan a correction/evolution to have an array rather than an object in this case?
If not, do you have another solution to offer me?

**Comment by goetas** [comment]
Please check https://github.com/schmittjoh/serializer/blob/master/doc/cookbook/arrays.rst to see how can you configure jms to serialize arrays properly. You can use the same syntax for the `@Type` annotation
