### ISSUE TITLE
Missing Annotations, if request not hits a controller

### ISSUE THREAD

**Issue by wiseguy1394** [schmittjoh/JMSSerializerBundle#775]
Our system:
**Symfony 4.3.5**

We are getting a fatal error, 
if we use the serializer but the route ends in authentication.

**Fatal Error: Unknown Annotation group**

if the requests hits a controller everything works fine.

Is there any possibility to load the annotations in any context?

**Comment by goetas** [comment]
This seems a support question, and no feedback has been provided after more than 6 months. Closing
