### ISSUE TITLE
JMSSerializer deserialize entity by id

### ISSUE THREAD

**Issue by ei-developpers-team** [schmittjoh/JMSSerializerBundle#776]
Hello,

any help plz;
i need to deserialize entity by id . () ManyToone.
_Invalid data 1 (integer), expected_ 

any idea?

**Comment by zoomtronic** [comment]
same issue, if you have any update on this..
the only thing that worked for me is to add merge before persist but its deprecated.. 

> $serializer = SerializerBuilder::create()->build();
$block = $serializer->deserialize($encodedData, 'App\Entity\Block', 'json');
$block = $manager->merge($block);
            // persist
            $manager->persist($block);
            $manager->flush();

**Comment by goetas** [comment]
this has been documented in https://github.com/schmittjoh/serializer/pull/1308
