### ISSUE TITLE
JMS - Abstract class collection set property type from child class using method `getType`

### ISSUE THREAD

**Issue by DangleBerry** [schmittjoh/JMSSerializerBundle#778]
The issue I am having is when I deserialze an oject which inherits the property values from the parents its returned as multidimensional array when it should be an array of objects that is defined by the child. 

So I have custom abstract collection class that has one property named values. The child class initiates the values type by calling the abstract method of getType which returns the object type for the collection.

My YAML Configuration

Collection:

    exclusion_policy: NONE
    properties:
        values: 
            type: array

PersonCollection:

    exclusion_policy: NONE
    properties:
        values:
            type: array<Person>

Person:

    exclusion_policy: NONE
    properties:
        name:
            type: string

When the collection is deserialized it returns as multidimensional array not an collection of the Person object at property values.   

 

Collection.php

    abstract class Collection {
    	
    	protected $values; 
    	
    	public function __construct(){
    		
    		$this->values = [];
    		
    	}
            
            abstract static public function getType();
    }

PersonCollection.php

    class PersonCollection extends Collection {
    
          public static function getType(){
                  return 'Person'; // this is an entity 
    
          }
    
    }

Person.php

    class Person {
          private $name;
    
    }

**Comment by goetas** [comment]
I think http://jmsyst.com/libs/serializer/master/reference/annotations#discriminator is what you need

**Comment by DangleBerry** [comment]
Thanks for your quick response. 

I have been trying to get the discriminator work over the last 24 hours only am not having much luck. Here is the configuration I used. 

Collection:
    exclusion_policy: NONE
    discriminator:
        field_name: type
        disabled: false
        map:
            person: PersonCollection
    properties:
        values: 
            type: array 

Person:
    exclusion_policy: NONE
    properties:
        name:
            type: string

$person = new Person('Matthew');
$collection = new PersonCollection();
$collection->add($person);

$json = $serializer->serialize($collection, 'json');

$deserialized = $serializer->deserialize($json, PersonCollection::class, 'json');

object(PersonCollection)#59 (1) {
  ["values":protected]=>
  array(1) {
    [0]=>
    array(1) {
      ["name"]=>
      string(7) "Matthew"
    }
  }
}  

When I change the 'field_name: type' to 'field_name: values' in the `Collection` yaml configuration I get a logic exception `Uncaught LogicException: The discriminator field name "values" of the base-class "Collection" conflicts with a regular property of the sub-class "PersonCollection"`

**Comment by DangleBerry** [comment]
My apologies for wasting your guys time. I have instead decided to implement an interface.
