### ISSUE TITLE
Unable to install in Symfony 5.1

### ISSUE THREAD

**Issue by gcorchon** [schmittjoh/JMSSerializerBundle#779]
I have a fresh installation of Symfony 5.1 and I get the following message when trying to install the bundle:

> jms/serializer-bundle 3.4.1 requires symfony/dependency-injection ^3.3 || ^4.0 -> no matching package found

It seems it's still not compatible with the latest version of Symfony, are there any plans to support it?

**Comment by W0rma** [comment]
This should have been fixed in https://github.com/schmittjoh/JMSSerializerBundle/commit/209d2a3de1d567be57bddb780a71efba3238ee32 .

A new release needs to be tagged.

**Comment by ruudk** [comment]
@gcorchon 
```diff
-Symfony 5.1
+Symfony 5
```

@goetas Can we new version be tagged please? 🙏

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/3.5.0
