### ISSUE TITLE
Convert metadata config to another format

### ISSUE THREAD

**Issue by gam6itko** [schmittjoh/JMSSerializerBundle#791]
Hello. I have project which has serializer metadata in Annotations. I need to convert it to `yaml` format. Is there a way how to convert metadata to another configuration format?

**Comment by goetas** [comment]
Currently that feature is not available, but it would be very nice to have.

**Comment by gam6itko** [comment]
I can try to realize it, if you do not mind

**Comment by goetas** [comment]
That would be great. I guess that you will have to add some code in the serializer library (that reads from the Metadata factory and dumps it to yaml) , and then have a command here in the bundle.

**Comment by gam6itko** [comment]
It's not posible to extract some properties from Metadata like `exclusion_policy`, `virtual_properties` for classes and `expose`, 'access_type' etc for properties. 

I see the following solutions:

1. Add properties to Metadata classes for export.
Add several properties to ClassMetadata and PropertyMetadata and use it just for export to another format.

2. `Config` class
We can add another layer between serializer configuration files (annotation, yml, xml) and Metadata. Something like `Config` class. In this way Driver will load all data from configuration file (annotation, yml, xml) to `Config` class. Then we will have oportunity to convert it to another confugurations format and Metadata.

- Get data from config file
- Store data to Config object
- Convert Config to Metadata or another configuration file

What you think?

**Comment by goetas** [comment]
rather than trying to reproduce the initial metadata files, why not generate only what available in the metadata object? I mean `exclusion_policy` can be set always to "ALL" and `access_type` can be set to whatever can be inferred from the metadata. I think that there is no need to have the same files if the semantic is kept the same.

**Comment by gam6itko** [comment]
In this case, I’d better create a separate project and implement the conversion through the Config class. Because the “grab what you can” approach can cause serialization problems after conversion.

With this approach, extra files will not be downloaded with the project, if you do not need to convert configurations.

**Comment by gam6itko** [comment]
Here https://github.com/gam6itko/jms-serializer-config-converter
