### ISSUE TITLE
Stopwatch throwing error

### ISSUE THREAD

**Issue by mpoiriert** [schmittjoh/JMSSerializerBundle#796]
This is not a problem of you implementation but rather a bug in symfony.

I just want to point it out. Here is the comment on the specific commit that introduce the bug on symfony side.

https://github.com/symfony/http-kernel/commit/7b2421a59caf2bb273f2736c5c8d1a5b55de6ae6#commitcomment-38683251

**Comment by goetas** [comment]
Actually I'm having the same problem... (in a project that even does not use jms/serializer).. do you have a workaround for it?

**Comment by goetas** [comment]
I think that is better to file a report on symfony rather than commenting on the commit

**Comment by goetas** [comment]
Closing as this is a bug in symfony and tracked by https://github.com/symfony/symfony/issues/36623
