### ISSUE TITLE
Missing dependency symfony/templating ?

### ISSUE THREAD

**Issue by kevinpapst** [schmittjoh/JMSSerializerBundle#799]
Hi,
I [received a bug report](https://github.com/kevinpapst/kimai2/issues/1689) stating that a build of my app fails during `composer install` with
```
!!  PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class "Symfony\Component\Templating\Helper\Helper" not found while loading "JMS\SerializerBundle\Templating\SerializerHelper". in .../vendor/symfony/config/Resource/ClassExistenceResource.php:181
```
I cannot reproduce the problem.

But looking at the code it seems that the [SerializerHelper extends Symfony\Component\Templating\Helper\Helper](https://github.com/schmittjoh/JMSSerializerBundle/blob/master/Templating/SerializerHelper.php#L15) which itself is not living in the [FrameworkBundle](https://github.com/symfony/framework-bundle/tree/v4.4.8/Templating/Helper) but in the [Templating package](https://github.com/symfony/templating/tree/v4.4.8/Helper).

So multiple questions:
- The templating package is neither mentioned in composer require section nor in suggest, should it be added?
- Could it happen, because `jms_serializer.templating.helper.serializer` is registered as service by default?

Do you have any other idea how to solve it without requiring `symfony/templating`?

**Comment by goetas** [comment]
it seems like a bug. 
the feature should be enabled only if the templating package is available

**Comment by kevinpapst** [comment]
I wasn't able to reproduce the problem, currently using:
- Symfony 4.4.7
- jms/serializer-bundle 3.5.0
What can I do to help?

**Comment by goetas** [comment]
https://github.com/schmittjoh/JMSSerializerBundle/pull/800 should solve it

**Comment by kevinpapst** [comment]
That was quick, I didn't even had a chance to test it before you merged. 

Thanks another time for your support @goetas 🎉 awesome work 👍 
 
I'll ask my user if he can give it a try and will let you know if he responds.
