### ISSUE TITLE
Error after upgrading to 3.7

### ISSUE THREAD

**Issue by fikusz01** [schmittjoh/JMSSerializerBundle#802]
Hey guys!

After upgrading JMSSerializerBundle to v3.7, our system drops this error message:

`Uncaught PHP Exception ErrorException: "Notice: Undefined offset: 15" at /application/vendor/jms/serializer/src/Metadata/ClassMetadata.php line 325`

Had to revert to previous version to get it work again.

**Comment by goetas** [comment]
Did you clear the cache?

**Comment by benjamintoussaint** [comment]
I did not clear the cache, but now I have and this error pops up:

`{"code":500,"message":"Notice: Undefined property: JMS\\Serializer\\Metadata\\ClassMetadata::$excludeIf"}`

**Comment by fikusz01** [comment]
> Did you clear the cache?

Yes, I did it in my host system by default with Symfony's composer auto scripts. But after I entered my Docker container and cleared there as well manually it started to work. Interesting, 'cause both systems have the same php version and permissions...

**Comment by benjamintoussaint** [comment]
I removed the `jms` folder from the `vendors` and run `composer install` and **it works now**, sorry for raising a flag for that one, and thanks for your swift reply 👍

**Comment by fikusz01** [comment]
Yeah, thanks for the quick response!
