### ISSUE TITLE
doctine OneToMany relation + JMSSerializer + critearea

### ISSUE THREAD

**Issue by ankit-ilogix** [schmittjoh/JMSSerializerBundle#809]
Hello

I'm using JMSSerializerBundle 1.14.0 version.

I'm facing an issue when I use **oneToMany** relation with **Criteria**. When I calling get method it's returning proper result with applied filter. But when I serialize it it's returning all data without an applied filter. I'm not sure why it's happening.

please give you help/suggestion for the same.
**COde:** 
```
   /**
     * @ORM\OneToMany(targetEntity="TrakeToCollection" , mappedBy="collection" ,
     *     fetch="EXTRA_LAZY", cascade={"remove"})
     * @ORM\OrderBy({"sort" = "ASC"})
     * @Groups({"Trakes"})
     */
    public $trakeToHomepageCollection;

public function getTrakeToCollection()
    {
        $criteria = Criteria::create();

        $criteria->where(Criteria::expr()->eq('status', true));
        $criteria->setMaxResults(1);
        $criteria->orderBy(['sort' => 'ASC']);
        return $this->trakeToCollection->matching($criteria);
    }

```
@goetas

**Comment by goetas** [comment]
@ankit-ilogix From the snippet you have shared, rhere is nothing that tells jms/serializer to use the getter method (maybe you want to use `@VirtualProperty`?), thus the serializer serializes all the data.
