### ISSUE TITLE
Symfony profiler page

### ISSUE THREAD

**Issue by gam6itko** [schmittjoh/JMSSerializerBundle#812]
Do you plan to realize Symfony profiler page for this bundle? If you do not have time for this, I will do it with pleasure in my free time. But I need your vision how it should be

**Comment by goetas** [comment]
hi! That would be great!
Time ago i started to work on it, but then i stopped as my time became quite limited.

I can share the code i wrote a that time with you. 

If you want we can chat in the doctrine or symfony slack. feel free to write me a private message!

**Comment by slava-v** [comment]
Hi there ! 
Is there any progress on this ?

I was thinking to start something in this direction :)

**Comment by gam6itko** [comment]
@slava-v Unfortunately no progress. =(

**Comment by gam6itko** [comment]
realised in #858
