### ISSUE TITLE
Use PHP 7.4 ReflectionsProperty's method "getType" when PHP version is ^7.2

### ISSUE THREAD

**Issue by Arlisaha** [schmittjoh/JMSSerializerBundle#826]
It seems that PHP version declared for current version (`3.7.0`) does nto match bundle's code PHP version. I am using this version  with PHP 7.2.2 and Symfony 4.4 but I get error : 
`Attempted to call an undefined method named "getType" of class "ReflectionProperty"` in class `JMS\Serializer\Metadata\Driver\TypedPropertiesDriver` line 107. I found out how to avoid issue, by declaring my types manually. Am I missing someting ?

**Comment by goetas** [comment]
This is very weird... both the library and the bundle enable the typed props driver only if php 7.4 is detected, see:
- https://github.com/schmittjoh/JMSSerializerBundle/blob/dd0f44530431fd762203b6ba6aee05322d8a7694/DependencyInjection/JMSSerializerExtension.php#L111
- https://github.com/schmittjoh/serializer/blob/3efd5db279f7582bb5c27ea233e434e45399dfb4/src/Builder/DefaultDriverFactory.php#L58

Can you please try to debug it ?

**Comment by Arlisaha** [comment]
Hum... I am realizing that m'y CLI is in 7.4 ans my Apache runtime in 7.2.2. Could it be the reason ?

**Comment by goetas** [comment]
I think that is exactly the issue.

**Comment by Arlisaha** [comment]
Silly me. Thank you and sorry for the waste of time.
