### ISSUE TITLE
Move Travis to GitHub Actions

### ISSUE THREAD

**Issue by Yozhef** [schmittjoh/JMSSerializerBundle#827]
How do you view the transition to GitHub Actions - with more checks for compatibility with PHP version and Symfony versions?

I can help with that.

**Comment by goetas** [comment]
I'm personally fine with moving the project to github actions, if you want to create a PR moving the whole workflow from travis to GA, it would be great!

**Comment by Yozhef** [comment]
@goetas  create pull request -> https://github.com/schmittjoh/JMSSerializerBundle/pull/828/files
But in my fork all okay https://github.com/Yozhef/JMSSerializerBundle/pull/1

**Comment by goetas** [comment]
the bundle uses not github actions
