### ISSUE TITLE
Can't use incorrect type object for collection in Doctrine\ORM\PersistentCollection:owner

### ISSUE THREAD

**Issue by egd-gledoux** [schmittjoh/JMSSerializerBundle#846]
Hi,

I upgrade SerializeBundle from 3.8.0 to 3.9.0 and I get this error :

Can't use incorrect type object for collection in Doctrine\ORM\PersistentCollection:owner

When I try to serialize a collection of the same Entity (I use Gedmo NestedTree extention and I what to serialize children).

Do you know the reason why ?

**Comment by goetas** [comment]
see https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/3.9.1
