### ISSUE TITLE
Is there no support for Symfony 4.4?

### ISSUE THREAD

**Issue by sdonner-mobiletrend** [schmittjoh/JMSSerializerBundle#856]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I try to use the bundle in Symfony 4.4 but it doesn't seem to support 4.4 (require said ^3.0 || ^4.0 || ^5.0).
Shouldnt it be (~3.0 || ~4.0 || ~5.0)?

## Steps required to reproduce the problem

1. Run composer update symfony/framework-bundle:4.4 

## Expected Result

* success

## Actual Result

* Root composer.json requires symfony/framework-bundle ^4.4.0, 4.4, found symfony/framework-bundle[v4.4.0] but these were not loaded, likely because it conflicts with another require.

**Comment by W0rma** [comment]
> I try to use the bundle in Symfony 4.4 but it doesn't seem to support 4.4 (require said ^3.0 || ^4.0 || ^5.0).
> Shouldnt it be (~3.0 || ~4.0 || ~5.0)?

Please see https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators for an explanation of the release operators in composer.

Both `^4.0` and `~4.0` allow the installation of version `4.4`.

> Root composer.json requires symfony/framework-bundle ^4.4.0, 4.4, found symfony/framework-bundle[v4.4.0] but these were not loaded, likely because it conflicts with another require.

Maybe your app has another dependency which requires a higher version of `symfony/framework-bundle`. Have you already tried using `composer why symfony/framework-bundle`?

**Comment by goetas** [comment]
as suggested by @W0rma , this is probably an issue unrelated to jms serializer

**Comment by sdonner-mobiletrend** [comment]
oh sorry.. my bad. thanks for updating me ;)
