### ISSUE TITLE
Deserializing an entity make it present in Doctrine UnitOfWork

### ISSUE THREAD

**Issue by JEDIBC** [schmittjoh/JMSSerializerBundle#868]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

Hi,

I'm upgrading a project from JMSSerializerBundle `3.6.x` to the latest version and some integrations tests fails.
Basically I deserialize entities from XML and compare them with the entities present in the database.
My problem is that now when I deserialize from XML, the entity is present in Doctrine Unit Of Work and fetching the same entity from the database give me the one from the XML, not the data from the database.

Using a plain serializer built from `SerializerBuilder::create()->build()` works fine.

How can I disable the deserialization putting my entities in doctrine unit of work ?

Regards,

Bruno

## Steps required to reproduce the problem

1. Deserialize an entity from XML or JSON 
2. Inspect Doctrine unit of work

## Expected Result

* Unit of work empty

## Actual Result

* Unit of work filled with deserialized entity

**Comment by goetas** [comment]
1) can you reproduce it with a test please? 
2) does your entity have an ID? if yes, the `JMS\Serializer\Construction\DoctrineObjectConstructor` might be trying to load it from the DB.

**Comment by goetas** [comment]
can you check if https://github.com/schmittjoh/serializer/commit/2414b42ce3cd801a371cf9a31fdb5d00e8338c9f has introduced such behavior?

**Comment by JEDIBC** [comment]
> can you check if [schmittjoh/serializer@2414b42](https://github.com/schmittjoh/serializer/commit/2414b42ce3cd801a371cf9a31fdb5d00e8338c9f) has introduced such behavior?

Hi,

It is far older than that as the behavior appeared with JMSSerializerBundle 3.7.0

I'll make a test project ASAP.

Regards,

Bruno

**Comment by JEDIBC** [comment]
Here's the test project : https://github.com/JEDIBC/JMSSerializerBundle-issue868test
The README explain how to reproduce the issue (basically switching from serializer-bundle 3.6 to 3.7 makes the test fails.

**Comment by goetas** [comment]
Hi, thanks a lot for the GREAT reproducer :heart_eyes: . I could test the issue by my self!

The behavior in 3.6.0 is wrong and what is done in 3.7.0 is correct.

When unserializing an existing doctrine entity (with an ID), jms should look int doctrine first to avoid having multiple object instance representing the same doctrine entity. I believe that what was exposed in 3.6.0 should be considered as a bug.

However if you do not want such behavior you can set `jms_serializer.infer_types_from_doctrine_metadata: false` in your `parameter.yaml`.

**Comment by goetas** [comment]
In reality, we should introduce a second parameter `jms_serializer.unserialize_with_doctrine_metadata` to keep the type inference but to disable the object construction.

**Comment by JEDIBC** [comment]
Thank you it work perfectly fine now :+1: 
Are those parameters documented somewhere ? I can't find them on https://jmsyst.com/bundles/JMSSerializerBundle

Regards,

Bruno
