### ISSUE TITLE
Performance issue when enableMaxDepthChecks

### ISSUE THREAD

**Issue by aelfannir** [schmittjoh/JMSSerializerBundle#871]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no

I'm trying to serialize 1000 user entities, in a dev environment. 
- With `enableMaxDepthChecks` : ~ 50 sec
- Without `enableMaxDepthChecks` : ~ 1 sec

```php
public function serializer($entities)
{
    $context = new SerializationContext();
    $context
        ->enableMaxDepthChecks()
        ->setGroups(['DEFAULT'])
    ;
    $result = $this->serializer->serialize($entities, 'json', $context);

    return json_decode($result);
}
```
* Seems the issue comes from the 2nd expression in this condition 
https://github.com/schmittjoh/serializer/blob/a682e33e8d3811c8b7a6c5b2f92e05855f69edd5/src/Exclusion/DepthExclusionStrategy.php#L39-L41

**Comment by goetas** [comment]
lets keep the conversation in https://github.com/schmittjoh/serializer/issues/1347
