### ISSUE TITLE
Profiler issue after upgrade v3 to v4 (Sf4.4)

### ISSUE THREAD

**Issue by pag1903** [schmittjoh/JMSSerializerBundle#877]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hello,

I've just run a `composer update` and move from the v3.10.0 to the v4.0.1. Then the cache clear is failing with:

`You have requested a non-existent service "jms_serializer.handler_registry".`

I've tried to disable the debug in the config:
```
jms_serializer:
    profiler: false
```

This is solving my issue.

**Comment by goetas** [comment]
you need to update `friendsofsymfony/rest-bundle` to 3.1

**Comment by pag1903** [comment]
Thank you, I've upgrade `FOSRestBundle` to v3.1 and now it's working.
