### ISSUE TITLE
Problem with subscribing handlers after upgrade from 3.10.0 to 4.0.1

### ISSUE THREAD

**Issue by vkhramtsov** [schmittjoh/JMSSerializerBundle#879]
Hello,

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes?

## Steps required to reproduce the problem

1. Create symfony project
2. Install `jms/serializer-bundle` version `3.10.0`
3. Create subscribing handler (we are using autowire) for class like `\Exception` (we need to serialize objects of  \Exception and all it's descendants)
4. Try to serialize instance of `\Exception` or any it's descendants
5. Update `jms/serializer-bundle` to version `4.0.1`

## Expected Result
Both on 3.10.0 and 4.0.1 we have same result, i.e. call of configured method and serialize result.
 
## Actual Result
On `3.10.0`we have no issues, everything works as expected
On `4.0.1` Method not called, so everything works like no handler installed. After changing from `\Exception` to  particular descendant handler start work, but only with mentioned type, not with descendants.

Additional description:
The only change while upgrade is upgrade of jms/serializer-bundle with command `composer require jms/serializer-bundle:^4.0.1` with output
```
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading jms/serializer-bundle (3.10.0 => 4.0.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading jms/serializer-bundle (4.0.1)
  - Upgrading jms/serializer-bundle (3.10.0 => 4.0.1): Extracting archive
```
Php version is `8.0.12`, symfony version is `4.4.33`.

If you have any questions, don't hesitate to ask.

Thank you in advance.

**Comment by goetas** [comment]
Are you using this in combination with `friendsofsymfony/rest-bundle` ? if yes, that was a mentioned BC break in the https://github.com/schmittjoh/JMSSerializerBundle/blob/master/UPGRADING.md document

**Comment by vkhramtsov** [comment]
Thank you for clarification. You are right, I'm using fos rest bundle.
Do you have/know any option/workaround to return old behaviour? I cannot enum all exceptions in a project and I need same handler for all of them.

Thank you in advance.

**Comment by goetas** [comment]
You can decorate by your self the `jms_serializer.handler_registry` with an implementation as https://github.com/FriendsOfSymfony/FOSRestBundle/blob/cb75a41227ed5a9028fa3028c8225dda5c7b3086/Serializer/JMSHandlerRegistryV2.php

**Comment by vkhramtsov** [comment]
@goetas Thank you

**Comment by vkhramtsov** [comment]
Possible fix:
```yml
 FOS\RestBundle\Serializer\JMSHandlerRegistryV2:
        decorates: jms_serializer.handler_registry
        arguments:
            - '@FOS\RestBundle\Serializer\JMSHandlerRegistryV2.inner'
```
Just decorate JMS 4.0 handler registry with handler from FOS in services.yaml
