### ISSUE TITLE
Misnamed traceable metadata service in data collector

### ISSUE THREAD

**Issue by ajdinmore** [schmittjoh/JMSSerializerBundle#902]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Install bundle
2. Run application with debug enabled

## Expected Result

* Application runs

## Actual Result

* Application errors with the message `JMS\SerializerBundle\Debug\DataCollector::__construct(): Argument #4 ($metadataDriver) must be of type JMS\SerializerBundle\Debug\TraceableDriver, JMS\SerializerBundle\Debug\TraceableMetadataFactory given, called in /app/var/cache/dev/ContainerP6xo1xa/App_KernelDevDebugContainer.php on line 360`

**Comment by ajdinmore** [comment]
Just  to note: this breaks the currently active 4.1.0 release in environments with debug enabled.

**Comment by cizordj** [comment]
I'm having this problem right now. I can't clear the cache while in dev mode

Here is relevant part of my `composer.lock`:
```json
        ...
        {
            "name": "jms/serializer-bundle",
            "version": "4.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/schmittjoh/JMSSerializerBundle.git",
                "reference": "408ad721f9b7b5c1fb9bfff93f54868e946a12fd"
            },
        ...
```
Symfony `5.4.12`

**Comment by ajdinmore** [comment]
@cizordj In the short-term, you can solve the issue by locking your version to `4.0.*`

**Comment by cizordj** [comment]
@ajdinmore Thanks, that's what I ended up doing.

**Comment by adamoki** [comment]
I've also encounter the same problem, as mention above I've locked upgrade till issue is solve - probably it just needs renaming the metadataDriver property type.
