### ISSUE TITLE
Deprecation in : TraceableMetadataFactory

### ISSUE THREAD

**Issue by kiropowered** [schmittjoh/JMSSerializerBundle#907]
Hello,

It seems like there is some deprecations triggered :

`User Deprecated: Method "Metadata\MetadataFactoryInterface::getMetadataForClass()" might add "ClassHierarchyMetadata|MergeableClassMetadata|null" as a native return type declaration in the future. Do the same in implementation "JMS\SerializerBundle\Debug\TraceableMetadataFactory" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Metadata\\MetadataFactoryInterface::getMetadataForClass()\" might add \"ClassHierarchyMetadata|MergeableClassMetadata|null\" as a native return type declaration in the future. Do the same in implementation \"JMS\\SerializerBundle\\Debug\\TraceableMetadataFactory\" now to avoid errors or add an explicit @return annotation to suppress this message`

**Comment by scyzoryck** [comment]
@asuri0n - is it solved with the newly released fix?

**Comment by asuri0n** [comment]
yes
