### ISSUE TITLE
Union types are serialized to null

### ISSUE THREAD

**Issue by sgehrig** [schmittjoh/JMSSerializerBundle#953]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

This is just a cross-post of issue https://github.com/schmittjoh/serializer/issues/1565 reported by @dmaicher in https://github.com/schmittjoh/serializer. As suspected by @scyzoryck in https://github.com/schmittjoh/serializer/issues/1565#issuecomment-2455599664 it is indeed the missing configuration for the new `JMS\Serializer\Handler\UnionHandler` that leads to union types being serialized to `NULL`. 

## Steps required to reproduce the problem

Please see the OP at https://github.com/schmittjoh/serializer/issues/1565. Basically it happens whenever you serialise a union type in a context where the serialiser is configured using this bundle. 

## Expected Result

* union types are serialized correctly

## Actual Result

* union types are serialized to `NULL`

I can provide a pull request if it helps.

**Comment by scyzoryck** [comment]
5.5.1 released! :) Thanks for contribution!
